apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ioc-enrich

resources:
  - namespace.yaml
  - secrets.yaml
  - configmaps.yaml
  - postgres.yaml
  - redis.yaml
  - ti-enrichment.yaml
  - ioc-core.yaml
  - ioc-api-gateway.yaml

labels:
  - pairs:
      project: ioc-enrich-system
    includeSelectors: true
