apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: ioc-enrich
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: changeme-in-production
  DB_USERNAME: postgres
  DB_PASSWORD: changeme-in-production
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: ioc-enrich
type: Opaque
stringData:
  REDIS_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
  namespace: ioc-enrich
type: Opaque
stringData:
  JWT_SECRET: changeme-in-production
---
apiVersion: v1
kind: Secret
metadata:
  name: ti-api-keys
  namespace: ioc-enrich
type: Opaque
stringData:
  VIRUSTOTAL_API_KEY: "VIRUSTOTAL_API_KEY_PLACEHOLDER"
  ABUSEIPDB_API_KEY: "ABUSEIPDB_API_KEY_PLACEHOLDER"
  OTX_API_KEY: "OTX_API_KEY_PLACEHOLDER"
  HYBRID_ANALYSIS_API_KEY: "HYBRID_ANALYSIS_API_KEY_PLACEHOLDER"
