// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ioc/v1/common.proto

package iocv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IoCType int32

const (
	IoCType_IOC_TYPE_UNSPECIFIED IoCType = 0
	IoCType_IOC_TYPE_IP          IoCType = 1
	IoCType_IOC_TYPE_DOMAIN      IoCType = 2
	IoCType_IOC_TYPE_URL         IoCType = 3
	IoCType_IOC_TYPE_HASH_MD5    IoCType = 4
	IoCType_IOC_TYPE_HASH_SHA1   IoCType = 5
	IoCType_IOC_TYPE_HASH_SHA256 IoCType = 6
	IoCType_IOC_TYPE_FILE_PATH   IoCType = 7
)

// Enum value maps for IoCType.
var (
	IoCType_name = map[int32]string{
		0: "IOC_TYPE_UNSPECIFIED",
		1: "IOC_TYPE_IP",
		2: "IOC_TYPE_DOMAIN",
		3: "IOC_TYPE_URL",
		4: "IOC_TYPE_HASH_MD5",
		5: "IOC_TYPE_HASH_SHA1",
		6: "IOC_TYPE_HASH_SHA256",
		7: "IOC_TYPE_FILE_PATH",
	}
	IoCType_value = map[string]int32{
		"IOC_TYPE_UNSPECIFIED": 0,
		"IOC_TYPE_IP":          1,
		"IOC_TYPE_DOMAIN":      2,
		"IOC_TYPE_URL":         3,
		"IOC_TYPE_HASH_MD5":    4,
		"IOC_TYPE_HASH_SHA1":   5,
		"IOC_TYPE_HASH_SHA256": 6,
		"IOC_TYPE_FILE_PATH":   7,
	}
)

func (x IoCType) Enum() *IoCType {
	p := new(IoCType)
	*p = x
	return p
}

func (x IoCType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IoCType) Descriptor() protoreflect.EnumDescriptor {
	return file_ioc_v1_common_proto_enumTypes[0].Descriptor()
}

func (IoCType) Type() protoreflect.EnumType {
	return &file_ioc_v1_common_proto_enumTypes[0]
}

func (x IoCType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IoCType.Descriptor instead.
func (IoCType) EnumDescriptor() ([]byte, []int) {
	return file_ioc_v1_common_proto_rawDescGZIP(), []int{0}
}

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_INFO        Severity = 1
	Severity_SEVERITY_LOW         Severity = 2
	Severity_SEVERITY_MEDIUM      Severity = 3
	Severity_SEVERITY_HIGH        Severity = 4
	Severity_SEVERITY_CRITICAL    Severity = 5
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_INFO",
		2: "SEVERITY_LOW",
		3: "SEVERITY_MEDIUM",
		4: "SEVERITY_HIGH",
		5: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_INFO":        1,
		"SEVERITY_LOW":         2,
		"SEVERITY_MEDIUM":      3,
		"SEVERITY_HIGH":        4,
		"SEVERITY_CRITICAL":    5,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_ioc_v1_common_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_ioc_v1_common_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_ioc_v1_common_proto_rawDescGZIP(), []int{1}
}

type Verdict int32

const (
	Verdict_VERDICT_UNSPECIFIED    Verdict = 0
	Verdict_VERDICT_BENIGN         Verdict = 1
	Verdict_VERDICT_SUSPICIOUS     Verdict = 2
	Verdict_VERDICT_MALICIOUS      Verdict = 3
	Verdict_VERDICT_FALSE_POSITIVE Verdict = 4
	Verdict_VERDICT_UNKNOWN        Verdict = 5
)

// Enum value maps for Verdict.
var (
	Verdict_name = map[int32]string{
		0: "VERDICT_UNSPECIFIED",
		1: "VERDICT_BENIGN",
		2: "VERDICT_SUSPICIOUS",
		3: "VERDICT_MALICIOUS",
		4: "VERDICT_FALSE_POSITIVE",
		5: "VERDICT_UNKNOWN",
	}
	Verdict_value = map[string]int32{
		"VERDICT_UNSPECIFIED":    0,
		"VERDICT_BENIGN":         1,
		"VERDICT_SUSPICIOUS":     2,
		"VERDICT_MALICIOUS":      3,
		"VERDICT_FALSE_POSITIVE": 4,
		"VERDICT_UNKNOWN":        5,
	}
)

func (x Verdict) Enum() *Verdict {
	p := new(Verdict)
	*p = x
	return p
}

func (x Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_ioc_v1_common_proto_enumTypes[2].Descriptor()
}

func (Verdict) Type() protoreflect.EnumType {
	return &file_ioc_v1_common_proto_enumTypes[2]
}

func (x Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verdict.Descriptor instead.
func (Verdict) EnumDescriptor() ([]byte, []int) {
	return file_ioc_v1_common_proto_rawDescGZIP(), []int{2}
}

type ThreatCategory int32

const (
	ThreatCategory_THREAT_CATEGORY_UNSPECIFIED ThreatCategory = 0
	ThreatCategory_THREAT_CATEGORY_MALWARE     ThreatCategory = 1
	ThreatCategory_THREAT_CATEGORY_BOTNET      ThreatCategory = 2
	ThreatCategory_THREAT_CATEGORY_C2          ThreatCategory = 3
	ThreatCategory_THREAT_CATEGORY_EXPLOIT     ThreatCategory = 4
	ThreatCategory_THREAT_CATEGORY_PHISHING    ThreatCategory = 5
	ThreatCategory_THREAT_CATEGORY_SPAM        ThreatCategory = 6
)

// Enum value maps for ThreatCategory.
var (
	ThreatCategory_name = map[int32]string{
		0: "THREAT_CATEGORY_UNSPECIFIED",
		1: "THREAT_CATEGORY_MALWARE",
		2: "THREAT_CATEGORY_BOTNET",
		3: "THREAT_CATEGORY_C2",
		4: "THREAT_CATEGORY_EXPLOIT",
		5: "THREAT_CATEGORY_PHISHING",
		6: "THREAT_CATEGORY_SPAM",
	}
	ThreatCategory_value = map[string]int32{
		"THREAT_CATEGORY_UNSPECIFIED": 0,
		"THREAT_CATEGORY_MALWARE":     1,
		"THREAT_CATEGORY_BOTNET":      2,
		"THREAT_CATEGORY_C2":          3,
		"THREAT_CATEGORY_EXPLOIT":     4,
		"THREAT_CATEGORY_PHISHING":    5,
		"THREAT_CATEGORY_SPAM":        6,
	}
)

func (x ThreatCategory) Enum() *ThreatCategory {
	p := new(ThreatCategory)
	*p = x
	return p
}

func (x ThreatCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThreatCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_ioc_v1_common_proto_enumTypes[3].Descriptor()
}

func (ThreatCategory) Type() protoreflect.EnumType {
	return &file_ioc_v1_common_proto_enumTypes[3]
}

func (x ThreatCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThreatCategory.Descriptor instead.
func (ThreatCategory) EnumDescriptor() ([]byte, []int) {
	return file_ioc_v1_common_proto_rawDescGZIP(), []int{3}
}

type TLP int32

const (
	TLP_TLP_UNSPECIFIED  TLP = 0
	TLP_TLP_CLEAR        TLP = 1
	TLP_TLP_GREEN        TLP = 2
	TLP_TLP_AMBER        TLP = 3
	TLP_TLP_AMBER_STRICT TLP = 4
	TLP_TLP_RED          TLP = 5
)

// Enum value maps for TLP.
var (
	TLP_name = map[int32]string{
		0: "TLP_UNSPECIFIED",
		1: "TLP_CLEAR",
		2: "TLP_GREEN",
		3: "TLP_AMBER",
		4: "TLP_AMBER_STRICT",
		5: "TLP_RED",
	}
	TLP_value = map[string]int32{
		"TLP_UNSPECIFIED":  0,
		"TLP_CLEAR":        1,
		"TLP_GREEN":        2,
		"TLP_AMBER":        3,
		"TLP_AMBER_STRICT": 4,
		"TLP_RED":          5,
	}
)

func (x TLP) Enum() *TLP {
	p := new(TLP)
	*p = x
	return p
}

func (x TLP) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TLP) Descriptor() protoreflect.EnumDescriptor {
	return file_ioc_v1_common_proto_enumTypes[4].Descriptor()
}

func (TLP) Type() protoreflect.EnumType {
	return &file_ioc_v1_common_proto_enumTypes[4]
}

func (x TLP) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TLP.Descriptor instead.
func (TLP) EnumDescriptor() ([]byte, []int) {
	return file_ioc_v1_common_proto_rawDescGZIP(), []int{4}
}

type KillChainPhase int32

const (
	KillChainPhase_KILL_CHAIN_PHASE_UNSPECIFIED           KillChainPhase = 0
	KillChainPhase_KILL_CHAIN_PHASE_RECONNAISSANCE        KillChainPhase = 1
	KillChainPhase_KILL_CHAIN_PHASE_WEAPONIZATION         KillChainPhase = 2
	KillChainPhase_KILL_CHAIN_PHASE_DELIVERY              KillChainPhase = 3
	KillChainPhase_KILL_CHAIN_PHASE_EXPLOITATION          KillChainPhase = 4
	KillChainPhase_KILL_CHAIN_PHASE_INSTALLATION          KillChainPhase = 5
	KillChainPhase_KILL_CHAIN_PHASE_COMMAND_AND_CONTROL   KillChainPhase = 6
	KillChainPhase_KILL_CHAIN_PHASE_ACTIONS_ON_OBJECTIVES KillChainPhase = 7
)

// Enum value maps for KillChainPhase.
var (
	KillChainPhase_name = map[int32]string{
		0: "KILL_CHAIN_PHASE_UNSPECIFIED",
		1: "KILL_CHAIN_PHASE_RECONNAISSANCE",
		2: "KILL_CHAIN_PHASE_WEAPONIZATION",
		3: "KILL_CHAIN_PHASE_DELIVERY",
		4: "KILL_CHAIN_PHASE_EXPLOITATION",
		5: "KILL_CHAIN_PHASE_INSTALLATION",
		6: "KILL_CHAIN_PHASE_COMMAND_AND_CONTROL",
		7: "KILL_CHAIN_PHASE_ACTIONS_ON_OBJECTIVES",
	}
	KillChainPhase_value = map[string]int32{
		"KILL_CHAIN_PHASE_UNSPECIFIED":           0,
		"KILL_CHAIN_PHASE_RECONNAISSANCE":        1,
		"KILL_CHAIN_PHASE_WEAPONIZATION":         2,
		"KILL_CHAIN_PHASE_DELIVERY":              3,
		"KILL_CHAIN_PHASE_EXPLOITATION":          4,
		"KILL_CHAIN_PHASE_INSTALLATION":          5,
		"KILL_CHAIN_PHASE_COMMAND_AND_CONTROL":   6,
		"KILL_CHAIN_PHASE_ACTIONS_ON_OBJECTIVES": 7,
	}
)

func (x KillChainPhase) Enum() *KillChainPhase {
	p := new(KillChainPhase)
	*p = x
	return p
}

func (x KillChainPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KillChainPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_ioc_v1_common_proto_enumTypes[5].Descriptor()
}

func (KillChainPhase) Type() protoreflect.EnumType {
	return &file_ioc_v1_common_proto_enumTypes[5]
}

func (x KillChainPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KillChainPhase.Descriptor instead.
func (KillChainPhase) EnumDescriptor() ([]byte, []int) {
	return file_ioc_v1_common_proto_rawDescGZIP(), []int{5}
}

type EnrichmentSource int32

const (
	EnrichmentSource_ENRICHMENT_SOURCE_UNSPECIFIED     EnrichmentSource = 0
	EnrichmentSource_ENRICHMENT_SOURCE_VIRUSTOTAL      EnrichmentSource = 1
	EnrichmentSource_ENRICHMENT_SOURCE_ABUSEIPDB       EnrichmentSource = 2
	EnrichmentSource_ENRICHMENT_SOURCE_OTX             EnrichmentSource = 3
	EnrichmentSource_ENRICHMENT_SOURCE_HYBRID_ANALYSIS EnrichmentSource = 4
)

// Enum value maps for EnrichmentSource.
var (
	EnrichmentSource_name = map[int32]string{
		0: "ENRICHMENT_SOURCE_UNSPECIFIED",
		1: "ENRICHMENT_SOURCE_VIRUSTOTAL",
		2: "ENRICHMENT_SOURCE_ABUSEIPDB",
		3: "ENRICHMENT_SOURCE_OTX",
		4: "ENRICHMENT_SOURCE_HYBRID_ANALYSIS",
	}
	EnrichmentSource_value = map[string]int32{
		"ENRICHMENT_SOURCE_UNSPECIFIED":     0,
		"ENRICHMENT_SOURCE_VIRUSTOTAL":      1,
		"ENRICHMENT_SOURCE_ABUSEIPDB":       2,
		"ENRICHMENT_SOURCE_OTX":             3,
		"ENRICHMENT_SOURCE_HYBRID_ANALYSIS": 4,
	}
)

func (x EnrichmentSource) Enum() *EnrichmentSource {
	p := new(EnrichmentSource)
	*p = x
	return p
}

func (x EnrichmentSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnrichmentSource) Descriptor() protoreflect.EnumDescriptor {
	return file_ioc_v1_common_proto_enumTypes[6].Descriptor()
}

func (EnrichmentSource) Type() protoreflect.EnumType {
	return &file_ioc_v1_common_proto_enumTypes[6]
}

func (x EnrichmentSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnrichmentSource.Descriptor instead.
func (EnrichmentSource) EnumDescriptor() ([]byte, []int) {
	return file_ioc_v1_common_proto_rawDescGZIP(), []int{6}
}

type EnrichmentStatus int32

const (
	EnrichmentStatus_ENRICHMENT_STATUS_UNSPECIFIED EnrichmentStatus = 0
	EnrichmentStatus_ENRICHMENT_STATUS_PROCESSING  EnrichmentStatus = 2
	EnrichmentStatus_ENRICHMENT_STATUS_COMPLETED   EnrichmentStatus = 3
	EnrichmentStatus_ENRICHMENT_STATUS_FAILED      EnrichmentStatus = 4
	EnrichmentStatus_ENRICHMENT_STATUS_PARTIAL     EnrichmentStatus = 5
)

// Enum value maps for EnrichmentStatus.
var (
	EnrichmentStatus_name = map[int32]string{
		0: "ENRICHMENT_STATUS_UNSPECIFIED",
		2: "ENRICHMENT_STATUS_PROCESSING",
		3: "ENRICHMENT_STATUS_COMPLETED",
		4: "ENRICHMENT_STATUS_FAILED",
		5: "ENRICHMENT_STATUS_PARTIAL",
	}
	EnrichmentStatus_value = map[string]int32{
		"ENRICHMENT_STATUS_UNSPECIFIED": 0,
		"ENRICHMENT_STATUS_PROCESSING":  2,
		"ENRICHMENT_STATUS_COMPLETED":   3,
		"ENRICHMENT_STATUS_FAILED":      4,
		"ENRICHMENT_STATUS_PARTIAL":     5,
	}
)

func (x EnrichmentStatus) Enum() *EnrichmentStatus {
	p := new(EnrichmentStatus)
	*p = x
	return p
}

func (x EnrichmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnrichmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ioc_v1_common_proto_enumTypes[7].Descriptor()
}

func (EnrichmentStatus) Type() protoreflect.EnumType {
	return &file_ioc_v1_common_proto_enumTypes[7]
}

func (x EnrichmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnrichmentStatus.Descriptor instead.
func (EnrichmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_ioc_v1_common_proto_rawDescGZIP(), []int{7}
}

type RelationType int32

const (
	RelationType_RELATION_TYPE_UNSPECIFIED       RelationType = 0
	RelationType_RELATION_TYPE_SAME_CAMPAIGN     RelationType = 1
	RelationType_RELATION_TYPE_SAME_THREAT_ACTOR RelationType = 2
	RelationType_RELATION_TYPE_SAME_FAMILY       RelationType = 3
	RelationType_RELATION_TYPE_RESOLVES_TO       RelationType = 4
	RelationType_RELATION_TYPE_COMMUNICATES_WITH RelationType = 5
	RelationType_RELATION_TYPE_DOWNLOADED_FROM   RelationType = 6
	RelationType_RELATION_TYPE_DROPS             RelationType = 7
)

// Enum value maps for RelationType.
var (
	RelationType_name = map[int32]string{
		0: "RELATION_TYPE_UNSPECIFIED",
		1: "RELATION_TYPE_SAME_CAMPAIGN",
		2: "RELATION_TYPE_SAME_THREAT_ACTOR",
		3: "RELATION_TYPE_SAME_FAMILY",
		4: "RELATION_TYPE_RESOLVES_TO",
		5: "RELATION_TYPE_COMMUNICATES_WITH",
		6: "RELATION_TYPE_DOWNLOADED_FROM",
		7: "RELATION_TYPE_DROPS",
	}
	RelationType_value = map[string]int32{
		"RELATION_TYPE_UNSPECIFIED":       0,
		"RELATION_TYPE_SAME_CAMPAIGN":     1,
		"RELATION_TYPE_SAME_THREAT_ACTOR": 2,
		"RELATION_TYPE_SAME_FAMILY":       3,
		"RELATION_TYPE_RESOLVES_TO":       4,
		"RELATION_TYPE_COMMUNICATES_WITH": 5,
		"RELATION_TYPE_DOWNLOADED_FROM":   6,
		"RELATION_TYPE_DROPS":             7,
	}
)

func (x RelationType) Enum() *RelationType {
	p := new(RelationType)
	*p = x
	return p
}

func (x RelationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelationType) Descriptor() protoreflect.EnumDescriptor {
	return file_ioc_v1_common_proto_enumTypes[8].Descriptor()
}

func (RelationType) Type() protoreflect.EnumType {
	return &file_ioc_v1_common_proto_enumTypes[8]
}

func (x RelationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelationType.Descriptor instead.
func (RelationType) EnumDescriptor() ([]byte, []int) {
	return file_ioc_v1_common_proto_rawDescGZIP(), []int{8}
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_ioc_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_ioc_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *Pagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_ioc_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_ioc_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type SortOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SortBy        []string               `protobuf:"bytes,1,rep,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortDesc      bool                   `protobuf:"varint,2,opt,name=sort_desc,json=sortDesc,proto3" json:"sort_desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortOptions) Reset() {
	*x = SortOptions{}
	mi := &file_ioc_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortOptions) ProtoMessage() {}

func (x *SortOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortOptions.ProtoReflect.Descriptor instead.
func (*SortOptions) Descriptor() ([]byte, []int) {
	return file_ioc_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *SortOptions) GetSortBy() []string {
	if x != nil {
		return x.SortBy
	}
	return nil
}

func (x *SortOptions) GetSortDesc() bool {
	if x != nil {
		return x.SortDesc
	}
	return false
}

var File_ioc_v1_common_proto protoreflect.FileDescriptor

const file_ioc_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x13ioc/v1/common.proto\x12\x06ioc.v1\"\x7f\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"\xa7\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\adetails\x18\x03 \x03(\v2\x1a.ioc.v1.Error.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\vSortOptions\x12\x17\n" +
	"\asort_by\x18\x01 \x03(\tR\x06sortBy\x12\x1b\n" +
	"\tsort_desc\x18\x02 \x01(\bR\bsortDesc*\xbc\x01\n" +
	"\aIoCType\x12\x18\n" +
	"\x14IOC_TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vIOC_TYPE_IP\x10\x01\x12\x13\n" +
	"\x0fIOC_TYPE_DOMAIN\x10\x02\x12\x10\n" +
	"\fIOC_TYPE_URL\x10\x03\x12\x15\n" +
	"\x11IOC_TYPE_HASH_MD5\x10\x04\x12\x16\n" +
	"\x12IOC_TYPE_HASH_SHA1\x10\x05\x12\x18\n" +
	"\x14IOC_TYPE_HASH_SHA256\x10\x06\x12\x16\n" +
	"\x12IOC_TYPE_FILE_PATH\x10\a*\x88\x01\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x01\x12\x10\n" +
	"\fSEVERITY_LOW\x10\x02\x12\x13\n" +
	"\x0fSEVERITY_MEDIUM\x10\x03\x12\x11\n" +
	"\rSEVERITY_HIGH\x10\x04\x12\x15\n" +
	"\x11SEVERITY_CRITICAL\x10\x05*\x96\x01\n" +
	"\aVerdict\x12\x17\n" +
	"\x13VERDICT_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eVERDICT_BENIGN\x10\x01\x12\x16\n" +
	"\x12VERDICT_SUSPICIOUS\x10\x02\x12\x15\n" +
	"\x11VERDICT_MALICIOUS\x10\x03\x12\x1a\n" +
	"\x16VERDICT_FALSE_POSITIVE\x10\x04\x12\x13\n" +
	"\x0fVERDICT_UNKNOWN\x10\x05*\xd7\x01\n" +
	"\x0eThreatCategory\x12\x1f\n" +
	"\x1bTHREAT_CATEGORY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17THREAT_CATEGORY_MALWARE\x10\x01\x12\x1a\n" +
	"\x16THREAT_CATEGORY_BOTNET\x10\x02\x12\x16\n" +
	"\x12THREAT_CATEGORY_C2\x10\x03\x12\x1b\n" +
	"\x17THREAT_CATEGORY_EXPLOIT\x10\x04\x12\x1c\n" +
	"\x18THREAT_CATEGORY_PHISHING\x10\x05\x12\x18\n" +
	"\x14THREAT_CATEGORY_SPAM\x10\x06*j\n" +
	"\x03TLP\x12\x13\n" +
	"\x0fTLP_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tTLP_CLEAR\x10\x01\x12\r\n" +
	"\tTLP_GREEN\x10\x02\x12\r\n" +
	"\tTLP_AMBER\x10\x03\x12\x14\n" +
	"\x10TLP_AMBER_STRICT\x10\x04\x12\v\n" +
	"\aTLP_RED\x10\x05*\xb6\x02\n" +
	"\x0eKillChainPhase\x12 \n" +
	"\x1cKILL_CHAIN_PHASE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fKILL_CHAIN_PHASE_RECONNAISSANCE\x10\x01\x12\"\n" +
	"\x1eKILL_CHAIN_PHASE_WEAPONIZATION\x10\x02\x12\x1d\n" +
	"\x19KILL_CHAIN_PHASE_DELIVERY\x10\x03\x12!\n" +
	"\x1dKILL_CHAIN_PHASE_EXPLOITATION\x10\x04\x12!\n" +
	"\x1dKILL_CHAIN_PHASE_INSTALLATION\x10\x05\x12(\n" +
	"$KILL_CHAIN_PHASE_COMMAND_AND_CONTROL\x10\x06\x12*\n" +
	"&KILL_CHAIN_PHASE_ACTIONS_ON_OBJECTIVES\x10\a*\xba\x01\n" +
	"\x10EnrichmentSource\x12!\n" +
	"\x1dENRICHMENT_SOURCE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cENRICHMENT_SOURCE_VIRUSTOTAL\x10\x01\x12\x1f\n" +
	"\x1bENRICHMENT_SOURCE_ABUSEIPDB\x10\x02\x12\x19\n" +
	"\x15ENRICHMENT_SOURCE_OTX\x10\x03\x12%\n" +
	"!ENRICHMENT_SOURCE_HYBRID_ANALYSIS\x10\x04*\xb5\x01\n" +
	"\x10EnrichmentStatus\x12!\n" +
	"\x1dENRICHMENT_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cENRICHMENT_STATUS_PROCESSING\x10\x02\x12\x1f\n" +
	"\x1bENRICHMENT_STATUS_COMPLETED\x10\x03\x12\x1c\n" +
	"\x18ENRICHMENT_STATUS_FAILED\x10\x04\x12\x1d\n" +
	"\x19ENRICHMENT_STATUS_PARTIAL\x10\x05*\x92\x02\n" +
	"\fRelationType\x12\x1d\n" +
	"\x19RELATION_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bRELATION_TYPE_SAME_CAMPAIGN\x10\x01\x12#\n" +
	"\x1fRELATION_TYPE_SAME_THREAT_ACTOR\x10\x02\x12\x1d\n" +
	"\x19RELATION_TYPE_SAME_FAMILY\x10\x03\x12\x1d\n" +
	"\x19RELATION_TYPE_RESOLVES_TO\x10\x04\x12#\n" +
	"\x1fRELATION_TYPE_COMMUNICATES_WITH\x10\x05\x12!\n" +
	"\x1dRELATION_TYPE_DOWNLOADED_FROM\x10\x06\x12\x17\n" +
	"\x13RELATION_TYPE_DROPS\x10\aBBZ@github.com/DgHnG36/ioc_enrichment_service/shared/go/ioc/v1;iocv1b\x06proto3"

var (
	file_ioc_v1_common_proto_rawDescOnce sync.Once
	file_ioc_v1_common_proto_rawDescData []byte
)

func file_ioc_v1_common_proto_rawDescGZIP() []byte {
	file_ioc_v1_common_proto_rawDescOnce.Do(func() {
		file_ioc_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ioc_v1_common_proto_rawDesc), len(file_ioc_v1_common_proto_rawDesc)))
	})
	return file_ioc_v1_common_proto_rawDescData
}

var file_ioc_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_ioc_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ioc_v1_common_proto_goTypes = []any{
	(IoCType)(0),          // 0: ioc.v1.IoCType
	(Severity)(0),         // 1: ioc.v1.Severity
	(Verdict)(0),          // 2: ioc.v1.Verdict
	(ThreatCategory)(0),   // 3: ioc.v1.ThreatCategory
	(TLP)(0),              // 4: ioc.v1.TLP
	(KillChainPhase)(0),   // 5: ioc.v1.KillChainPhase
	(EnrichmentSource)(0), // 6: ioc.v1.EnrichmentSource
	(EnrichmentStatus)(0), // 7: ioc.v1.EnrichmentStatus
	(RelationType)(0),     // 8: ioc.v1.RelationType
	(*Pagination)(nil),    // 9: ioc.v1.Pagination
	(*Error)(nil),         // 10: ioc.v1.Error
	(*SortOptions)(nil),   // 11: ioc.v1.SortOptions
	nil,                   // 12: ioc.v1.Error.DetailsEntry
}
var file_ioc_v1_common_proto_depIdxs = []int32{
	12, // 0: ioc.v1.Error.details:type_name -> ioc.v1.Error.DetailsEntry
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_ioc_v1_common_proto_init() }
func file_ioc_v1_common_proto_init() {
	if File_ioc_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ioc_v1_common_proto_rawDesc), len(file_ioc_v1_common_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ioc_v1_common_proto_goTypes,
		DependencyIndexes: file_ioc_v1_common_proto_depIdxs,
		EnumInfos:         file_ioc_v1_common_proto_enumTypes,
		MessageInfos:      file_ioc_v1_common_proto_msgTypes,
	}.Build()
	File_ioc_v1_common_proto = out.File
	file_ioc_v1_common_proto_goTypes = nil
	file_ioc_v1_common_proto_depIdxs = nil
}
