// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ioc/v1/ioc.proto

package iocv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IoC struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type              IoCType                `protobuf:"varint,2,opt,name=type,proto3,enum=ioc.v1.IoCType" json:"type,omitempty"`
	Value             string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Verdict           Verdict                `protobuf:"varint,4,opt,name=verdict,proto3,enum=ioc.v1.Verdict" json:"verdict,omitempty"`
	Severity          Severity               `protobuf:"varint,5,opt,name=severity,proto3,enum=ioc.v1.Severity" json:"severity,omitempty"`
	Source            string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Description       string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpiresAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Tags              []string               `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	ThreatContext     *ThreatContext         `protobuf:"bytes,12,opt,name=threat_context,json=threatContext,proto3" json:"threat_context,omitempty"`
	EnrichmentSummary *EnrichmentSummary     `protobuf:"bytes,13,opt,name=enrichment_summary,json=enrichmentSummary,proto3" json:"enrichment_summary,omitempty"`
	Metadata          *IoCMetadata           `protobuf:"bytes,14,opt,name=metadata,proto3" json:"metadata,omitempty"`
	IsActive          bool                   `protobuf:"varint,15,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	DetectionCount    int32                  `protobuf:"varint,16,opt,name=detection_count,json=detectionCount,proto3" json:"detection_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IoC) Reset() {
	*x = IoC{}
	mi := &file_ioc_v1_ioc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IoC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IoC) ProtoMessage() {}

func (x *IoC) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_ioc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IoC.ProtoReflect.Descriptor instead.
func (*IoC) Descriptor() ([]byte, []int) {
	return file_ioc_v1_ioc_proto_rawDescGZIP(), []int{0}
}

func (x *IoC) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IoC) GetType() IoCType {
	if x != nil {
		return x.Type
	}
	return IoCType_IOC_TYPE_UNSPECIFIED
}

func (x *IoC) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *IoC) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_UNSPECIFIED
}

func (x *IoC) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *IoC) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IoC) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IoC) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *IoC) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *IoC) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *IoC) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *IoC) GetThreatContext() *ThreatContext {
	if x != nil {
		return x.ThreatContext
	}
	return nil
}

func (x *IoC) GetEnrichmentSummary() *EnrichmentSummary {
	if x != nil {
		return x.EnrichmentSummary
	}
	return nil
}

func (x *IoC) GetMetadata() *IoCMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *IoC) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *IoC) GetDetectionCount() int32 {
	if x != nil {
		return x.DetectionCount
	}
	return 0
}

type ThreatContext struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConfidenceScore float32                `protobuf:"fixed32,1,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	Categories      []ThreatCategory       `protobuf:"varint,2,rep,packed,name=categories,proto3,enum=ioc.v1.ThreatCategory" json:"categories,omitempty"`
	KillChainPhase  KillChainPhase         `protobuf:"varint,3,opt,name=kill_chain_phase,json=killChainPhase,proto3,enum=ioc.v1.KillChainPhase" json:"kill_chain_phase,omitempty"`
	ThreatActors    []string               `protobuf:"bytes,4,rep,name=threat_actors,json=threatActors,proto3" json:"threat_actors,omitempty"`
	Campaigns       []string               `protobuf:"bytes,5,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ThreatContext) Reset() {
	*x = ThreatContext{}
	mi := &file_ioc_v1_ioc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatContext) ProtoMessage() {}

func (x *ThreatContext) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_ioc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatContext.ProtoReflect.Descriptor instead.
func (*ThreatContext) Descriptor() ([]byte, []int) {
	return file_ioc_v1_ioc_proto_rawDescGZIP(), []int{1}
}

func (x *ThreatContext) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *ThreatContext) GetCategories() []ThreatCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ThreatContext) GetKillChainPhase() KillChainPhase {
	if x != nil {
		return x.KillChainPhase
	}
	return KillChainPhase_KILL_CHAIN_PHASE_UNSPECIFIED
}

func (x *ThreatContext) GetThreatActors() []string {
	if x != nil {
		return x.ThreatActors
	}
	return nil
}

func (x *ThreatContext) GetCampaigns() []string {
	if x != nil {
		return x.Campaigns
	}
	return nil
}

type EnrichmentSummary struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	TotalSources    int32                    `protobuf:"varint,1,opt,name=total_sources,json=totalSources,proto3" json:"total_sources,omitempty"`
	MaliciousCount  int32                    `protobuf:"varint,2,opt,name=malicious_count,json=maliciousCount,proto3" json:"malicious_count,omitempty"`
	SuspiciousCount int32                    `protobuf:"varint,3,opt,name=suspicious_count,json=suspiciousCount,proto3" json:"suspicious_count,omitempty"`
	BenignCount     int32                    `protobuf:"varint,4,opt,name=benign_count,json=benignCount,proto3" json:"benign_count,omitempty"`
	LastEnriched    *timestamppb.Timestamp   `protobuf:"bytes,5,opt,name=last_enriched,json=lastEnriched,proto3" json:"last_enriched,omitempty"`
	SourceDetails   map[string]*SourceResult `protobuf:"bytes,6,rep,name=source_details,json=sourceDetails,proto3" json:"source_details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrichmentSummary) Reset() {
	*x = EnrichmentSummary{}
	mi := &file_ioc_v1_ioc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichmentSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichmentSummary) ProtoMessage() {}

func (x *EnrichmentSummary) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_ioc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichmentSummary.ProtoReflect.Descriptor instead.
func (*EnrichmentSummary) Descriptor() ([]byte, []int) {
	return file_ioc_v1_ioc_proto_rawDescGZIP(), []int{2}
}

func (x *EnrichmentSummary) GetTotalSources() int32 {
	if x != nil {
		return x.TotalSources
	}
	return 0
}

func (x *EnrichmentSummary) GetMaliciousCount() int32 {
	if x != nil {
		return x.MaliciousCount
	}
	return 0
}

func (x *EnrichmentSummary) GetSuspiciousCount() int32 {
	if x != nil {
		return x.SuspiciousCount
	}
	return 0
}

func (x *EnrichmentSummary) GetBenignCount() int32 {
	if x != nil {
		return x.BenignCount
	}
	return 0
}

func (x *EnrichmentSummary) GetLastEnriched() *timestamppb.Timestamp {
	if x != nil {
		return x.LastEnriched
	}
	return nil
}

func (x *EnrichmentSummary) GetSourceDetails() map[string]*SourceResult {
	if x != nil {
		return x.SourceDetails
	}
	return nil
}

type SourceResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceName    string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	IsMalicious   bool                   `protobuf:"varint,2,opt,name=is_malicious,json=isMalicious,proto3" json:"is_malicious,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	Verdict       string                 `protobuf:"bytes,4,opt,name=verdict,proto3" json:"verdict,omitempty"`
	CheckedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	RawData       *structpb.Struct       `protobuf:"bytes,6,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceResult) Reset() {
	*x = SourceResult{}
	mi := &file_ioc_v1_ioc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceResult) ProtoMessage() {}

func (x *SourceResult) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_ioc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceResult.ProtoReflect.Descriptor instead.
func (*SourceResult) Descriptor() ([]byte, []int) {
	return file_ioc_v1_ioc_proto_rawDescGZIP(), []int{3}
}

func (x *SourceResult) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *SourceResult) GetIsMalicious() bool {
	if x != nil {
		return x.IsMalicious
	}
	return false
}

func (x *SourceResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SourceResult) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *SourceResult) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

func (x *SourceResult) GetRawData() *structpb.Struct {
	if x != nil {
		return x.RawData
	}
	return nil
}

type IoCMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomFields  *structpb.Struct       `protobuf:"bytes,1,opt,name=custom_fields,json=customFields,proto3" json:"custom_fields,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,3,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IoCMetadata) Reset() {
	*x = IoCMetadata{}
	mi := &file_ioc_v1_ioc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IoCMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IoCMetadata) ProtoMessage() {}

func (x *IoCMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_ioc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IoCMetadata.ProtoReflect.Descriptor instead.
func (*IoCMetadata) Descriptor() ([]byte, []int) {
	return file_ioc_v1_ioc_proto_rawDescGZIP(), []int{4}
}

func (x *IoCMetadata) GetCustomFields() *structpb.Struct {
	if x != nil {
		return x.CustomFields
	}
	return nil
}

func (x *IoCMetadata) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *IoCMetadata) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type RelatedIoC struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IocId           string                 `protobuf:"bytes,1,opt,name=ioc_id,json=iocId,proto3" json:"ioc_id,omitempty"`
	Value           string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type            IoCType                `protobuf:"varint,3,opt,name=type,proto3,enum=ioc.v1.IoCType" json:"type,omitempty"`
	RelationType    RelationType           `protobuf:"varint,4,opt,name=relation_type,json=relationType,proto3,enum=ioc.v1.RelationType" json:"relation_type,omitempty"`
	SimilarityScore float32                `protobuf:"fixed32,5,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
	Source          string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Description     string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RelatedIoC) Reset() {
	*x = RelatedIoC{}
	mi := &file_ioc_v1_ioc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelatedIoC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelatedIoC) ProtoMessage() {}

func (x *RelatedIoC) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_ioc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelatedIoC.ProtoReflect.Descriptor instead.
func (*RelatedIoC) Descriptor() ([]byte, []int) {
	return file_ioc_v1_ioc_proto_rawDescGZIP(), []int{5}
}

func (x *RelatedIoC) GetIocId() string {
	if x != nil {
		return x.IocId
	}
	return ""
}

func (x *RelatedIoC) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *RelatedIoC) GetType() IoCType {
	if x != nil {
		return x.Type
	}
	return IoCType_IOC_TYPE_UNSPECIFIED
}

func (x *RelatedIoC) GetRelationType() RelationType {
	if x != nil {
		return x.RelationType
	}
	return RelationType_RELATION_TYPE_UNSPECIFIED
}

func (x *RelatedIoC) GetSimilarityScore() float32 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

func (x *RelatedIoC) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RelatedIoC) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type IoCFilter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SearchQuery    string                 `protobuf:"bytes,1,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	Type           IoCType                `protobuf:"varint,2,opt,name=type,proto3,enum=ioc.v1.IoCType" json:"type,omitempty"`
	Severity       Severity               `protobuf:"varint,3,opt,name=severity,proto3,enum=ioc.v1.Severity" json:"severity,omitempty"`
	Verdict        Verdict                `protobuf:"varint,4,opt,name=verdict,proto3,enum=ioc.v1.Verdict" json:"verdict,omitempty"`
	Source         string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Tags           []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	KillChainPhase KillChainPhase         `protobuf:"varint,7,opt,name=kill_chain_phase,json=killChainPhase,proto3,enum=ioc.v1.KillChainPhase" json:"kill_chain_phase,omitempty"`
	IsActive       bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	StartDate      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IoCFilter) Reset() {
	*x = IoCFilter{}
	mi := &file_ioc_v1_ioc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IoCFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IoCFilter) ProtoMessage() {}

func (x *IoCFilter) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_ioc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IoCFilter.ProtoReflect.Descriptor instead.
func (*IoCFilter) Descriptor() ([]byte, []int) {
	return file_ioc_v1_ioc_proto_rawDescGZIP(), []int{6}
}

func (x *IoCFilter) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *IoCFilter) GetType() IoCType {
	if x != nil {
		return x.Type
	}
	return IoCType_IOC_TYPE_UNSPECIFIED
}

func (x *IoCFilter) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *IoCFilter) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_UNSPECIFIED
}

func (x *IoCFilter) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IoCFilter) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *IoCFilter) GetKillChainPhase() KillChainPhase {
	if x != nil {
		return x.KillChainPhase
	}
	return KillChainPhase_KILL_CHAIN_PHASE_UNSPECIFIED
}

func (x *IoCFilter) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *IoCFilter) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *IoCFilter) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type IoCStatistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalIocs     int32                  `protobuf:"varint,1,opt,name=total_iocs,json=totalIocs,proto3" json:"total_iocs,omitempty"`
	ActiveIocs    int32                  `protobuf:"varint,2,opt,name=active_iocs,json=activeIocs,proto3" json:"active_iocs,omitempty"`
	ByType        map[string]int32       `protobuf:"bytes,3,rep,name=by_type,json=byType,proto3" json:"by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	BySeverity    map[string]int32       `protobuf:"bytes,4,rep,name=by_severity,json=bySeverity,proto3" json:"by_severity,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ByVerdict     map[string]int32       `protobuf:"bytes,5,rep,name=by_verdict,json=byVerdict,proto3" json:"by_verdict,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IoCStatistics) Reset() {
	*x = IoCStatistics{}
	mi := &file_ioc_v1_ioc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IoCStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IoCStatistics) ProtoMessage() {}

func (x *IoCStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_ioc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IoCStatistics.ProtoReflect.Descriptor instead.
func (*IoCStatistics) Descriptor() ([]byte, []int) {
	return file_ioc_v1_ioc_proto_rawDescGZIP(), []int{7}
}

func (x *IoCStatistics) GetTotalIocs() int32 {
	if x != nil {
		return x.TotalIocs
	}
	return 0
}

func (x *IoCStatistics) GetActiveIocs() int32 {
	if x != nil {
		return x.ActiveIocs
	}
	return 0
}

func (x *IoCStatistics) GetByType() map[string]int32 {
	if x != nil {
		return x.ByType
	}
	return nil
}

func (x *IoCStatistics) GetBySeverity() map[string]int32 {
	if x != nil {
		return x.BySeverity
	}
	return nil
}

func (x *IoCStatistics) GetByVerdict() map[string]int32 {
	if x != nil {
		return x.ByVerdict
	}
	return nil
}

func (x *IoCStatistics) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

var File_ioc_v1_ioc_proto protoreflect.FileDescriptor

const file_ioc_v1_ioc_proto_rawDesc = "" +
	"\n" +
	"\x10ioc/v1/ioc.proto\x12\x06ioc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x13ioc/v1/common.proto\"\xa7\x05\n" +
	"\x03IoC\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0f.ioc.v1.IoCTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12)\n" +
	"\averdict\x18\x04 \x01(\x0e2\x0f.ioc.v1.VerdictR\averdict\x12,\n" +
	"\bseverity\x18\x05 \x01(\x0e2\x10.ioc.v1.SeverityR\bseverity\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\x12<\n" +
	"\x0ethreat_context\x18\f \x01(\v2\x15.ioc.v1.ThreatContextR\rthreatContext\x12H\n" +
	"\x12enrichment_summary\x18\r \x01(\v2\x19.ioc.v1.EnrichmentSummaryR\x11enrichmentSummary\x12/\n" +
	"\bmetadata\x18\x0e \x01(\v2\x13.ioc.v1.IoCMetadataR\bmetadata\x12\x1b\n" +
	"\tis_active\x18\x0f \x01(\bR\bisActive\x12'\n" +
	"\x0fdetection_count\x18\x10 \x01(\x05R\x0edetectionCount\"\xf7\x01\n" +
	"\rThreatContext\x12)\n" +
	"\x10confidence_score\x18\x01 \x01(\x02R\x0fconfidenceScore\x126\n" +
	"\n" +
	"categories\x18\x02 \x03(\x0e2\x16.ioc.v1.ThreatCategoryR\n" +
	"categories\x12@\n" +
	"\x10kill_chain_phase\x18\x03 \x01(\x0e2\x16.ioc.v1.KillChainPhaseR\x0ekillChainPhase\x12#\n" +
	"\rthreat_actors\x18\x04 \x03(\tR\fthreatActors\x12\x1c\n" +
	"\tcampaigns\x18\x05 \x03(\tR\tcampaigns\"\x9d\x03\n" +
	"\x11EnrichmentSummary\x12#\n" +
	"\rtotal_sources\x18\x01 \x01(\x05R\ftotalSources\x12'\n" +
	"\x0fmalicious_count\x18\x02 \x01(\x05R\x0emaliciousCount\x12)\n" +
	"\x10suspicious_count\x18\x03 \x01(\x05R\x0fsuspiciousCount\x12!\n" +
	"\fbenign_count\x18\x04 \x01(\x05R\vbenignCount\x12?\n" +
	"\rlast_enriched\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\flastEnriched\x12S\n" +
	"\x0esource_details\x18\x06 \x03(\v2,.ioc.v1.EnrichmentSummary.SourceDetailsEntryR\rsourceDetails\x1aV\n" +
	"\x12SourceDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.ioc.v1.SourceResultR\x05value:\x028\x01\"\xf1\x01\n" +
	"\fSourceResult\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12!\n" +
	"\fis_malicious\x18\x02 \x01(\bR\visMalicious\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12\x18\n" +
	"\averdict\x18\x04 \x01(\tR\averdict\x129\n" +
	"\n" +
	"checked_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\x122\n" +
	"\braw_data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\arawData\"\x89\x01\n" +
	"\vIoCMetadata\x12<\n" +
	"\rcustom_fields\x18\x01 \x01(\v2\x17.google.protobuf.StructR\fcustomFields\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x03 \x01(\tR\tupdatedBy\"\xfe\x01\n" +
	"\n" +
	"RelatedIoC\x12\x15\n" +
	"\x06ioc_id\x18\x01 \x01(\tR\x05iocId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12#\n" +
	"\x04type\x18\x03 \x01(\x0e2\x0f.ioc.v1.IoCTypeR\x04type\x129\n" +
	"\rrelation_type\x18\x04 \x01(\x0e2\x14.ioc.v1.RelationTypeR\frelationType\x12)\n" +
	"\x10similarity_score\x18\x05 \x01(\x02R\x0fsimilarityScore\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"\xa9\x03\n" +
	"\tIoCFilter\x12!\n" +
	"\fsearch_query\x18\x01 \x01(\tR\vsearchQuery\x12#\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0f.ioc.v1.IoCTypeR\x04type\x12,\n" +
	"\bseverity\x18\x03 \x01(\x0e2\x10.ioc.v1.SeverityR\bseverity\x12)\n" +
	"\averdict\x18\x04 \x01(\x0e2\x0f.ioc.v1.VerdictR\averdict\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12@\n" +
	"\x10kill_chain_phase\x18\a \x01(\x0e2\x16.ioc.v1.KillChainPhaseR\x0ekillChainPhase\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x129\n" +
	"\n" +
	"start_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\x8f\x04\n" +
	"\rIoCStatistics\x12\x1d\n" +
	"\n" +
	"total_iocs\x18\x01 \x01(\x05R\ttotalIocs\x12\x1f\n" +
	"\vactive_iocs\x18\x02 \x01(\x05R\n" +
	"activeIocs\x12:\n" +
	"\aby_type\x18\x03 \x03(\v2!.ioc.v1.IoCStatistics.ByTypeEntryR\x06byType\x12F\n" +
	"\vby_severity\x18\x04 \x03(\v2%.ioc.v1.IoCStatistics.BySeverityEntryR\n" +
	"bySeverity\x12C\n" +
	"\n" +
	"by_verdict\x18\x05 \x03(\v2$.ioc.v1.IoCStatistics.ByVerdictEntryR\tbyVerdict\x12=\n" +
	"\fgenerated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x1a9\n" +
	"\vByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a=\n" +
	"\x0fBySeverityEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a<\n" +
	"\x0eByVerdictEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01BBZ@github.com/DgHnG36/ioc_enrichment_service/shared/go/ioc/v1;iocv1b\x06proto3"

var (
	file_ioc_v1_ioc_proto_rawDescOnce sync.Once
	file_ioc_v1_ioc_proto_rawDescData []byte
)

func file_ioc_v1_ioc_proto_rawDescGZIP() []byte {
	file_ioc_v1_ioc_proto_rawDescOnce.Do(func() {
		file_ioc_v1_ioc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ioc_v1_ioc_proto_rawDesc), len(file_ioc_v1_ioc_proto_rawDesc)))
	})
	return file_ioc_v1_ioc_proto_rawDescData
}

var file_ioc_v1_ioc_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_ioc_v1_ioc_proto_goTypes = []any{
	(*IoC)(nil),                   // 0: ioc.v1.IoC
	(*ThreatContext)(nil),         // 1: ioc.v1.ThreatContext
	(*EnrichmentSummary)(nil),     // 2: ioc.v1.EnrichmentSummary
	(*SourceResult)(nil),          // 3: ioc.v1.SourceResult
	(*IoCMetadata)(nil),           // 4: ioc.v1.IoCMetadata
	(*RelatedIoC)(nil),            // 5: ioc.v1.RelatedIoC
	(*IoCFilter)(nil),             // 6: ioc.v1.IoCFilter
	(*IoCStatistics)(nil),         // 7: ioc.v1.IoCStatistics
	nil,                           // 8: ioc.v1.EnrichmentSummary.SourceDetailsEntry
	nil,                           // 9: ioc.v1.IoCStatistics.ByTypeEntry
	nil,                           // 10: ioc.v1.IoCStatistics.BySeverityEntry
	nil,                           // 11: ioc.v1.IoCStatistics.ByVerdictEntry
	(IoCType)(0),                  // 12: ioc.v1.IoCType
	(Verdict)(0),                  // 13: ioc.v1.Verdict
	(Severity)(0),                 // 14: ioc.v1.Severity
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
	(ThreatCategory)(0),           // 16: ioc.v1.ThreatCategory
	(KillChainPhase)(0),           // 17: ioc.v1.KillChainPhase
	(*structpb.Struct)(nil),       // 18: google.protobuf.Struct
	(RelationType)(0),             // 19: ioc.v1.RelationType
}
var file_ioc_v1_ioc_proto_depIdxs = []int32{
	12, // 0: ioc.v1.IoC.type:type_name -> ioc.v1.IoCType
	13, // 1: ioc.v1.IoC.verdict:type_name -> ioc.v1.Verdict
	14, // 2: ioc.v1.IoC.severity:type_name -> ioc.v1.Severity
	15, // 3: ioc.v1.IoC.created_at:type_name -> google.protobuf.Timestamp
	15, // 4: ioc.v1.IoC.updated_at:type_name -> google.protobuf.Timestamp
	15, // 5: ioc.v1.IoC.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 6: ioc.v1.IoC.threat_context:type_name -> ioc.v1.ThreatContext
	2,  // 7: ioc.v1.IoC.enrichment_summary:type_name -> ioc.v1.EnrichmentSummary
	4,  // 8: ioc.v1.IoC.metadata:type_name -> ioc.v1.IoCMetadata
	16, // 9: ioc.v1.ThreatContext.categories:type_name -> ioc.v1.ThreatCategory
	17, // 10: ioc.v1.ThreatContext.kill_chain_phase:type_name -> ioc.v1.KillChainPhase
	15, // 11: ioc.v1.EnrichmentSummary.last_enriched:type_name -> google.protobuf.Timestamp
	8,  // 12: ioc.v1.EnrichmentSummary.source_details:type_name -> ioc.v1.EnrichmentSummary.SourceDetailsEntry
	15, // 13: ioc.v1.SourceResult.checked_at:type_name -> google.protobuf.Timestamp
	18, // 14: ioc.v1.SourceResult.raw_data:type_name -> google.protobuf.Struct
	18, // 15: ioc.v1.IoCMetadata.custom_fields:type_name -> google.protobuf.Struct
	12, // 16: ioc.v1.RelatedIoC.type:type_name -> ioc.v1.IoCType
	19, // 17: ioc.v1.RelatedIoC.relation_type:type_name -> ioc.v1.RelationType
	12, // 18: ioc.v1.IoCFilter.type:type_name -> ioc.v1.IoCType
	14, // 19: ioc.v1.IoCFilter.severity:type_name -> ioc.v1.Severity
	13, // 20: ioc.v1.IoCFilter.verdict:type_name -> ioc.v1.Verdict
	17, // 21: ioc.v1.IoCFilter.kill_chain_phase:type_name -> ioc.v1.KillChainPhase
	15, // 22: ioc.v1.IoCFilter.start_date:type_name -> google.protobuf.Timestamp
	15, // 23: ioc.v1.IoCFilter.end_date:type_name -> google.protobuf.Timestamp
	9,  // 24: ioc.v1.IoCStatistics.by_type:type_name -> ioc.v1.IoCStatistics.ByTypeEntry
	10, // 25: ioc.v1.IoCStatistics.by_severity:type_name -> ioc.v1.IoCStatistics.BySeverityEntry
	11, // 26: ioc.v1.IoCStatistics.by_verdict:type_name -> ioc.v1.IoCStatistics.ByVerdictEntry
	15, // 27: ioc.v1.IoCStatistics.generated_at:type_name -> google.protobuf.Timestamp
	3,  // 28: ioc.v1.EnrichmentSummary.SourceDetailsEntry.value:type_name -> ioc.v1.SourceResult
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_ioc_v1_ioc_proto_init() }
func file_ioc_v1_ioc_proto_init() {
	if File_ioc_v1_ioc_proto != nil {
		return
	}
	file_ioc_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ioc_v1_ioc_proto_rawDesc), len(file_ioc_v1_ioc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ioc_v1_ioc_proto_goTypes,
		DependencyIndexes: file_ioc_v1_ioc_proto_depIdxs,
		MessageInfos:      file_ioc_v1_ioc_proto_msgTypes,
	}.Build()
	File_ioc_v1_ioc_proto = out.File
	file_ioc_v1_ioc_proto_goTypes = nil
	file_ioc_v1_ioc_proto_depIdxs = nil
}
