// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: ioc/v1/ioc_service.proto

package iocv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IoCService_BatchUpsertIoCs_FullMethodName         = "/ioc.v1.IoCService/BatchUpsertIoCs"
	IoCService_GetIoC_FullMethodName                  = "/ioc.v1.IoCService/GetIoC"
	IoCService_GetByValue_FullMethodName              = "/ioc.v1.IoCService/GetByValue"
	IoCService_DeleteIoCs_FullMethodName              = "/ioc.v1.IoCService/DeleteIoCs"
	IoCService_FindIoCs_FullMethodName                = "/ioc.v1.IoCService/FindIoCs"
	IoCService_GetIoCStatistics_FullMethodName        = "/ioc.v1.IoCService/GetIoCStatistics"
	IoCService_IncrementDetectionCount_FullMethodName = "/ioc.v1.IoCService/IncrementDetectionCount"
	IoCService_GetExpired_FullMethodName              = "/ioc.v1.IoCService/GetExpired"
	IoCService_EnrichIoC_FullMethodName               = "/ioc.v1.IoCService/EnrichIoC"
	IoCService_GetEnrichmentStatus_FullMethodName     = "/ioc.v1.IoCService/GetEnrichmentStatus"
	IoCService_GetRelatedIoCs_FullMethodName          = "/ioc.v1.IoCService/GetRelatedIoCs"
)

// IoCServiceClient is the client API for IoCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IoCServiceClient interface {
	BatchUpsertIoCs(ctx context.Context, in *BatchUpsertIoCsRequest, opts ...grpc.CallOption) (*BatchUpsertIoCsResponse, error)
	GetIoC(ctx context.Context, in *GetIoCRequest, opts ...grpc.CallOption) (*GetIoCResponse, error)
	GetByValue(ctx context.Context, in *GetByValueRequest, opts ...grpc.CallOption) (*GetByValueResponse, error)
	DeleteIoCs(ctx context.Context, in *DeleteIoCsRequest, opts ...grpc.CallOption) (*DeleteIoCsResponse, error)
	FindIoCs(ctx context.Context, in *FindIoCsRequest, opts ...grpc.CallOption) (*FindIoCsResponse, error)
	GetIoCStatistics(ctx context.Context, in *GetIoCStatisticsRequest, opts ...grpc.CallOption) (*GetIoCStatisticsResponse, error)
	IncrementDetectionCount(ctx context.Context, in *IncrementDetectionCountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetExpired(ctx context.Context, in *GetExpiredRequest, opts ...grpc.CallOption) (*GetExpiredResponse, error)
	EnrichIoC(ctx context.Context, in *EnrichIoCRequest, opts ...grpc.CallOption) (*EnrichIoCResponse, error)
	GetEnrichmentStatus(ctx context.Context, in *GetEnrichmentStatusRequest, opts ...grpc.CallOption) (*GetEnrichmentStatusResponse, error)
	GetRelatedIoCs(ctx context.Context, in *GetRelatedIoCsRequest, opts ...grpc.CallOption) (*GetRelatedIoCsResponse, error)
}

type ioCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIoCServiceClient(cc grpc.ClientConnInterface) IoCServiceClient {
	return &ioCServiceClient{cc}
}

func (c *ioCServiceClient) BatchUpsertIoCs(ctx context.Context, in *BatchUpsertIoCsRequest, opts ...grpc.CallOption) (*BatchUpsertIoCsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUpsertIoCsResponse)
	err := c.cc.Invoke(ctx, IoCService_BatchUpsertIoCs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioCServiceClient) GetIoC(ctx context.Context, in *GetIoCRequest, opts ...grpc.CallOption) (*GetIoCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIoCResponse)
	err := c.cc.Invoke(ctx, IoCService_GetIoC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioCServiceClient) GetByValue(ctx context.Context, in *GetByValueRequest, opts ...grpc.CallOption) (*GetByValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetByValueResponse)
	err := c.cc.Invoke(ctx, IoCService_GetByValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioCServiceClient) DeleteIoCs(ctx context.Context, in *DeleteIoCsRequest, opts ...grpc.CallOption) (*DeleteIoCsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteIoCsResponse)
	err := c.cc.Invoke(ctx, IoCService_DeleteIoCs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioCServiceClient) FindIoCs(ctx context.Context, in *FindIoCsRequest, opts ...grpc.CallOption) (*FindIoCsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindIoCsResponse)
	err := c.cc.Invoke(ctx, IoCService_FindIoCs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioCServiceClient) GetIoCStatistics(ctx context.Context, in *GetIoCStatisticsRequest, opts ...grpc.CallOption) (*GetIoCStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIoCStatisticsResponse)
	err := c.cc.Invoke(ctx, IoCService_GetIoCStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioCServiceClient) IncrementDetectionCount(ctx context.Context, in *IncrementDetectionCountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IoCService_IncrementDetectionCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioCServiceClient) GetExpired(ctx context.Context, in *GetExpiredRequest, opts ...grpc.CallOption) (*GetExpiredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExpiredResponse)
	err := c.cc.Invoke(ctx, IoCService_GetExpired_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioCServiceClient) EnrichIoC(ctx context.Context, in *EnrichIoCRequest, opts ...grpc.CallOption) (*EnrichIoCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichIoCResponse)
	err := c.cc.Invoke(ctx, IoCService_EnrichIoC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioCServiceClient) GetEnrichmentStatus(ctx context.Context, in *GetEnrichmentStatusRequest, opts ...grpc.CallOption) (*GetEnrichmentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEnrichmentStatusResponse)
	err := c.cc.Invoke(ctx, IoCService_GetEnrichmentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ioCServiceClient) GetRelatedIoCs(ctx context.Context, in *GetRelatedIoCsRequest, opts ...grpc.CallOption) (*GetRelatedIoCsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRelatedIoCsResponse)
	err := c.cc.Invoke(ctx, IoCService_GetRelatedIoCs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IoCServiceServer is the server API for IoCService service.
// All implementations must embed UnimplementedIoCServiceServer
// for forward compatibility.
type IoCServiceServer interface {
	BatchUpsertIoCs(context.Context, *BatchUpsertIoCsRequest) (*BatchUpsertIoCsResponse, error)
	GetIoC(context.Context, *GetIoCRequest) (*GetIoCResponse, error)
	GetByValue(context.Context, *GetByValueRequest) (*GetByValueResponse, error)
	DeleteIoCs(context.Context, *DeleteIoCsRequest) (*DeleteIoCsResponse, error)
	FindIoCs(context.Context, *FindIoCsRequest) (*FindIoCsResponse, error)
	GetIoCStatistics(context.Context, *GetIoCStatisticsRequest) (*GetIoCStatisticsResponse, error)
	IncrementDetectionCount(context.Context, *IncrementDetectionCountRequest) (*emptypb.Empty, error)
	GetExpired(context.Context, *GetExpiredRequest) (*GetExpiredResponse, error)
	EnrichIoC(context.Context, *EnrichIoCRequest) (*EnrichIoCResponse, error)
	GetEnrichmentStatus(context.Context, *GetEnrichmentStatusRequest) (*GetEnrichmentStatusResponse, error)
	GetRelatedIoCs(context.Context, *GetRelatedIoCsRequest) (*GetRelatedIoCsResponse, error)
	mustEmbedUnimplementedIoCServiceServer()
}

// UnimplementedIoCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIoCServiceServer struct{}

func (UnimplementedIoCServiceServer) BatchUpsertIoCs(context.Context, *BatchUpsertIoCsRequest) (*BatchUpsertIoCsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchUpsertIoCs not implemented")
}
func (UnimplementedIoCServiceServer) GetIoC(context.Context, *GetIoCRequest) (*GetIoCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIoC not implemented")
}
func (UnimplementedIoCServiceServer) GetByValue(context.Context, *GetByValueRequest) (*GetByValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByValue not implemented")
}
func (UnimplementedIoCServiceServer) DeleteIoCs(context.Context, *DeleteIoCsRequest) (*DeleteIoCsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteIoCs not implemented")
}
func (UnimplementedIoCServiceServer) FindIoCs(context.Context, *FindIoCsRequest) (*FindIoCsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindIoCs not implemented")
}
func (UnimplementedIoCServiceServer) GetIoCStatistics(context.Context, *GetIoCStatisticsRequest) (*GetIoCStatisticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIoCStatistics not implemented")
}
func (UnimplementedIoCServiceServer) IncrementDetectionCount(context.Context, *IncrementDetectionCountRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrementDetectionCount not implemented")
}
func (UnimplementedIoCServiceServer) GetExpired(context.Context, *GetExpiredRequest) (*GetExpiredResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExpired not implemented")
}
func (UnimplementedIoCServiceServer) EnrichIoC(context.Context, *EnrichIoCRequest) (*EnrichIoCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrichIoC not implemented")
}
func (UnimplementedIoCServiceServer) GetEnrichmentStatus(context.Context, *GetEnrichmentStatusRequest) (*GetEnrichmentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEnrichmentStatus not implemented")
}
func (UnimplementedIoCServiceServer) GetRelatedIoCs(context.Context, *GetRelatedIoCsRequest) (*GetRelatedIoCsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRelatedIoCs not implemented")
}
func (UnimplementedIoCServiceServer) mustEmbedUnimplementedIoCServiceServer() {}
func (UnimplementedIoCServiceServer) testEmbeddedByValue()                    {}

// UnsafeIoCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IoCServiceServer will
// result in compilation errors.
type UnsafeIoCServiceServer interface {
	mustEmbedUnimplementedIoCServiceServer()
}

func RegisterIoCServiceServer(s grpc.ServiceRegistrar, srv IoCServiceServer) {
	// If the following call panics, it indicates UnimplementedIoCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IoCService_ServiceDesc, srv)
}

func _IoCService_BatchUpsertIoCs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpsertIoCsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoCServiceServer).BatchUpsertIoCs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoCService_BatchUpsertIoCs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoCServiceServer).BatchUpsertIoCs(ctx, req.(*BatchUpsertIoCsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoCService_GetIoC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIoCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoCServiceServer).GetIoC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoCService_GetIoC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoCServiceServer).GetIoC(ctx, req.(*GetIoCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoCService_GetByValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoCServiceServer).GetByValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoCService_GetByValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoCServiceServer).GetByValue(ctx, req.(*GetByValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoCService_DeleteIoCs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIoCsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoCServiceServer).DeleteIoCs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoCService_DeleteIoCs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoCServiceServer).DeleteIoCs(ctx, req.(*DeleteIoCsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoCService_FindIoCs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindIoCsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoCServiceServer).FindIoCs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoCService_FindIoCs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoCServiceServer).FindIoCs(ctx, req.(*FindIoCsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoCService_GetIoCStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIoCStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoCServiceServer).GetIoCStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoCService_GetIoCStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoCServiceServer).GetIoCStatistics(ctx, req.(*GetIoCStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoCService_IncrementDetectionCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementDetectionCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoCServiceServer).IncrementDetectionCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoCService_IncrementDetectionCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoCServiceServer).IncrementDetectionCount(ctx, req.(*IncrementDetectionCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoCService_GetExpired_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExpiredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoCServiceServer).GetExpired(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoCService_GetExpired_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoCServiceServer).GetExpired(ctx, req.(*GetExpiredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoCService_EnrichIoC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichIoCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoCServiceServer).EnrichIoC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoCService_EnrichIoC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoCServiceServer).EnrichIoC(ctx, req.(*EnrichIoCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoCService_GetEnrichmentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnrichmentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoCServiceServer).GetEnrichmentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoCService_GetEnrichmentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoCServiceServer).GetEnrichmentStatus(ctx, req.(*GetEnrichmentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IoCService_GetRelatedIoCs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRelatedIoCsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IoCServiceServer).GetRelatedIoCs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IoCService_GetRelatedIoCs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IoCServiceServer).GetRelatedIoCs(ctx, req.(*GetRelatedIoCsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IoCService_ServiceDesc is the grpc.ServiceDesc for IoCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IoCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ioc.v1.IoCService",
	HandlerType: (*IoCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchUpsertIoCs",
			Handler:    _IoCService_BatchUpsertIoCs_Handler,
		},
		{
			MethodName: "GetIoC",
			Handler:    _IoCService_GetIoC_Handler,
		},
		{
			MethodName: "GetByValue",
			Handler:    _IoCService_GetByValue_Handler,
		},
		{
			MethodName: "DeleteIoCs",
			Handler:    _IoCService_DeleteIoCs_Handler,
		},
		{
			MethodName: "FindIoCs",
			Handler:    _IoCService_FindIoCs_Handler,
		},
		{
			MethodName: "GetIoCStatistics",
			Handler:    _IoCService_GetIoCStatistics_Handler,
		},
		{
			MethodName: "IncrementDetectionCount",
			Handler:    _IoCService_IncrementDetectionCount_Handler,
		},
		{
			MethodName: "GetExpired",
			Handler:    _IoCService_GetExpired_Handler,
		},
		{
			MethodName: "EnrichIoC",
			Handler:    _IoCService_EnrichIoC_Handler,
		},
		{
			MethodName: "GetEnrichmentStatus",
			Handler:    _IoCService_GetEnrichmentStatus_Handler,
		},
		{
			MethodName: "GetRelatedIoCs",
			Handler:    _IoCService_GetRelatedIoCs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ioc/v1/ioc_service.proto",
}
