// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ioc/v1/threat_service.proto

package iocv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchUpsertThreatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threats       []*Threat              `protobuf:"bytes,1,rep,name=threats,proto3" json:"threats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpsertThreatsRequest) Reset() {
	*x = BatchUpsertThreatsRequest{}
	mi := &file_ioc_v1_threat_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpsertThreatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpsertThreatsRequest) ProtoMessage() {}

func (x *BatchUpsertThreatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpsertThreatsRequest.ProtoReflect.Descriptor instead.
func (*BatchUpsertThreatsRequest) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_service_proto_rawDescGZIP(), []int{0}
}

func (x *BatchUpsertThreatsRequest) GetThreats() []*Threat {
	if x != nil {
		return x.Threats
	}
	return nil
}

type BatchUpsertThreatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpsertedIds   []string               `protobuf:"bytes,1,rep,name=upserted_ids,json=upsertedIds,proto3" json:"upserted_ids,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpsertThreatsResponse) Reset() {
	*x = BatchUpsertThreatsResponse{}
	mi := &file_ioc_v1_threat_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpsertThreatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpsertThreatsResponse) ProtoMessage() {}

func (x *BatchUpsertThreatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpsertThreatsResponse.ProtoReflect.Descriptor instead.
func (*BatchUpsertThreatsResponse) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_service_proto_rawDescGZIP(), []int{1}
}

func (x *BatchUpsertThreatsResponse) GetUpsertedIds() []string {
	if x != nil {
		return x.UpsertedIds
	}
	return nil
}

func (x *BatchUpsertThreatsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetThreatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetThreatRequest_Id
	//	*GetThreatRequest_Name
	Identifier        isGetThreatRequest_Identifier `protobuf_oneof:"identifier"`
	IncludeIndicators bool                          `protobuf:"varint,3,opt,name=include_indicators,json=includeIndicators,proto3" json:"include_indicators,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetThreatRequest) Reset() {
	*x = GetThreatRequest{}
	mi := &file_ioc_v1_threat_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreatRequest) ProtoMessage() {}

func (x *GetThreatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreatRequest.ProtoReflect.Descriptor instead.
func (*GetThreatRequest) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetThreatRequest) GetIdentifier() isGetThreatRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetThreatRequest) GetId() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetThreatRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *GetThreatRequest) GetName() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetThreatRequest_Name); ok {
			return x.Name
		}
	}
	return ""
}

func (x *GetThreatRequest) GetIncludeIndicators() bool {
	if x != nil {
		return x.IncludeIndicators
	}
	return false
}

type isGetThreatRequest_Identifier interface {
	isGetThreatRequest_Identifier()
}

type GetThreatRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type GetThreatRequest_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

func (*GetThreatRequest_Id) isGetThreatRequest_Identifier() {}

func (*GetThreatRequest_Name) isGetThreatRequest_Identifier() {}

type GetThreatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threat        *Threat                `protobuf:"bytes,1,opt,name=threat,proto3" json:"threat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreatResponse) Reset() {
	*x = GetThreatResponse{}
	mi := &file_ioc_v1_threat_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreatResponse) ProtoMessage() {}

func (x *GetThreatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreatResponse.ProtoReflect.Descriptor instead.
func (*GetThreatResponse) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetThreatResponse) GetThreat() *Threat {
	if x != nil {
		return x.Threat
	}
	return nil
}

type DeleteThreatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteThreatsRequest) Reset() {
	*x = DeleteThreatsRequest{}
	mi := &file_ioc_v1_threat_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteThreatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteThreatsRequest) ProtoMessage() {}

func (x *DeleteThreatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteThreatsRequest.ProtoReflect.Descriptor instead.
func (*DeleteThreatsRequest) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteThreatsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *DeleteThreatsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeleteThreatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteThreatsResponse) Reset() {
	*x = DeleteThreatsResponse{}
	mi := &file_ioc_v1_threat_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteThreatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteThreatsResponse) ProtoMessage() {}

func (x *DeleteThreatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteThreatsResponse.ProtoReflect.Descriptor instead.
func (*DeleteThreatsResponse) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteThreatsResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

func (x *DeleteThreatsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FindThreatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Filter        *ThreatFilter          `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	SortOptions   *SortOptions           `protobuf:"bytes,3,opt,name=sort_options,json=sortOptions,proto3" json:"sort_options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindThreatsRequest) Reset() {
	*x = FindThreatsRequest{}
	mi := &file_ioc_v1_threat_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindThreatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindThreatsRequest) ProtoMessage() {}

func (x *FindThreatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindThreatsRequest.ProtoReflect.Descriptor instead.
func (*FindThreatsRequest) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_service_proto_rawDescGZIP(), []int{6}
}

func (x *FindThreatsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *FindThreatsRequest) GetFilter() *ThreatFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *FindThreatsRequest) GetSortOptions() *SortOptions {
	if x != nil {
		return x.SortOptions
	}
	return nil
}

type FindThreatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threats       []*Threat              `protobuf:"bytes,1,rep,name=threats,proto3" json:"threats,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindThreatsResponse) Reset() {
	*x = FindThreatsResponse{}
	mi := &file_ioc_v1_threat_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindThreatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindThreatsResponse) ProtoMessage() {}

func (x *FindThreatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindThreatsResponse.ProtoReflect.Descriptor instead.
func (*FindThreatsResponse) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_service_proto_rawDescGZIP(), []int{7}
}

func (x *FindThreatsResponse) GetThreats() []*Threat {
	if x != nil {
		return x.Threats
	}
	return nil
}

func (x *FindThreatsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetThreatStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *ThreatFilter          `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreatStatisticsRequest) Reset() {
	*x = GetThreatStatisticsRequest{}
	mi := &file_ioc_v1_threat_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreatStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreatStatisticsRequest) ProtoMessage() {}

func (x *GetThreatStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreatStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetThreatStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetThreatStatisticsRequest) GetFilter() *ThreatFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type GetThreatStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statistics    *ThreatStatistics      `protobuf:"bytes,1,opt,name=statistics,proto3" json:"statistics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreatStatisticsResponse) Reset() {
	*x = GetThreatStatisticsResponse{}
	mi := &file_ioc_v1_threat_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreatStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreatStatisticsResponse) ProtoMessage() {}

func (x *GetThreatStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreatStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetThreatStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetThreatStatisticsResponse) GetStatistics() *ThreatStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

type GetThreatsByIoCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IocId         string                 `protobuf:"bytes,1,opt,name=ioc_id,json=iocId,proto3" json:"ioc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreatsByIoCRequest) Reset() {
	*x = GetThreatsByIoCRequest{}
	mi := &file_ioc_v1_threat_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreatsByIoCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreatsByIoCRequest) ProtoMessage() {}

func (x *GetThreatsByIoCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreatsByIoCRequest.ProtoReflect.Descriptor instead.
func (*GetThreatsByIoCRequest) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetThreatsByIoCRequest) GetIocId() string {
	if x != nil {
		return x.IocId
	}
	return ""
}

type GetThreatsByIoCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threats       []*Threat              `protobuf:"bytes,1,rep,name=threats,proto3" json:"threats,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreatsByIoCResponse) Reset() {
	*x = GetThreatsByIoCResponse{}
	mi := &file_ioc_v1_threat_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreatsByIoCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreatsByIoCResponse) ProtoMessage() {}

func (x *GetThreatsByIoCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreatsByIoCResponse.ProtoReflect.Descriptor instead.
func (*GetThreatsByIoCResponse) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetThreatsByIoCResponse) GetThreats() []*Threat {
	if x != nil {
		return x.Threats
	}
	return nil
}

func (x *GetThreatsByIoCResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetThreatsByTTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ttps          []string               `protobuf:"bytes,1,rep,name=ttps,proto3" json:"ttps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreatsByTTPRequest) Reset() {
	*x = GetThreatsByTTPRequest{}
	mi := &file_ioc_v1_threat_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreatsByTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreatsByTTPRequest) ProtoMessage() {}

func (x *GetThreatsByTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreatsByTTPRequest.ProtoReflect.Descriptor instead.
func (*GetThreatsByTTPRequest) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetThreatsByTTPRequest) GetTtps() []string {
	if x != nil {
		return x.Ttps
	}
	return nil
}

type GetThreatsByTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threats       []*Threat              `protobuf:"bytes,1,rep,name=threats,proto3" json:"threats,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreatsByTTPResponse) Reset() {
	*x = GetThreatsByTTPResponse{}
	mi := &file_ioc_v1_threat_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreatsByTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreatsByTTPResponse) ProtoMessage() {}

func (x *GetThreatsByTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreatsByTTPResponse.ProtoReflect.Descriptor instead.
func (*GetThreatsByTTPResponse) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetThreatsByTTPResponse) GetThreats() []*Threat {
	if x != nil {
		return x.Threats
	}
	return nil
}

func (x *GetThreatsByTTPResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CorrelateThreatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IocId         string                 `protobuf:"bytes,1,opt,name=ioc_id,json=iocId,proto3" json:"ioc_id,omitempty"`
	MinConfidence float32                `protobuf:"fixed32,2,opt,name=min_confidence,json=minConfidence,proto3" json:"min_confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorrelateThreatRequest) Reset() {
	*x = CorrelateThreatRequest{}
	mi := &file_ioc_v1_threat_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorrelateThreatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrelateThreatRequest) ProtoMessage() {}

func (x *CorrelateThreatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrelateThreatRequest.ProtoReflect.Descriptor instead.
func (*CorrelateThreatRequest) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_service_proto_rawDescGZIP(), []int{14}
}

func (x *CorrelateThreatRequest) GetIocId() string {
	if x != nil {
		return x.IocId
	}
	return ""
}

func (x *CorrelateThreatRequest) GetMinConfidence() float32 {
	if x != nil {
		return x.MinConfidence
	}
	return 0
}

type CorrelateThreatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Correlations  []*ThreatCorrelation   `protobuf:"bytes,1,rep,name=correlations,proto3" json:"correlations,omitempty"`
	TotalFound    int32                  `protobuf:"varint,2,opt,name=total_found,json=totalFound,proto3" json:"total_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorrelateThreatResponse) Reset() {
	*x = CorrelateThreatResponse{}
	mi := &file_ioc_v1_threat_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorrelateThreatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrelateThreatResponse) ProtoMessage() {}

func (x *CorrelateThreatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrelateThreatResponse.ProtoReflect.Descriptor instead.
func (*CorrelateThreatResponse) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_service_proto_rawDescGZIP(), []int{15}
}

func (x *CorrelateThreatResponse) GetCorrelations() []*ThreatCorrelation {
	if x != nil {
		return x.Correlations
	}
	return nil
}

func (x *CorrelateThreatResponse) GetTotalFound() int32 {
	if x != nil {
		return x.TotalFound
	}
	return 0
}

type LinkIoCsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreatId      string                 `protobuf:"bytes,1,opt,name=threat_id,json=threatId,proto3" json:"threat_id,omitempty"`
	IocIds        []string               `protobuf:"bytes,2,rep,name=ioc_ids,json=iocIds,proto3" json:"ioc_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkIoCsRequest) Reset() {
	*x = LinkIoCsRequest{}
	mi := &file_ioc_v1_threat_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkIoCsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkIoCsRequest) ProtoMessage() {}

func (x *LinkIoCsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkIoCsRequest.ProtoReflect.Descriptor instead.
func (*LinkIoCsRequest) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_service_proto_rawDescGZIP(), []int{16}
}

func (x *LinkIoCsRequest) GetThreatId() string {
	if x != nil {
		return x.ThreatId
	}
	return ""
}

func (x *LinkIoCsRequest) GetIocIds() []string {
	if x != nil {
		return x.IocIds
	}
	return nil
}

type LinkIoCsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkIoCsResponse) Reset() {
	*x = LinkIoCsResponse{}
	mi := &file_ioc_v1_threat_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkIoCsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkIoCsResponse) ProtoMessage() {}

func (x *LinkIoCsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkIoCsResponse.ProtoReflect.Descriptor instead.
func (*LinkIoCsResponse) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_service_proto_rawDescGZIP(), []int{17}
}

func (x *LinkIoCsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnlinkIoCsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreatId      string                 `protobuf:"bytes,1,opt,name=threat_id,json=threatId,proto3" json:"threat_id,omitempty"`
	IocIds        []string               `protobuf:"bytes,2,rep,name=ioc_ids,json=iocIds,proto3" json:"ioc_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkIoCsRequest) Reset() {
	*x = UnlinkIoCsRequest{}
	mi := &file_ioc_v1_threat_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkIoCsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkIoCsRequest) ProtoMessage() {}

func (x *UnlinkIoCsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkIoCsRequest.ProtoReflect.Descriptor instead.
func (*UnlinkIoCsRequest) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_service_proto_rawDescGZIP(), []int{18}
}

func (x *UnlinkIoCsRequest) GetThreatId() string {
	if x != nil {
		return x.ThreatId
	}
	return ""
}

func (x *UnlinkIoCsRequest) GetIocIds() []string {
	if x != nil {
		return x.IocIds
	}
	return nil
}

type UnlinkIoCsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkIoCsResponse) Reset() {
	*x = UnlinkIoCsResponse{}
	mi := &file_ioc_v1_threat_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkIoCsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkIoCsResponse) ProtoMessage() {}

func (x *UnlinkIoCsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkIoCsResponse.ProtoReflect.Descriptor instead.
func (*UnlinkIoCsResponse) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_service_proto_rawDescGZIP(), []int{19}
}

func (x *UnlinkIoCsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ioc_v1_threat_service_proto protoreflect.FileDescriptor

const file_ioc_v1_threat_service_proto_rawDesc = "" +
	"\n" +
	"\x1bioc/v1/threat_service.proto\x12\x06ioc.v1\x1a\x13ioc/v1/threat.proto\x1a\x13ioc/v1/common.proto\"E\n" +
	"\x19BatchUpsertThreatsRequest\x12(\n" +
	"\athreats\x18\x01 \x03(\v2\x0e.ioc.v1.ThreatR\athreats\"Y\n" +
	"\x1aBatchUpsertThreatsResponse\x12!\n" +
	"\fupserted_ids\x18\x01 \x03(\tR\vupsertedIds\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"w\n" +
	"\x10GetThreatRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x14\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x12-\n" +
	"\x12include_indicators\x18\x03 \x01(\bR\x11includeIndicatorsB\f\n" +
	"\n" +
	"identifier\";\n" +
	"\x11GetThreatResponse\x12&\n" +
	"\x06threat\x18\x01 \x01(\v2\x0e.ioc.v1.ThreatR\x06threat\"@\n" +
	"\x14DeleteThreatsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"V\n" +
	"\x15DeleteThreatsResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xae\x01\n" +
	"\x12FindThreatsRequest\x122\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x12.ioc.v1.PaginationR\n" +
	"pagination\x12,\n" +
	"\x06filter\x18\x02 \x01(\v2\x14.ioc.v1.ThreatFilterR\x06filter\x126\n" +
	"\fsort_options\x18\x03 \x01(\v2\x13.ioc.v1.SortOptionsR\vsortOptions\"s\n" +
	"\x13FindThreatsResponse\x12(\n" +
	"\athreats\x18\x01 \x03(\v2\x0e.ioc.v1.ThreatR\athreats\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.ioc.v1.PaginationR\n" +
	"pagination\"J\n" +
	"\x1aGetThreatStatisticsRequest\x12,\n" +
	"\x06filter\x18\x01 \x01(\v2\x14.ioc.v1.ThreatFilterR\x06filter\"W\n" +
	"\x1bGetThreatStatisticsResponse\x128\n" +
	"\n" +
	"statistics\x18\x01 \x01(\v2\x18.ioc.v1.ThreatStatisticsR\n" +
	"statistics\"/\n" +
	"\x16GetThreatsByIoCRequest\x12\x15\n" +
	"\x06ioc_id\x18\x01 \x01(\tR\x05iocId\"d\n" +
	"\x17GetThreatsByIoCResponse\x12(\n" +
	"\athreats\x18\x01 \x03(\v2\x0e.ioc.v1.ThreatR\athreats\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\",\n" +
	"\x16GetThreatsByTTPRequest\x12\x12\n" +
	"\x04ttps\x18\x01 \x03(\tR\x04ttps\"d\n" +
	"\x17GetThreatsByTTPResponse\x12(\n" +
	"\athreats\x18\x01 \x03(\v2\x0e.ioc.v1.ThreatR\athreats\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"V\n" +
	"\x16CorrelateThreatRequest\x12\x15\n" +
	"\x06ioc_id\x18\x01 \x01(\tR\x05iocId\x12%\n" +
	"\x0emin_confidence\x18\x02 \x01(\x02R\rminConfidence\"y\n" +
	"\x17CorrelateThreatResponse\x12=\n" +
	"\fcorrelations\x18\x01 \x03(\v2\x19.ioc.v1.ThreatCorrelationR\fcorrelations\x12\x1f\n" +
	"\vtotal_found\x18\x02 \x01(\x05R\n" +
	"totalFound\"G\n" +
	"\x0fLinkIoCsRequest\x12\x1b\n" +
	"\tthreat_id\x18\x01 \x01(\tR\bthreatId\x12\x17\n" +
	"\aioc_ids\x18\x02 \x03(\tR\x06iocIds\",\n" +
	"\x10LinkIoCsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"I\n" +
	"\x11UnlinkIoCsRequest\x12\x1b\n" +
	"\tthreat_id\x18\x01 \x01(\tR\bthreatId\x12\x17\n" +
	"\aioc_ids\x18\x02 \x03(\tR\x06iocIds\".\n" +
	"\x12UnlinkIoCsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa4\x06\n" +
	"\rThreatService\x12[\n" +
	"\x12BatchUpsertThreats\x12!.ioc.v1.BatchUpsertThreatsRequest\x1a\".ioc.v1.BatchUpsertThreatsResponse\x12@\n" +
	"\tGetThreat\x12\x18.ioc.v1.GetThreatRequest\x1a\x19.ioc.v1.GetThreatResponse\x12L\n" +
	"\rDeleteThreats\x12\x1c.ioc.v1.DeleteThreatsRequest\x1a\x1d.ioc.v1.DeleteThreatsResponse\x12F\n" +
	"\vFindThreats\x12\x1a.ioc.v1.FindThreatsRequest\x1a\x1b.ioc.v1.FindThreatsResponse\x12^\n" +
	"\x13GetThreatStatistics\x12\".ioc.v1.GetThreatStatisticsRequest\x1a#.ioc.v1.GetThreatStatisticsResponse\x12R\n" +
	"\x0fGetThreatsByIoC\x12\x1e.ioc.v1.GetThreatsByIoCRequest\x1a\x1f.ioc.v1.GetThreatsByIoCResponse\x12R\n" +
	"\x0fGetThreatsByTTP\x12\x1e.ioc.v1.GetThreatsByTTPRequest\x1a\x1f.ioc.v1.GetThreatsByTTPResponse\x12R\n" +
	"\x0fCorrelateThreat\x12\x1e.ioc.v1.CorrelateThreatRequest\x1a\x1f.ioc.v1.CorrelateThreatResponse\x12=\n" +
	"\bLinkIoCs\x12\x17.ioc.v1.LinkIoCsRequest\x1a\x18.ioc.v1.LinkIoCsResponse\x12C\n" +
	"\n" +
	"UnlinkIoCs\x12\x19.ioc.v1.UnlinkIoCsRequest\x1a\x1a.ioc.v1.UnlinkIoCsResponseBBZ@github.com/DgHnG36/ioc_enrichment_service/shared/go/ioc/v1;iocv1b\x06proto3"

var (
	file_ioc_v1_threat_service_proto_rawDescOnce sync.Once
	file_ioc_v1_threat_service_proto_rawDescData []byte
)

func file_ioc_v1_threat_service_proto_rawDescGZIP() []byte {
	file_ioc_v1_threat_service_proto_rawDescOnce.Do(func() {
		file_ioc_v1_threat_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ioc_v1_threat_service_proto_rawDesc), len(file_ioc_v1_threat_service_proto_rawDesc)))
	})
	return file_ioc_v1_threat_service_proto_rawDescData
}

var file_ioc_v1_threat_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_ioc_v1_threat_service_proto_goTypes = []any{
	(*BatchUpsertThreatsRequest)(nil),   // 0: ioc.v1.BatchUpsertThreatsRequest
	(*BatchUpsertThreatsResponse)(nil),  // 1: ioc.v1.BatchUpsertThreatsResponse
	(*GetThreatRequest)(nil),            // 2: ioc.v1.GetThreatRequest
	(*GetThreatResponse)(nil),           // 3: ioc.v1.GetThreatResponse
	(*DeleteThreatsRequest)(nil),        // 4: ioc.v1.DeleteThreatsRequest
	(*DeleteThreatsResponse)(nil),       // 5: ioc.v1.DeleteThreatsResponse
	(*FindThreatsRequest)(nil),          // 6: ioc.v1.FindThreatsRequest
	(*FindThreatsResponse)(nil),         // 7: ioc.v1.FindThreatsResponse
	(*GetThreatStatisticsRequest)(nil),  // 8: ioc.v1.GetThreatStatisticsRequest
	(*GetThreatStatisticsResponse)(nil), // 9: ioc.v1.GetThreatStatisticsResponse
	(*GetThreatsByIoCRequest)(nil),      // 10: ioc.v1.GetThreatsByIoCRequest
	(*GetThreatsByIoCResponse)(nil),     // 11: ioc.v1.GetThreatsByIoCResponse
	(*GetThreatsByTTPRequest)(nil),      // 12: ioc.v1.GetThreatsByTTPRequest
	(*GetThreatsByTTPResponse)(nil),     // 13: ioc.v1.GetThreatsByTTPResponse
	(*CorrelateThreatRequest)(nil),      // 14: ioc.v1.CorrelateThreatRequest
	(*CorrelateThreatResponse)(nil),     // 15: ioc.v1.CorrelateThreatResponse
	(*LinkIoCsRequest)(nil),             // 16: ioc.v1.LinkIoCsRequest
	(*LinkIoCsResponse)(nil),            // 17: ioc.v1.LinkIoCsResponse
	(*UnlinkIoCsRequest)(nil),           // 18: ioc.v1.UnlinkIoCsRequest
	(*UnlinkIoCsResponse)(nil),          // 19: ioc.v1.UnlinkIoCsResponse
	(*Threat)(nil),                      // 20: ioc.v1.Threat
	(*Pagination)(nil),                  // 21: ioc.v1.Pagination
	(*ThreatFilter)(nil),                // 22: ioc.v1.ThreatFilter
	(*SortOptions)(nil),                 // 23: ioc.v1.SortOptions
	(*ThreatStatistics)(nil),            // 24: ioc.v1.ThreatStatistics
	(*ThreatCorrelation)(nil),           // 25: ioc.v1.ThreatCorrelation
}
var file_ioc_v1_threat_service_proto_depIdxs = []int32{
	20, // 0: ioc.v1.BatchUpsertThreatsRequest.threats:type_name -> ioc.v1.Threat
	20, // 1: ioc.v1.GetThreatResponse.threat:type_name -> ioc.v1.Threat
	21, // 2: ioc.v1.FindThreatsRequest.pagination:type_name -> ioc.v1.Pagination
	22, // 3: ioc.v1.FindThreatsRequest.filter:type_name -> ioc.v1.ThreatFilter
	23, // 4: ioc.v1.FindThreatsRequest.sort_options:type_name -> ioc.v1.SortOptions
	20, // 5: ioc.v1.FindThreatsResponse.threats:type_name -> ioc.v1.Threat
	21, // 6: ioc.v1.FindThreatsResponse.pagination:type_name -> ioc.v1.Pagination
	22, // 7: ioc.v1.GetThreatStatisticsRequest.filter:type_name -> ioc.v1.ThreatFilter
	24, // 8: ioc.v1.GetThreatStatisticsResponse.statistics:type_name -> ioc.v1.ThreatStatistics
	20, // 9: ioc.v1.GetThreatsByIoCResponse.threats:type_name -> ioc.v1.Threat
	20, // 10: ioc.v1.GetThreatsByTTPResponse.threats:type_name -> ioc.v1.Threat
	25, // 11: ioc.v1.CorrelateThreatResponse.correlations:type_name -> ioc.v1.ThreatCorrelation
	0,  // 12: ioc.v1.ThreatService.BatchUpsertThreats:input_type -> ioc.v1.BatchUpsertThreatsRequest
	2,  // 13: ioc.v1.ThreatService.GetThreat:input_type -> ioc.v1.GetThreatRequest
	4,  // 14: ioc.v1.ThreatService.DeleteThreats:input_type -> ioc.v1.DeleteThreatsRequest
	6,  // 15: ioc.v1.ThreatService.FindThreats:input_type -> ioc.v1.FindThreatsRequest
	8,  // 16: ioc.v1.ThreatService.GetThreatStatistics:input_type -> ioc.v1.GetThreatStatisticsRequest
	10, // 17: ioc.v1.ThreatService.GetThreatsByIoC:input_type -> ioc.v1.GetThreatsByIoCRequest
	12, // 18: ioc.v1.ThreatService.GetThreatsByTTP:input_type -> ioc.v1.GetThreatsByTTPRequest
	14, // 19: ioc.v1.ThreatService.CorrelateThreat:input_type -> ioc.v1.CorrelateThreatRequest
	16, // 20: ioc.v1.ThreatService.LinkIoCs:input_type -> ioc.v1.LinkIoCsRequest
	18, // 21: ioc.v1.ThreatService.UnlinkIoCs:input_type -> ioc.v1.UnlinkIoCsRequest
	1,  // 22: ioc.v1.ThreatService.BatchUpsertThreats:output_type -> ioc.v1.BatchUpsertThreatsResponse
	3,  // 23: ioc.v1.ThreatService.GetThreat:output_type -> ioc.v1.GetThreatResponse
	5,  // 24: ioc.v1.ThreatService.DeleteThreats:output_type -> ioc.v1.DeleteThreatsResponse
	7,  // 25: ioc.v1.ThreatService.FindThreats:output_type -> ioc.v1.FindThreatsResponse
	9,  // 26: ioc.v1.ThreatService.GetThreatStatistics:output_type -> ioc.v1.GetThreatStatisticsResponse
	11, // 27: ioc.v1.ThreatService.GetThreatsByIoC:output_type -> ioc.v1.GetThreatsByIoCResponse
	13, // 28: ioc.v1.ThreatService.GetThreatsByTTP:output_type -> ioc.v1.GetThreatsByTTPResponse
	15, // 29: ioc.v1.ThreatService.CorrelateThreat:output_type -> ioc.v1.CorrelateThreatResponse
	17, // 30: ioc.v1.ThreatService.LinkIoCs:output_type -> ioc.v1.LinkIoCsResponse
	19, // 31: ioc.v1.ThreatService.UnlinkIoCs:output_type -> ioc.v1.UnlinkIoCsResponse
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_ioc_v1_threat_service_proto_init() }
func file_ioc_v1_threat_service_proto_init() {
	if File_ioc_v1_threat_service_proto != nil {
		return
	}
	file_ioc_v1_threat_proto_init()
	file_ioc_v1_common_proto_init()
	file_ioc_v1_threat_service_proto_msgTypes[2].OneofWrappers = []any{
		(*GetThreatRequest_Id)(nil),
		(*GetThreatRequest_Name)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ioc_v1_threat_service_proto_rawDesc), len(file_ioc_v1_threat_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ioc_v1_threat_service_proto_goTypes,
		DependencyIndexes: file_ioc_v1_threat_service_proto_depIdxs,
		MessageInfos:      file_ioc_v1_threat_service_proto_msgTypes,
	}.Build()
	File_ioc_v1_threat_service_proto = out.File
	file_ioc_v1_threat_service_proto_goTypes = nil
	file_ioc_v1_threat_service_proto_depIdxs = nil
}
