// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ioc/v1/threat.proto

package iocv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Threat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      ThreatCategory         `protobuf:"varint,3,opt,name=category,proto3,enum=ioc.v1.ThreatCategory" json:"category,omitempty"`
	Severity      Severity               `protobuf:"varint,4,opt,name=severity,proto3,enum=ioc.v1.Severity" json:"severity,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Indicators    []*IoC                 `protobuf:"bytes,6,rep,name=indicators,proto3" json:"indicators,omitempty"`
	Campaigns     []string               `protobuf:"bytes,8,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	ThreatActors  []string               `protobuf:"bytes,9,rep,name=threat_actors,json=threatActors,proto3" json:"threat_actors,omitempty"`
	Confidence    float32                `protobuf:"fixed32,10,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Metadata      *ThreatMetadata        `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Tags          []string               `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	IsActive      bool                   `protobuf:"varint,13,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Threat) Reset() {
	*x = Threat{}
	mi := &file_ioc_v1_threat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Threat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Threat) ProtoMessage() {}

func (x *Threat) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Threat.ProtoReflect.Descriptor instead.
func (*Threat) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_proto_rawDescGZIP(), []int{0}
}

func (x *Threat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Threat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Threat) GetCategory() ThreatCategory {
	if x != nil {
		return x.Category
	}
	return ThreatCategory_THREAT_CATEGORY_UNSPECIFIED
}

func (x *Threat) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Threat) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Threat) GetIndicators() []*IoC {
	if x != nil {
		return x.Indicators
	}
	return nil
}

func (x *Threat) GetCampaigns() []string {
	if x != nil {
		return x.Campaigns
	}
	return nil
}

func (x *Threat) GetThreatActors() []string {
	if x != nil {
		return x.ThreatActors
	}
	return nil
}

func (x *Threat) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Threat) GetMetadata() *ThreatMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Threat) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Threat) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Threat) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Threat) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ThreatMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ttps          []string               `protobuf:"bytes,1,rep,name=ttps,proto3" json:"ttps,omitempty"`
	References    []string               `protobuf:"bytes,2,rep,name=references,proto3" json:"references,omitempty"`
	CustomFields  *structpb.Struct       `protobuf:"bytes,3,opt,name=custom_fields,json=customFields,proto3" json:"custom_fields,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,5,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatMetadata) Reset() {
	*x = ThreatMetadata{}
	mi := &file_ioc_v1_threat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatMetadata) ProtoMessage() {}

func (x *ThreatMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatMetadata.ProtoReflect.Descriptor instead.
func (*ThreatMetadata) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_proto_rawDescGZIP(), []int{1}
}

func (x *ThreatMetadata) GetTtps() []string {
	if x != nil {
		return x.Ttps
	}
	return nil
}

func (x *ThreatMetadata) GetReferences() []string {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *ThreatMetadata) GetCustomFields() *structpb.Struct {
	if x != nil {
		return x.CustomFields
	}
	return nil
}

func (x *ThreatMetadata) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ThreatMetadata) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type ThreatCorrelation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreatId      string                 `protobuf:"bytes,1,opt,name=threat_id,json=threatId,proto3" json:"threat_id,omitempty"`
	IocId         string                 `protobuf:"bytes,2,opt,name=ioc_id,json=iocId,proto3" json:"ioc_id,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatCorrelation) Reset() {
	*x = ThreatCorrelation{}
	mi := &file_ioc_v1_threat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatCorrelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatCorrelation) ProtoMessage() {}

func (x *ThreatCorrelation) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatCorrelation.ProtoReflect.Descriptor instead.
func (*ThreatCorrelation) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_proto_rawDescGZIP(), []int{2}
}

func (x *ThreatCorrelation) GetThreatId() string {
	if x != nil {
		return x.ThreatId
	}
	return ""
}

func (x *ThreatCorrelation) GetIocId() string {
	if x != nil {
		return x.IocId
	}
	return ""
}

func (x *ThreatCorrelation) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ThreatCorrelation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ThreatIntelligence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        EnrichmentSource       `protobuf:"varint,1,opt,name=source,proto3,enum=ioc.v1.EnrichmentSource" json:"source,omitempty"`
	ThreatId      string                 `protobuf:"bytes,2,opt,name=threat_id,json=threatId,proto3" json:"threat_id,omitempty"`
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ReportedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	RawData       *structpb.Struct       `protobuf:"bytes,5,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatIntelligence) Reset() {
	*x = ThreatIntelligence{}
	mi := &file_ioc_v1_threat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatIntelligence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatIntelligence) ProtoMessage() {}

func (x *ThreatIntelligence) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatIntelligence.ProtoReflect.Descriptor instead.
func (*ThreatIntelligence) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_proto_rawDescGZIP(), []int{3}
}

func (x *ThreatIntelligence) GetSource() EnrichmentSource {
	if x != nil {
		return x.Source
	}
	return EnrichmentSource_ENRICHMENT_SOURCE_UNSPECIFIED
}

func (x *ThreatIntelligence) GetThreatId() string {
	if x != nil {
		return x.ThreatId
	}
	return ""
}

func (x *ThreatIntelligence) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ThreatIntelligence) GetReportedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReportedAt
	}
	return nil
}

func (x *ThreatIntelligence) GetRawData() *structpb.Struct {
	if x != nil {
		return x.RawData
	}
	return nil
}

type ThreatFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchQuery   string                 `protobuf:"bytes,1,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	Category      ThreatCategory         `protobuf:"varint,2,opt,name=category,proto3,enum=ioc.v1.ThreatCategory" json:"category,omitempty"`
	Severity      Severity               `protobuf:"varint,3,opt,name=severity,proto3,enum=ioc.v1.Severity" json:"severity,omitempty"`
	Campaign      string                 `protobuf:"bytes,4,opt,name=campaign,proto3" json:"campaign,omitempty"`
	ThreatActor   string                 `protobuf:"bytes,5,opt,name=threat_actor,json=threatActor,proto3" json:"threat_actor,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatFilter) Reset() {
	*x = ThreatFilter{}
	mi := &file_ioc_v1_threat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatFilter) ProtoMessage() {}

func (x *ThreatFilter) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatFilter.ProtoReflect.Descriptor instead.
func (*ThreatFilter) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_proto_rawDescGZIP(), []int{4}
}

func (x *ThreatFilter) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *ThreatFilter) GetCategory() ThreatCategory {
	if x != nil {
		return x.Category
	}
	return ThreatCategory_THREAT_CATEGORY_UNSPECIFIED
}

func (x *ThreatFilter) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *ThreatFilter) GetCampaign() string {
	if x != nil {
		return x.Campaign
	}
	return ""
}

func (x *ThreatFilter) GetThreatActor() string {
	if x != nil {
		return x.ThreatActor
	}
	return ""
}

func (x *ThreatFilter) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ThreatFilter) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ThreatFilter) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type ThreatStatistics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalThreats    int32                  `protobuf:"varint,1,opt,name=total_threats,json=totalThreats,proto3" json:"total_threats,omitempty"`
	ActiveThreats   int32                  `protobuf:"varint,2,opt,name=active_threats,json=activeThreats,proto3" json:"active_threats,omitempty"`
	ByCategory      map[string]int32       `protobuf:"bytes,3,rep,name=by_category,json=byCategory,proto3" json:"by_category,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	BySeverity      map[string]int32       `protobuf:"bytes,4,rep,name=by_severity,json=bySeverity,proto3" json:"by_severity,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TopCampaigns    []string               `protobuf:"bytes,5,rep,name=top_campaigns,json=topCampaigns,proto3" json:"top_campaigns,omitempty"`
	TopThreatActors []string               `protobuf:"bytes,6,rep,name=top_threat_actors,json=topThreatActors,proto3" json:"top_threat_actors,omitempty"`
	GeneratedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ThreatStatistics) Reset() {
	*x = ThreatStatistics{}
	mi := &file_ioc_v1_threat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatStatistics) ProtoMessage() {}

func (x *ThreatStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_ioc_v1_threat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatStatistics.ProtoReflect.Descriptor instead.
func (*ThreatStatistics) Descriptor() ([]byte, []int) {
	return file_ioc_v1_threat_proto_rawDescGZIP(), []int{5}
}

func (x *ThreatStatistics) GetTotalThreats() int32 {
	if x != nil {
		return x.TotalThreats
	}
	return 0
}

func (x *ThreatStatistics) GetActiveThreats() int32 {
	if x != nil {
		return x.ActiveThreats
	}
	return 0
}

func (x *ThreatStatistics) GetByCategory() map[string]int32 {
	if x != nil {
		return x.ByCategory
	}
	return nil
}

func (x *ThreatStatistics) GetBySeverity() map[string]int32 {
	if x != nil {
		return x.BySeverity
	}
	return nil
}

func (x *ThreatStatistics) GetTopCampaigns() []string {
	if x != nil {
		return x.TopCampaigns
	}
	return nil
}

func (x *ThreatStatistics) GetTopThreatActors() []string {
	if x != nil {
		return x.TopThreatActors
	}
	return nil
}

func (x *ThreatStatistics) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

var File_ioc_v1_threat_proto protoreflect.FileDescriptor

const file_ioc_v1_threat_proto_rawDesc = "" +
	"\n" +
	"\x13ioc/v1/threat.proto\x12\x06ioc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x13ioc/v1/common.proto\x1a\x10ioc/v1/ioc.proto\"\x9b\x04\n" +
	"\x06Threat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x122\n" +
	"\bcategory\x18\x03 \x01(\x0e2\x16.ioc.v1.ThreatCategoryR\bcategory\x12,\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x10.ioc.v1.SeverityR\bseverity\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12+\n" +
	"\n" +
	"indicators\x18\x06 \x03(\v2\v.ioc.v1.IoCR\n" +
	"indicators\x12\x1c\n" +
	"\tcampaigns\x18\b \x03(\tR\tcampaigns\x12#\n" +
	"\rthreat_actors\x18\t \x03(\tR\fthreatActors\x12\x1e\n" +
	"\n" +
	"confidence\x18\n" +
	" \x01(\x02R\n" +
	"confidence\x122\n" +
	"\bmetadata\x18\v \x01(\v2\x16.ioc.v1.ThreatMetadataR\bmetadata\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_active\x18\r \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc0\x01\n" +
	"\x0eThreatMetadata\x12\x12\n" +
	"\x04ttps\x18\x01 \x03(\tR\x04ttps\x12\x1e\n" +
	"\n" +
	"references\x18\x02 \x03(\tR\n" +
	"references\x12<\n" +
	"\rcustom_fields\x18\x03 \x01(\v2\x17.google.protobuf.StructR\fcustomFields\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x05 \x01(\tR\tupdatedBy\"\x9a\x01\n" +
	"\x11ThreatCorrelation\x12\x1b\n" +
	"\tthreat_id\x18\x01 \x01(\tR\bthreatId\x12\x15\n" +
	"\x06ioc_id\x18\x02 \x01(\tR\x05iocId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xf4\x01\n" +
	"\x12ThreatIntelligence\x120\n" +
	"\x06source\x18\x01 \x01(\x0e2\x18.ioc.v1.EnrichmentSourceR\x06source\x12\x1b\n" +
	"\tthreat_id\x18\x02 \x01(\tR\bthreatId\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12;\n" +
	"\vreported_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reportedAt\x122\n" +
	"\braw_data\x18\x05 \x01(\v2\x17.google.protobuf.StructR\arawData\"\xe1\x02\n" +
	"\fThreatFilter\x12!\n" +
	"\fsearch_query\x18\x01 \x01(\tR\vsearchQuery\x122\n" +
	"\bcategory\x18\x02 \x01(\x0e2\x16.ioc.v1.ThreatCategoryR\bcategory\x12,\n" +
	"\bseverity\x18\x03 \x01(\x0e2\x10.ioc.v1.SeverityR\bseverity\x12\x1a\n" +
	"\bcampaign\x18\x04 \x01(\tR\bcampaign\x12!\n" +
	"\fthreat_actor\x18\x05 \x01(\tR\vthreatActor\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"start_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\x82\x04\n" +
	"\x10ThreatStatistics\x12#\n" +
	"\rtotal_threats\x18\x01 \x01(\x05R\ftotalThreats\x12%\n" +
	"\x0eactive_threats\x18\x02 \x01(\x05R\ractiveThreats\x12I\n" +
	"\vby_category\x18\x03 \x03(\v2(.ioc.v1.ThreatStatistics.ByCategoryEntryR\n" +
	"byCategory\x12I\n" +
	"\vby_severity\x18\x04 \x03(\v2(.ioc.v1.ThreatStatistics.BySeverityEntryR\n" +
	"bySeverity\x12#\n" +
	"\rtop_campaigns\x18\x05 \x03(\tR\ftopCampaigns\x12*\n" +
	"\x11top_threat_actors\x18\x06 \x03(\tR\x0ftopThreatActors\x12=\n" +
	"\fgenerated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x1a=\n" +
	"\x0fByCategoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a=\n" +
	"\x0fBySeverityEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01BBZ@github.com/DgHnG36/ioc_enrichment_service/shared/go/ioc/v1;iocv1b\x06proto3"

var (
	file_ioc_v1_threat_proto_rawDescOnce sync.Once
	file_ioc_v1_threat_proto_rawDescData []byte
)

func file_ioc_v1_threat_proto_rawDescGZIP() []byte {
	file_ioc_v1_threat_proto_rawDescOnce.Do(func() {
		file_ioc_v1_threat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ioc_v1_threat_proto_rawDesc), len(file_ioc_v1_threat_proto_rawDesc)))
	})
	return file_ioc_v1_threat_proto_rawDescData
}

var file_ioc_v1_threat_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ioc_v1_threat_proto_goTypes = []any{
	(*Threat)(nil),                // 0: ioc.v1.Threat
	(*ThreatMetadata)(nil),        // 1: ioc.v1.ThreatMetadata
	(*ThreatCorrelation)(nil),     // 2: ioc.v1.ThreatCorrelation
	(*ThreatIntelligence)(nil),    // 3: ioc.v1.ThreatIntelligence
	(*ThreatFilter)(nil),          // 4: ioc.v1.ThreatFilter
	(*ThreatStatistics)(nil),      // 5: ioc.v1.ThreatStatistics
	nil,                           // 6: ioc.v1.ThreatStatistics.ByCategoryEntry
	nil,                           // 7: ioc.v1.ThreatStatistics.BySeverityEntry
	(ThreatCategory)(0),           // 8: ioc.v1.ThreatCategory
	(Severity)(0),                 // 9: ioc.v1.Severity
	(*IoC)(nil),                   // 10: ioc.v1.IoC
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 12: google.protobuf.Struct
	(EnrichmentSource)(0),         // 13: ioc.v1.EnrichmentSource
}
var file_ioc_v1_threat_proto_depIdxs = []int32{
	8,  // 0: ioc.v1.Threat.category:type_name -> ioc.v1.ThreatCategory
	9,  // 1: ioc.v1.Threat.severity:type_name -> ioc.v1.Severity
	10, // 2: ioc.v1.Threat.indicators:type_name -> ioc.v1.IoC
	1,  // 3: ioc.v1.Threat.metadata:type_name -> ioc.v1.ThreatMetadata
	11, // 4: ioc.v1.Threat.created_at:type_name -> google.protobuf.Timestamp
	11, // 5: ioc.v1.Threat.updated_at:type_name -> google.protobuf.Timestamp
	12, // 6: ioc.v1.ThreatMetadata.custom_fields:type_name -> google.protobuf.Struct
	11, // 7: ioc.v1.ThreatCorrelation.created_at:type_name -> google.protobuf.Timestamp
	13, // 8: ioc.v1.ThreatIntelligence.source:type_name -> ioc.v1.EnrichmentSource
	11, // 9: ioc.v1.ThreatIntelligence.reported_at:type_name -> google.protobuf.Timestamp
	12, // 10: ioc.v1.ThreatIntelligence.raw_data:type_name -> google.protobuf.Struct
	8,  // 11: ioc.v1.ThreatFilter.category:type_name -> ioc.v1.ThreatCategory
	9,  // 12: ioc.v1.ThreatFilter.severity:type_name -> ioc.v1.Severity
	11, // 13: ioc.v1.ThreatFilter.start_date:type_name -> google.protobuf.Timestamp
	11, // 14: ioc.v1.ThreatFilter.end_date:type_name -> google.protobuf.Timestamp
	6,  // 15: ioc.v1.ThreatStatistics.by_category:type_name -> ioc.v1.ThreatStatistics.ByCategoryEntry
	7,  // 16: ioc.v1.ThreatStatistics.by_severity:type_name -> ioc.v1.ThreatStatistics.BySeverityEntry
	11, // 17: ioc.v1.ThreatStatistics.generated_at:type_name -> google.protobuf.Timestamp
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_ioc_v1_threat_proto_init() }
func file_ioc_v1_threat_proto_init() {
	if File_ioc_v1_threat_proto != nil {
		return
	}
	file_ioc_v1_common_proto_init()
	file_ioc_v1_ioc_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ioc_v1_threat_proto_rawDesc), len(file_ioc_v1_threat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ioc_v1_threat_proto_goTypes,
		DependencyIndexes: file_ioc_v1_threat_proto_depIdxs,
		MessageInfos:      file_ioc_v1_threat_proto_msgTypes,
	}.Build()
	File_ioc_v1_threat_proto = out.File
	file_ioc_v1_threat_proto_goTypes = nil
	file_ioc_v1_threat_proto_depIdxs = nil
}
