// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: ioc/v1/threat_service.proto

package iocv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ThreatService_BatchUpsertThreats_FullMethodName  = "/ioc.v1.ThreatService/BatchUpsertThreats"
	ThreatService_GetThreat_FullMethodName           = "/ioc.v1.ThreatService/GetThreat"
	ThreatService_DeleteThreats_FullMethodName       = "/ioc.v1.ThreatService/DeleteThreats"
	ThreatService_FindThreats_FullMethodName         = "/ioc.v1.ThreatService/FindThreats"
	ThreatService_GetThreatStatistics_FullMethodName = "/ioc.v1.ThreatService/GetThreatStatistics"
	ThreatService_GetThreatsByIoC_FullMethodName     = "/ioc.v1.ThreatService/GetThreatsByIoC"
	ThreatService_GetThreatsByTTP_FullMethodName     = "/ioc.v1.ThreatService/GetThreatsByTTP"
	ThreatService_CorrelateThreat_FullMethodName     = "/ioc.v1.ThreatService/CorrelateThreat"
	ThreatService_LinkIoCs_FullMethodName            = "/ioc.v1.ThreatService/LinkIoCs"
	ThreatService_UnlinkIoCs_FullMethodName          = "/ioc.v1.ThreatService/UnlinkIoCs"
)

// ThreatServiceClient is the client API for ThreatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThreatServiceClient interface {
	BatchUpsertThreats(ctx context.Context, in *BatchUpsertThreatsRequest, opts ...grpc.CallOption) (*BatchUpsertThreatsResponse, error)
	GetThreat(ctx context.Context, in *GetThreatRequest, opts ...grpc.CallOption) (*GetThreatResponse, error)
	DeleteThreats(ctx context.Context, in *DeleteThreatsRequest, opts ...grpc.CallOption) (*DeleteThreatsResponse, error)
	FindThreats(ctx context.Context, in *FindThreatsRequest, opts ...grpc.CallOption) (*FindThreatsResponse, error)
	GetThreatStatistics(ctx context.Context, in *GetThreatStatisticsRequest, opts ...grpc.CallOption) (*GetThreatStatisticsResponse, error)
	GetThreatsByIoC(ctx context.Context, in *GetThreatsByIoCRequest, opts ...grpc.CallOption) (*GetThreatsByIoCResponse, error)
	GetThreatsByTTP(ctx context.Context, in *GetThreatsByTTPRequest, opts ...grpc.CallOption) (*GetThreatsByTTPResponse, error)
	CorrelateThreat(ctx context.Context, in *CorrelateThreatRequest, opts ...grpc.CallOption) (*CorrelateThreatResponse, error)
	LinkIoCs(ctx context.Context, in *LinkIoCsRequest, opts ...grpc.CallOption) (*LinkIoCsResponse, error)
	UnlinkIoCs(ctx context.Context, in *UnlinkIoCsRequest, opts ...grpc.CallOption) (*UnlinkIoCsResponse, error)
}

type threatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewThreatServiceClient(cc grpc.ClientConnInterface) ThreatServiceClient {
	return &threatServiceClient{cc}
}

func (c *threatServiceClient) BatchUpsertThreats(ctx context.Context, in *BatchUpsertThreatsRequest, opts ...grpc.CallOption) (*BatchUpsertThreatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUpsertThreatsResponse)
	err := c.cc.Invoke(ctx, ThreatService_BatchUpsertThreats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threatServiceClient) GetThreat(ctx context.Context, in *GetThreatRequest, opts ...grpc.CallOption) (*GetThreatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetThreatResponse)
	err := c.cc.Invoke(ctx, ThreatService_GetThreat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threatServiceClient) DeleteThreats(ctx context.Context, in *DeleteThreatsRequest, opts ...grpc.CallOption) (*DeleteThreatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteThreatsResponse)
	err := c.cc.Invoke(ctx, ThreatService_DeleteThreats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threatServiceClient) FindThreats(ctx context.Context, in *FindThreatsRequest, opts ...grpc.CallOption) (*FindThreatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindThreatsResponse)
	err := c.cc.Invoke(ctx, ThreatService_FindThreats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threatServiceClient) GetThreatStatistics(ctx context.Context, in *GetThreatStatisticsRequest, opts ...grpc.CallOption) (*GetThreatStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetThreatStatisticsResponse)
	err := c.cc.Invoke(ctx, ThreatService_GetThreatStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threatServiceClient) GetThreatsByIoC(ctx context.Context, in *GetThreatsByIoCRequest, opts ...grpc.CallOption) (*GetThreatsByIoCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetThreatsByIoCResponse)
	err := c.cc.Invoke(ctx, ThreatService_GetThreatsByIoC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threatServiceClient) GetThreatsByTTP(ctx context.Context, in *GetThreatsByTTPRequest, opts ...grpc.CallOption) (*GetThreatsByTTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetThreatsByTTPResponse)
	err := c.cc.Invoke(ctx, ThreatService_GetThreatsByTTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threatServiceClient) CorrelateThreat(ctx context.Context, in *CorrelateThreatRequest, opts ...grpc.CallOption) (*CorrelateThreatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CorrelateThreatResponse)
	err := c.cc.Invoke(ctx, ThreatService_CorrelateThreat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threatServiceClient) LinkIoCs(ctx context.Context, in *LinkIoCsRequest, opts ...grpc.CallOption) (*LinkIoCsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkIoCsResponse)
	err := c.cc.Invoke(ctx, ThreatService_LinkIoCs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *threatServiceClient) UnlinkIoCs(ctx context.Context, in *UnlinkIoCsRequest, opts ...grpc.CallOption) (*UnlinkIoCsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlinkIoCsResponse)
	err := c.cc.Invoke(ctx, ThreatService_UnlinkIoCs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThreatServiceServer is the server API for ThreatService service.
// All implementations must embed UnimplementedThreatServiceServer
// for forward compatibility.
type ThreatServiceServer interface {
	BatchUpsertThreats(context.Context, *BatchUpsertThreatsRequest) (*BatchUpsertThreatsResponse, error)
	GetThreat(context.Context, *GetThreatRequest) (*GetThreatResponse, error)
	DeleteThreats(context.Context, *DeleteThreatsRequest) (*DeleteThreatsResponse, error)
	FindThreats(context.Context, *FindThreatsRequest) (*FindThreatsResponse, error)
	GetThreatStatistics(context.Context, *GetThreatStatisticsRequest) (*GetThreatStatisticsResponse, error)
	GetThreatsByIoC(context.Context, *GetThreatsByIoCRequest) (*GetThreatsByIoCResponse, error)
	GetThreatsByTTP(context.Context, *GetThreatsByTTPRequest) (*GetThreatsByTTPResponse, error)
	CorrelateThreat(context.Context, *CorrelateThreatRequest) (*CorrelateThreatResponse, error)
	LinkIoCs(context.Context, *LinkIoCsRequest) (*LinkIoCsResponse, error)
	UnlinkIoCs(context.Context, *UnlinkIoCsRequest) (*UnlinkIoCsResponse, error)
	mustEmbedUnimplementedThreatServiceServer()
}

// UnimplementedThreatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedThreatServiceServer struct{}

func (UnimplementedThreatServiceServer) BatchUpsertThreats(context.Context, *BatchUpsertThreatsRequest) (*BatchUpsertThreatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchUpsertThreats not implemented")
}
func (UnimplementedThreatServiceServer) GetThreat(context.Context, *GetThreatRequest) (*GetThreatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThreat not implemented")
}
func (UnimplementedThreatServiceServer) DeleteThreats(context.Context, *DeleteThreatsRequest) (*DeleteThreatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteThreats not implemented")
}
func (UnimplementedThreatServiceServer) FindThreats(context.Context, *FindThreatsRequest) (*FindThreatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindThreats not implemented")
}
func (UnimplementedThreatServiceServer) GetThreatStatistics(context.Context, *GetThreatStatisticsRequest) (*GetThreatStatisticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThreatStatistics not implemented")
}
func (UnimplementedThreatServiceServer) GetThreatsByIoC(context.Context, *GetThreatsByIoCRequest) (*GetThreatsByIoCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThreatsByIoC not implemented")
}
func (UnimplementedThreatServiceServer) GetThreatsByTTP(context.Context, *GetThreatsByTTPRequest) (*GetThreatsByTTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThreatsByTTP not implemented")
}
func (UnimplementedThreatServiceServer) CorrelateThreat(context.Context, *CorrelateThreatRequest) (*CorrelateThreatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CorrelateThreat not implemented")
}
func (UnimplementedThreatServiceServer) LinkIoCs(context.Context, *LinkIoCsRequest) (*LinkIoCsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkIoCs not implemented")
}
func (UnimplementedThreatServiceServer) UnlinkIoCs(context.Context, *UnlinkIoCsRequest) (*UnlinkIoCsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlinkIoCs not implemented")
}
func (UnimplementedThreatServiceServer) mustEmbedUnimplementedThreatServiceServer() {}
func (UnimplementedThreatServiceServer) testEmbeddedByValue()                       {}

// UnsafeThreatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThreatServiceServer will
// result in compilation errors.
type UnsafeThreatServiceServer interface {
	mustEmbedUnimplementedThreatServiceServer()
}

func RegisterThreatServiceServer(s grpc.ServiceRegistrar, srv ThreatServiceServer) {
	// If the following call panics, it indicates UnimplementedThreatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ThreatService_ServiceDesc, srv)
}

func _ThreatService_BatchUpsertThreats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpsertThreatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreatServiceServer).BatchUpsertThreats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreatService_BatchUpsertThreats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreatServiceServer).BatchUpsertThreats(ctx, req.(*BatchUpsertThreatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreatService_GetThreat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThreatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreatServiceServer).GetThreat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreatService_GetThreat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreatServiceServer).GetThreat(ctx, req.(*GetThreatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreatService_DeleteThreats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteThreatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreatServiceServer).DeleteThreats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreatService_DeleteThreats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreatServiceServer).DeleteThreats(ctx, req.(*DeleteThreatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreatService_FindThreats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindThreatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreatServiceServer).FindThreats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreatService_FindThreats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreatServiceServer).FindThreats(ctx, req.(*FindThreatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreatService_GetThreatStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThreatStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreatServiceServer).GetThreatStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreatService_GetThreatStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreatServiceServer).GetThreatStatistics(ctx, req.(*GetThreatStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreatService_GetThreatsByIoC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThreatsByIoCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreatServiceServer).GetThreatsByIoC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreatService_GetThreatsByIoC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreatServiceServer).GetThreatsByIoC(ctx, req.(*GetThreatsByIoCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreatService_GetThreatsByTTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThreatsByTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreatServiceServer).GetThreatsByTTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreatService_GetThreatsByTTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreatServiceServer).GetThreatsByTTP(ctx, req.(*GetThreatsByTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreatService_CorrelateThreat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CorrelateThreatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreatServiceServer).CorrelateThreat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreatService_CorrelateThreat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreatServiceServer).CorrelateThreat(ctx, req.(*CorrelateThreatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreatService_LinkIoCs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkIoCsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreatServiceServer).LinkIoCs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreatService_LinkIoCs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreatServiceServer).LinkIoCs(ctx, req.(*LinkIoCsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ThreatService_UnlinkIoCs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkIoCsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreatServiceServer).UnlinkIoCs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreatService_UnlinkIoCs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreatServiceServer).UnlinkIoCs(ctx, req.(*UnlinkIoCsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ThreatService_ServiceDesc is the grpc.ServiceDesc for ThreatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThreatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ioc.v1.ThreatService",
	HandlerType: (*ThreatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchUpsertThreats",
			Handler:    _ThreatService_BatchUpsertThreats_Handler,
		},
		{
			MethodName: "GetThreat",
			Handler:    _ThreatService_GetThreat_Handler,
		},
		{
			MethodName: "DeleteThreats",
			Handler:    _ThreatService_DeleteThreats_Handler,
		},
		{
			MethodName: "FindThreats",
			Handler:    _ThreatService_FindThreats_Handler,
		},
		{
			MethodName: "GetThreatStatistics",
			Handler:    _ThreatService_GetThreatStatistics_Handler,
		},
		{
			MethodName: "GetThreatsByIoC",
			Handler:    _ThreatService_GetThreatsByIoC_Handler,
		},
		{
			MethodName: "GetThreatsByTTP",
			Handler:    _ThreatService_GetThreatsByTTP_Handler,
		},
		{
			MethodName: "CorrelateThreat",
			Handler:    _ThreatService_CorrelateThreat_Handler,
		},
		{
			MethodName: "LinkIoCs",
			Handler:    _ThreatService_LinkIoCs_Handler,
		},
		{
			MethodName: "UnlinkIoCs",
			Handler:    _ThreatService_UnlinkIoCs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ioc/v1/threat_service.proto",
}
