# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import enrichment_service_pb2 as enrichment_dot_v1_dot_enrichment__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in enrichment/v1/enrichment_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EnrichmentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnrichIP = channel.unary_unary(
                '/enrichment.v1.EnrichmentService/EnrichIP',
                request_serializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichIPRequest.SerializeToString,
                response_deserializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichIPResponse.FromString,
                _registered_method=True)
        self.EnrichDomain = channel.unary_unary(
                '/enrichment.v1.EnrichmentService/EnrichDomain',
                request_serializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichDomainRequest.SerializeToString,
                response_deserializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichDomainResponse.FromString,
                _registered_method=True)
        self.EnrichHash = channel.unary_unary(
                '/enrichment.v1.EnrichmentService/EnrichHash',
                request_serializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichHashRequest.SerializeToString,
                response_deserializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichHashResponse.FromString,
                _registered_method=True)
        self.EnrichURL = channel.unary_unary(
                '/enrichment.v1.EnrichmentService/EnrichURL',
                request_serializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichURLRequest.SerializeToString,
                response_deserializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichURLResponse.FromString,
                _registered_method=True)
        self.EnrichFilePath = channel.unary_unary(
                '/enrichment.v1.EnrichmentService/EnrichFilePath',
                request_serializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichFilePathRequest.SerializeToString,
                response_deserializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichFilePathResponse.FromString,
                _registered_method=True)
        self.Enrich = channel.unary_unary(
                '/enrichment.v1.EnrichmentService/Enrich',
                request_serializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichRequest.SerializeToString,
                response_deserializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichResponse.FromString,
                _registered_method=True)
        self.EnrichBatch = channel.unary_unary(
                '/enrichment.v1.EnrichmentService/EnrichBatch',
                request_serializer=enrichment_dot_v1_dot_enrichment__service__pb2.BatchEnrichRequest.SerializeToString,
                response_deserializer=enrichment_dot_v1_dot_enrichment__service__pb2.BatchEnrichResponse.FromString,
                _registered_method=True)
        self.GetReputation = channel.unary_unary(
                '/enrichment.v1.EnrichmentService/GetReputation',
                request_serializer=enrichment_dot_v1_dot_enrichment__service__pb2.GetReputationRequest.SerializeToString,
                response_deserializer=enrichment_dot_v1_dot_enrichment__service__pb2.GetReputationResponse.FromString,
                _registered_method=True)
        self.StreamEnrich = channel.stream_stream(
                '/enrichment.v1.EnrichmentService/StreamEnrich',
                request_serializer=enrichment_dot_v1_dot_enrichment__service__pb2.StreamEnrichRequest.SerializeToString,
                response_deserializer=enrichment_dot_v1_dot_enrichment__service__pb2.StreamEnrichResponse.FromString,
                _registered_method=True)
        self.CheckSourceHealth = channel.unary_unary(
                '/enrichment.v1.EnrichmentService/CheckSourceHealth',
                request_serializer=enrichment_dot_v1_dot_enrichment__service__pb2.CheckSourceHealthRequest.SerializeToString,
                response_deserializer=enrichment_dot_v1_dot_enrichment__service__pb2.CheckSourceHealthResponse.FromString,
                _registered_method=True)


class EnrichmentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EnrichIP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrichDomain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrichHash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrichURL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrichFilePath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Enrich(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrichBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReputation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEnrich(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckSourceHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnrichmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnrichIP': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrichIP,
                    request_deserializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichIPRequest.FromString,
                    response_serializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichIPResponse.SerializeToString,
            ),
            'EnrichDomain': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrichDomain,
                    request_deserializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichDomainRequest.FromString,
                    response_serializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichDomainResponse.SerializeToString,
            ),
            'EnrichHash': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrichHash,
                    request_deserializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichHashRequest.FromString,
                    response_serializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichHashResponse.SerializeToString,
            ),
            'EnrichURL': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrichURL,
                    request_deserializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichURLRequest.FromString,
                    response_serializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichURLResponse.SerializeToString,
            ),
            'EnrichFilePath': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrichFilePath,
                    request_deserializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichFilePathRequest.FromString,
                    response_serializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichFilePathResponse.SerializeToString,
            ),
            'Enrich': grpc.unary_unary_rpc_method_handler(
                    servicer.Enrich,
                    request_deserializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichRequest.FromString,
                    response_serializer=enrichment_dot_v1_dot_enrichment__service__pb2.EnrichResponse.SerializeToString,
            ),
            'EnrichBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrichBatch,
                    request_deserializer=enrichment_dot_v1_dot_enrichment__service__pb2.BatchEnrichRequest.FromString,
                    response_serializer=enrichment_dot_v1_dot_enrichment__service__pb2.BatchEnrichResponse.SerializeToString,
            ),
            'GetReputation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReputation,
                    request_deserializer=enrichment_dot_v1_dot_enrichment__service__pb2.GetReputationRequest.FromString,
                    response_serializer=enrichment_dot_v1_dot_enrichment__service__pb2.GetReputationResponse.SerializeToString,
            ),
            'StreamEnrich': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamEnrich,
                    request_deserializer=enrichment_dot_v1_dot_enrichment__service__pb2.StreamEnrichRequest.FromString,
                    response_serializer=enrichment_dot_v1_dot_enrichment__service__pb2.StreamEnrichResponse.SerializeToString,
            ),
            'CheckSourceHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSourceHealth,
                    request_deserializer=enrichment_dot_v1_dot_enrichment__service__pb2.CheckSourceHealthRequest.FromString,
                    response_serializer=enrichment_dot_v1_dot_enrichment__service__pb2.CheckSourceHealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'enrichment.v1.EnrichmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('enrichment.v1.EnrichmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnrichmentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnrichIP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enrichment.v1.EnrichmentService/EnrichIP',
            enrichment_dot_v1_dot_enrichment__service__pb2.EnrichIPRequest.SerializeToString,
            enrichment_dot_v1_dot_enrichment__service__pb2.EnrichIPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnrichDomain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enrichment.v1.EnrichmentService/EnrichDomain',
            enrichment_dot_v1_dot_enrichment__service__pb2.EnrichDomainRequest.SerializeToString,
            enrichment_dot_v1_dot_enrichment__service__pb2.EnrichDomainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnrichHash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enrichment.v1.EnrichmentService/EnrichHash',
            enrichment_dot_v1_dot_enrichment__service__pb2.EnrichHashRequest.SerializeToString,
            enrichment_dot_v1_dot_enrichment__service__pb2.EnrichHashResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnrichURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enrichment.v1.EnrichmentService/EnrichURL',
            enrichment_dot_v1_dot_enrichment__service__pb2.EnrichURLRequest.SerializeToString,
            enrichment_dot_v1_dot_enrichment__service__pb2.EnrichURLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnrichFilePath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enrichment.v1.EnrichmentService/EnrichFilePath',
            enrichment_dot_v1_dot_enrichment__service__pb2.EnrichFilePathRequest.SerializeToString,
            enrichment_dot_v1_dot_enrichment__service__pb2.EnrichFilePathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Enrich(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enrichment.v1.EnrichmentService/Enrich',
            enrichment_dot_v1_dot_enrichment__service__pb2.EnrichRequest.SerializeToString,
            enrichment_dot_v1_dot_enrichment__service__pb2.EnrichResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnrichBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enrichment.v1.EnrichmentService/EnrichBatch',
            enrichment_dot_v1_dot_enrichment__service__pb2.BatchEnrichRequest.SerializeToString,
            enrichment_dot_v1_dot_enrichment__service__pb2.BatchEnrichResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReputation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enrichment.v1.EnrichmentService/GetReputation',
            enrichment_dot_v1_dot_enrichment__service__pb2.GetReputationRequest.SerializeToString,
            enrichment_dot_v1_dot_enrichment__service__pb2.GetReputationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEnrich(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/enrichment.v1.EnrichmentService/StreamEnrich',
            enrichment_dot_v1_dot_enrichment__service__pb2.StreamEnrichRequest.SerializeToString,
            enrichment_dot_v1_dot_enrichment__service__pb2.StreamEnrichResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckSourceHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enrichment.v1.EnrichmentService/CheckSourceHealth',
            enrichment_dot_v1_dot_enrichment__service__pb2.CheckSourceHealthRequest.SerializeToString,
            enrichment_dot_v1_dot_enrichment__service__pb2.CheckSourceHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
