// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: enrichment/v1/enrichment_service.proto

package enrichmentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrichOptions struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	HasType             string                 `protobuf:"bytes,1,opt,name=has_type,json=hasType,proto3" json:"has_type,omitempty"`
	IncludeFileMetadata bool                   `protobuf:"varint,2,opt,name=include_file_metadata,json=includeFileMetadata,proto3" json:"include_file_metadata,omitempty"`
	ForceRefresh        bool                   `protobuf:"varint,3,opt,name=force_refresh,json=forceRefresh,proto3" json:"force_refresh,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EnrichOptions) Reset() {
	*x = EnrichOptions{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichOptions) ProtoMessage() {}

func (x *EnrichOptions) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichOptions.ProtoReflect.Descriptor instead.
func (*EnrichOptions) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{0}
}

func (x *EnrichOptions) GetHasType() string {
	if x != nil {
		return x.HasType
	}
	return ""
}

func (x *EnrichOptions) GetIncludeFileMetadata() bool {
	if x != nil {
		return x.IncludeFileMetadata
	}
	return false
}

func (x *EnrichOptions) GetForceRefresh() bool {
	if x != nil {
		return x.ForceRefresh
	}
	return false
}

type EnrichIPRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ip             string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Sources        []EnrichmentSource     `protobuf:"varint,2,rep,packed,name=sources,proto3,enum=enrichment.v1.EnrichmentSource" json:"sources,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnrichIPRequest) Reset() {
	*x = EnrichIPRequest{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichIPRequest) ProtoMessage() {}

func (x *EnrichIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichIPRequest.ProtoReflect.Descriptor instead.
func (*EnrichIPRequest) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{1}
}

func (x *EnrichIPRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *EnrichIPRequest) GetSources() []EnrichmentSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *EnrichIPRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type EnrichIPResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Ip            string                      `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Results       map[string]*ThreatIntelData `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Aggregated    *AggregatedScore            `protobuf:"bytes,3,opt,name=aggregated,proto3" json:"aggregated,omitempty"`
	IpData        *IPEnrichmentData           `protobuf:"bytes,4,opt,name=ip_data,json=ipData,proto3" json:"ip_data,omitempty"`
	EnrichedAt    *timestamppb.Timestamp      `protobuf:"bytes,5,opt,name=enriched_at,json=enrichedAt,proto3" json:"enriched_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichIPResponse) Reset() {
	*x = EnrichIPResponse{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichIPResponse) ProtoMessage() {}

func (x *EnrichIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichIPResponse.ProtoReflect.Descriptor instead.
func (*EnrichIPResponse) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{2}
}

func (x *EnrichIPResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *EnrichIPResponse) GetResults() map[string]*ThreatIntelData {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *EnrichIPResponse) GetAggregated() *AggregatedScore {
	if x != nil {
		return x.Aggregated
	}
	return nil
}

func (x *EnrichIPResponse) GetIpData() *IPEnrichmentData {
	if x != nil {
		return x.IpData
	}
	return nil
}

func (x *EnrichIPResponse) GetEnrichedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnrichedAt
	}
	return nil
}

type EnrichDomainRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Domain         string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Sources        []EnrichmentSource     `protobuf:"varint,2,rep,packed,name=sources,proto3,enum=enrichment.v1.EnrichmentSource" json:"sources,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnrichDomainRequest) Reset() {
	*x = EnrichDomainRequest{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichDomainRequest) ProtoMessage() {}

func (x *EnrichDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichDomainRequest.ProtoReflect.Descriptor instead.
func (*EnrichDomainRequest) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{3}
}

func (x *EnrichDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *EnrichDomainRequest) GetSources() []EnrichmentSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *EnrichDomainRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type EnrichDomainResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Domain        string                      `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Results       map[string]*ThreatIntelData `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Aggregated    *AggregatedScore            `protobuf:"bytes,3,opt,name=aggregated,proto3" json:"aggregated,omitempty"`
	DomainData    *DomainEnrichmentData       `protobuf:"bytes,4,opt,name=domain_data,json=domainData,proto3" json:"domain_data,omitempty"`
	EnrichedAt    *timestamppb.Timestamp      `protobuf:"bytes,5,opt,name=enriched_at,json=enrichedAt,proto3" json:"enriched_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichDomainResponse) Reset() {
	*x = EnrichDomainResponse{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichDomainResponse) ProtoMessage() {}

func (x *EnrichDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichDomainResponse.ProtoReflect.Descriptor instead.
func (*EnrichDomainResponse) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{4}
}

func (x *EnrichDomainResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *EnrichDomainResponse) GetResults() map[string]*ThreatIntelData {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *EnrichDomainResponse) GetAggregated() *AggregatedScore {
	if x != nil {
		return x.Aggregated
	}
	return nil
}

func (x *EnrichDomainResponse) GetDomainData() *DomainEnrichmentData {
	if x != nil {
		return x.DomainData
	}
	return nil
}

func (x *EnrichDomainResponse) GetEnrichedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnrichedAt
	}
	return nil
}

type EnrichHashRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hash           string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Options        *EnrichOptions         `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	Sources        []EnrichmentSource     `protobuf:"varint,3,rep,packed,name=sources,proto3,enum=enrichment.v1.EnrichmentSource" json:"sources,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnrichHashRequest) Reset() {
	*x = EnrichHashRequest{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichHashRequest) ProtoMessage() {}

func (x *EnrichHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichHashRequest.ProtoReflect.Descriptor instead.
func (*EnrichHashRequest) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{5}
}

func (x *EnrichHashRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *EnrichHashRequest) GetOptions() *EnrichOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *EnrichHashRequest) GetSources() []EnrichmentSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *EnrichHashRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type EnrichHashResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Hash          string                      `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Results       map[string]*ThreatIntelData `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Aggregated    *AggregatedScore            `protobuf:"bytes,3,opt,name=aggregated,proto3" json:"aggregated,omitempty"`
	HashData      *HashEnrichmentData         `protobuf:"bytes,4,opt,name=hash_data,json=hashData,proto3" json:"hash_data,omitempty"`
	EnrichedAt    *timestamppb.Timestamp      `protobuf:"bytes,5,opt,name=enriched_at,json=enrichedAt,proto3" json:"enriched_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichHashResponse) Reset() {
	*x = EnrichHashResponse{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichHashResponse) ProtoMessage() {}

func (x *EnrichHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichHashResponse.ProtoReflect.Descriptor instead.
func (*EnrichHashResponse) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{6}
}

func (x *EnrichHashResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *EnrichHashResponse) GetResults() map[string]*ThreatIntelData {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *EnrichHashResponse) GetAggregated() *AggregatedScore {
	if x != nil {
		return x.Aggregated
	}
	return nil
}

func (x *EnrichHashResponse) GetHashData() *HashEnrichmentData {
	if x != nil {
		return x.HashData
	}
	return nil
}

func (x *EnrichHashResponse) GetEnrichedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnrichedAt
	}
	return nil
}

type EnrichURLRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Url            string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Sources        []EnrichmentSource     `protobuf:"varint,2,rep,packed,name=sources,proto3,enum=enrichment.v1.EnrichmentSource" json:"sources,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnrichURLRequest) Reset() {
	*x = EnrichURLRequest{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichURLRequest) ProtoMessage() {}

func (x *EnrichURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichURLRequest.ProtoReflect.Descriptor instead.
func (*EnrichURLRequest) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{7}
}

func (x *EnrichURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *EnrichURLRequest) GetSources() []EnrichmentSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *EnrichURLRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type EnrichURLResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Url           string                      `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Results       map[string]*ThreatIntelData `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Aggregated    *AggregatedScore            `protobuf:"bytes,3,opt,name=aggregated,proto3" json:"aggregated,omitempty"`
	UrlData       *URLEnrichmentData          `protobuf:"bytes,4,opt,name=url_data,json=urlData,proto3" json:"url_data,omitempty"`
	EnrichedAt    *timestamppb.Timestamp      `protobuf:"bytes,5,opt,name=enriched_at,json=enrichedAt,proto3" json:"enriched_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichURLResponse) Reset() {
	*x = EnrichURLResponse{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichURLResponse) ProtoMessage() {}

func (x *EnrichURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichURLResponse.ProtoReflect.Descriptor instead.
func (*EnrichURLResponse) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{8}
}

func (x *EnrichURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *EnrichURLResponse) GetResults() map[string]*ThreatIntelData {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *EnrichURLResponse) GetAggregated() *AggregatedScore {
	if x != nil {
		return x.Aggregated
	}
	return nil
}

func (x *EnrichURLResponse) GetUrlData() *URLEnrichmentData {
	if x != nil {
		return x.UrlData
	}
	return nil
}

func (x *EnrichURLResponse) GetEnrichedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnrichedAt
	}
	return nil
}

type EnrichFilePathRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FilePath       string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Sources        []EnrichmentSource     `protobuf:"varint,2,rep,packed,name=sources,proto3,enum=enrichment.v1.EnrichmentSource" json:"sources,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnrichFilePathRequest) Reset() {
	*x = EnrichFilePathRequest{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichFilePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichFilePathRequest) ProtoMessage() {}

func (x *EnrichFilePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichFilePathRequest.ProtoReflect.Descriptor instead.
func (*EnrichFilePathRequest) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{9}
}

func (x *EnrichFilePathRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *EnrichFilePathRequest) GetSources() []EnrichmentSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *EnrichFilePathRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type EnrichFilePathResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	FilePath      string                      `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Results       map[string]*ThreatIntelData `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Aggregated    *AggregatedScore            `protobuf:"bytes,3,opt,name=aggregated,proto3" json:"aggregated,omitempty"`
	FilePathData  *FilePathEnrichmentData     `protobuf:"bytes,4,opt,name=file_path_data,json=filePathData,proto3" json:"file_path_data,omitempty"`
	EnrichedAt    *timestamppb.Timestamp      `protobuf:"bytes,5,opt,name=enriched_at,json=enrichedAt,proto3" json:"enriched_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichFilePathResponse) Reset() {
	*x = EnrichFilePathResponse{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichFilePathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichFilePathResponse) ProtoMessage() {}

func (x *EnrichFilePathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichFilePathResponse.ProtoReflect.Descriptor instead.
func (*EnrichFilePathResponse) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{10}
}

func (x *EnrichFilePathResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *EnrichFilePathResponse) GetResults() map[string]*ThreatIntelData {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *EnrichFilePathResponse) GetAggregated() *AggregatedScore {
	if x != nil {
		return x.Aggregated
	}
	return nil
}

func (x *EnrichFilePathResponse) GetFilePathData() *FilePathEnrichmentData {
	if x != nil {
		return x.FilePathData
	}
	return nil
}

func (x *EnrichFilePathResponse) GetEnrichedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnrichedAt
	}
	return nil
}

type EnrichRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Value          string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Sources        []EnrichmentSource     `protobuf:"varint,3,rep,packed,name=sources,proto3,enum=enrichment.v1.EnrichmentSource" json:"sources,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Options        *EnrichOptions         `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnrichRequest) Reset() {
	*x = EnrichRequest{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichRequest) ProtoMessage() {}

func (x *EnrichRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichRequest.ProtoReflect.Descriptor instead.
func (*EnrichRequest) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{11}
}

func (x *EnrichRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EnrichRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EnrichRequest) GetSources() []EnrichmentSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *EnrichRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *EnrichRequest) GetOptions() *EnrichOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type EnrichResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Value         string                      `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Type          string                      `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Results       map[string]*ThreatIntelData `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Aggregated    *AggregatedScore            `protobuf:"bytes,4,opt,name=aggregated,proto3" json:"aggregated,omitempty"`
	EnrichedAt    *timestamppb.Timestamp      `protobuf:"bytes,5,opt,name=enriched_at,json=enrichedAt,proto3" json:"enriched_at,omitempty"`
	RawDetails    *structpb.Struct            `protobuf:"bytes,6,opt,name=raw_details,json=rawDetails,proto3" json:"raw_details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichResponse) Reset() {
	*x = EnrichResponse{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichResponse) ProtoMessage() {}

func (x *EnrichResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichResponse.ProtoReflect.Descriptor instead.
func (*EnrichResponse) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{12}
}

func (x *EnrichResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EnrichResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EnrichResponse) GetResults() map[string]*ThreatIntelData {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *EnrichResponse) GetAggregated() *AggregatedScore {
	if x != nil {
		return x.Aggregated
	}
	return nil
}

func (x *EnrichResponse) GetEnrichedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnrichedAt
	}
	return nil
}

func (x *EnrichResponse) GetRawDetails() *structpb.Struct {
	if x != nil {
		return x.RawDetails
	}
	return nil
}

type BatchEnrichRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Requests       []*EnrichRequest       `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	MaxConcurrency int32                  `protobuf:"varint,2,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchEnrichRequest) Reset() {
	*x = BatchEnrichRequest{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEnrichRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEnrichRequest) ProtoMessage() {}

func (x *BatchEnrichRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEnrichRequest.ProtoReflect.Descriptor instead.
func (*BatchEnrichRequest) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{13}
}

func (x *BatchEnrichRequest) GetRequests() []*EnrichRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *BatchEnrichRequest) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

type BatchEnrichResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*EnrichResponse      `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	SuccessCount  int32                  `protobuf:"varint,3,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailedCount   int32                  `protobuf:"varint,4,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	Errors        map[string]string      `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEnrichResponse) Reset() {
	*x = BatchEnrichResponse{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEnrichResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEnrichResponse) ProtoMessage() {}

func (x *BatchEnrichResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEnrichResponse.ProtoReflect.Descriptor instead.
func (*BatchEnrichResponse) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{14}
}

func (x *BatchEnrichResponse) GetResponses() []*EnrichResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *BatchEnrichResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *BatchEnrichResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchEnrichResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *BatchEnrichResponse) GetErrors() map[string]string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type GetReputationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Sources       []EnrichmentSource     `protobuf:"varint,3,rep,packed,name=sources,proto3,enum=enrichment.v1.EnrichmentSource" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReputationRequest) Reset() {
	*x = GetReputationRequest{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReputationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReputationRequest) ProtoMessage() {}

func (x *GetReputationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReputationRequest.ProtoReflect.Descriptor instead.
func (*GetReputationRequest) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetReputationRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetReputationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetReputationRequest) GetSources() []EnrichmentSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

type GetReputationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceScores  map[string]float32     `protobuf:"bytes,1,rep,name=source_scores,json=sourceScores,proto3" json:"source_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	Aggregated    *AggregatedScore       `protobuf:"bytes,2,opt,name=aggregated,proto3" json:"aggregated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReputationResponse) Reset() {
	*x = GetReputationResponse{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReputationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReputationResponse) ProtoMessage() {}

func (x *GetReputationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReputationResponse.ProtoReflect.Descriptor instead.
func (*GetReputationResponse) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetReputationResponse) GetSourceScores() map[string]float32 {
	if x != nil {
		return x.SourceScores
	}
	return nil
}

func (x *GetReputationResponse) GetAggregated() *AggregatedScore {
	if x != nil {
		return x.Aggregated
	}
	return nil
}

type StreamEnrichRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Request       *EnrichRequest         `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEnrichRequest) Reset() {
	*x = StreamEnrichRequest{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEnrichRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEnrichRequest) ProtoMessage() {}

func (x *StreamEnrichRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEnrichRequest.ProtoReflect.Descriptor instead.
func (*StreamEnrichRequest) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{17}
}

func (x *StreamEnrichRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StreamEnrichRequest) GetRequest() *EnrichRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type StreamEnrichResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*StreamEnrichResponse_Success
	//	*StreamEnrichResponse_ErrorMessage
	Result        isStreamEnrichResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEnrichResponse) Reset() {
	*x = StreamEnrichResponse{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEnrichResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEnrichResponse) ProtoMessage() {}

func (x *StreamEnrichResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEnrichResponse.ProtoReflect.Descriptor instead.
func (*StreamEnrichResponse) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{18}
}

func (x *StreamEnrichResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StreamEnrichResponse) GetResult() isStreamEnrichResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StreamEnrichResponse) GetSuccess() *EnrichResponse {
	if x != nil {
		if x, ok := x.Result.(*StreamEnrichResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *StreamEnrichResponse) GetErrorMessage() string {
	if x != nil {
		if x, ok := x.Result.(*StreamEnrichResponse_ErrorMessage); ok {
			return x.ErrorMessage
		}
	}
	return ""
}

type isStreamEnrichResponse_Result interface {
	isStreamEnrichResponse_Result()
}

type StreamEnrichResponse_Success struct {
	Success *EnrichResponse `protobuf:"bytes,2,opt,name=success,proto3,oneof"`
}

type StreamEnrichResponse_ErrorMessage struct {
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

func (*StreamEnrichResponse_Success) isStreamEnrichResponse_Result() {}

func (*StreamEnrichResponse_ErrorMessage) isStreamEnrichResponse_Result() {}

type CheckSourceHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []EnrichmentSource     `protobuf:"varint,1,rep,packed,name=sources,proto3,enum=enrichment.v1.EnrichmentSource" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSourceHealthRequest) Reset() {
	*x = CheckSourceHealthRequest{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSourceHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSourceHealthRequest) ProtoMessage() {}

func (x *CheckSourceHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSourceHealthRequest.ProtoReflect.Descriptor instead.
func (*CheckSourceHealthRequest) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{19}
}

func (x *CheckSourceHealthRequest) GetSources() []EnrichmentSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

type CheckSourceHealthResponse struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	HealthStatus   map[string]*SourceHealth `protobuf:"bytes,1,rep,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OverallHealthy bool                     `protobuf:"varint,3,opt,name=overall_healthy,json=overallHealthy,proto3" json:"overall_healthy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckSourceHealthResponse) Reset() {
	*x = CheckSourceHealthResponse{}
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSourceHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSourceHealthResponse) ProtoMessage() {}

func (x *CheckSourceHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSourceHealthResponse.ProtoReflect.Descriptor instead.
func (*CheckSourceHealthResponse) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_service_proto_rawDescGZIP(), []int{20}
}

func (x *CheckSourceHealthResponse) GetHealthStatus() map[string]*SourceHealth {
	if x != nil {
		return x.HealthStatus
	}
	return nil
}

func (x *CheckSourceHealthResponse) GetOverallHealthy() bool {
	if x != nil {
		return x.OverallHealthy
	}
	return false
}

var File_enrichment_v1_enrichment_service_proto protoreflect.FileDescriptor

const file_enrichment_v1_enrichment_service_proto_rawDesc = "" +
	"\n" +
	"&enrichment/v1/enrichment_service.proto\x12\renrichment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1eenrichment/v1/enrichment.proto\"\x83\x01\n" +
	"\rEnrichOptions\x12\x19\n" +
	"\bhas_type\x18\x01 \x01(\tR\ahasType\x122\n" +
	"\x15include_file_metadata\x18\x02 \x01(\bR\x13includeFileMetadata\x12#\n" +
	"\rforce_refresh\x18\x03 \x01(\bR\fforceRefresh\"\x85\x01\n" +
	"\x0fEnrichIPRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x129\n" +
	"\asources\x18\x02 \x03(\x0e2\x1f.enrichment.v1.EnrichmentSourceR\asources\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"\xfd\x02\n" +
	"\x10EnrichIPResponse\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12F\n" +
	"\aresults\x18\x02 \x03(\v2,.enrichment.v1.EnrichIPResponse.ResultsEntryR\aresults\x12>\n" +
	"\n" +
	"aggregated\x18\x03 \x01(\v2\x1e.enrichment.v1.AggregatedScoreR\n" +
	"aggregated\x128\n" +
	"\aip_data\x18\x04 \x01(\v2\x1f.enrichment.v1.IPEnrichmentDataR\x06ipData\x12;\n" +
	"\venriched_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enrichedAt\x1aZ\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.enrichment.v1.ThreatIntelDataR\x05value:\x028\x01\"\x91\x01\n" +
	"\x13EnrichDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x129\n" +
	"\asources\x18\x02 \x03(\x0e2\x1f.enrichment.v1.EnrichmentSourceR\asources\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"\x99\x03\n" +
	"\x14EnrichDomainResponse\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12J\n" +
	"\aresults\x18\x02 \x03(\v20.enrichment.v1.EnrichDomainResponse.ResultsEntryR\aresults\x12>\n" +
	"\n" +
	"aggregated\x18\x03 \x01(\v2\x1e.enrichment.v1.AggregatedScoreR\n" +
	"aggregated\x12D\n" +
	"\vdomain_data\x18\x04 \x01(\v2#.enrichment.v1.DomainEnrichmentDataR\n" +
	"domainData\x12;\n" +
	"\venriched_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enrichedAt\x1aZ\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.enrichment.v1.ThreatIntelDataR\x05value:\x028\x01\"\xc3\x01\n" +
	"\x11EnrichHashRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x126\n" +
	"\aoptions\x18\x02 \x01(\v2\x1c.enrichment.v1.EnrichOptionsR\aoptions\x129\n" +
	"\asources\x18\x03 \x03(\x0e2\x1f.enrichment.v1.EnrichmentSourceR\asources\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\"\x8b\x03\n" +
	"\x12EnrichHashResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12H\n" +
	"\aresults\x18\x02 \x03(\v2..enrichment.v1.EnrichHashResponse.ResultsEntryR\aresults\x12>\n" +
	"\n" +
	"aggregated\x18\x03 \x01(\v2\x1e.enrichment.v1.AggregatedScoreR\n" +
	"aggregated\x12>\n" +
	"\thash_data\x18\x04 \x01(\v2!.enrichment.v1.HashEnrichmentDataR\bhashData\x12;\n" +
	"\venriched_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enrichedAt\x1aZ\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.enrichment.v1.ThreatIntelDataR\x05value:\x028\x01\"\x88\x01\n" +
	"\x10EnrichURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x129\n" +
	"\asources\x18\x02 \x03(\x0e2\x1f.enrichment.v1.EnrichmentSourceR\asources\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"\x84\x03\n" +
	"\x11EnrichURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12G\n" +
	"\aresults\x18\x02 \x03(\v2-.enrichment.v1.EnrichURLResponse.ResultsEntryR\aresults\x12>\n" +
	"\n" +
	"aggregated\x18\x03 \x01(\v2\x1e.enrichment.v1.AggregatedScoreR\n" +
	"aggregated\x12;\n" +
	"\burl_data\x18\x04 \x01(\v2 .enrichment.v1.URLEnrichmentDataR\aurlData\x12;\n" +
	"\venriched_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enrichedAt\x1aZ\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.enrichment.v1.ThreatIntelDataR\x05value:\x028\x01\"\x98\x01\n" +
	"\x15EnrichFilePathRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x129\n" +
	"\asources\x18\x02 \x03(\x0e2\x1f.enrichment.v1.EnrichmentSourceR\asources\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"\xa9\x03\n" +
	"\x16EnrichFilePathResponse\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12L\n" +
	"\aresults\x18\x02 \x03(\v22.enrichment.v1.EnrichFilePathResponse.ResultsEntryR\aresults\x12>\n" +
	"\n" +
	"aggregated\x18\x03 \x01(\v2\x1e.enrichment.v1.AggregatedScoreR\n" +
	"aggregated\x12K\n" +
	"\x0efile_path_data\x18\x04 \x01(\v2%.enrichment.v1.FilePathEnrichmentDataR\ffilePathData\x12;\n" +
	"\venriched_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enrichedAt\x1aZ\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.enrichment.v1.ThreatIntelDataR\x05value:\x028\x01\"\xd5\x01\n" +
	"\rEnrichRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x129\n" +
	"\asources\x18\x03 \x03(\x0e2\x1f.enrichment.v1.EnrichmentSourceR\asources\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x126\n" +
	"\aoptions\x18\x05 \x01(\v2\x1c.enrichment.v1.EnrichOptionsR\aoptions\"\x93\x03\n" +
	"\x0eEnrichResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12D\n" +
	"\aresults\x18\x03 \x03(\v2*.enrichment.v1.EnrichResponse.ResultsEntryR\aresults\x12>\n" +
	"\n" +
	"aggregated\x18\x04 \x01(\v2\x1e.enrichment.v1.AggregatedScoreR\n" +
	"aggregated\x12;\n" +
	"\venriched_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enrichedAt\x128\n" +
	"\vraw_details\x18\x06 \x01(\v2\x17.google.protobuf.StructR\n" +
	"rawDetails\x1aZ\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.enrichment.v1.ThreatIntelDataR\x05value:\x028\x01\"w\n" +
	"\x12BatchEnrichRequest\x128\n" +
	"\brequests\x18\x01 \x03(\v2\x1c.enrichment.v1.EnrichRequestR\brequests\x12'\n" +
	"\x0fmax_concurrency\x18\x02 \x01(\x05R\x0emaxConcurrency\"\xbe\x02\n" +
	"\x13BatchEnrichResponse\x12;\n" +
	"\tresponses\x18\x01 \x03(\v2\x1d.enrichment.v1.EnrichResponseR\tresponses\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12#\n" +
	"\rsuccess_count\x18\x03 \x01(\x05R\fsuccessCount\x12!\n" +
	"\ffailed_count\x18\x04 \x01(\x05R\vfailedCount\x12F\n" +
	"\x06errors\x18\x05 \x03(\v2..enrichment.v1.BatchEnrichResponse.ErrorsEntryR\x06errors\x1a9\n" +
	"\vErrorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\x14GetReputationRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x129\n" +
	"\asources\x18\x03 \x03(\x0e2\x1f.enrichment.v1.EnrichmentSourceR\asources\"\xf5\x01\n" +
	"\x15GetReputationResponse\x12[\n" +
	"\rsource_scores\x18\x01 \x03(\v26.enrichment.v1.GetReputationResponse.SourceScoresEntryR\fsourceScores\x12>\n" +
	"\n" +
	"aggregated\x18\x02 \x01(\v2\x1e.enrichment.v1.AggregatedScoreR\n" +
	"aggregated\x1a?\n" +
	"\x11SourceScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"l\n" +
	"\x13StreamEnrichRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x126\n" +
	"\arequest\x18\x02 \x01(\v2\x1c.enrichment.v1.EnrichRequestR\arequest\"\xa1\x01\n" +
	"\x14StreamEnrichResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x129\n" +
	"\asuccess\x18\x02 \x01(\v2\x1d.enrichment.v1.EnrichResponseH\x00R\asuccess\x12%\n" +
	"\rerror_message\x18\x03 \x01(\tH\x00R\ferrorMessageB\b\n" +
	"\x06result\"U\n" +
	"\x18CheckSourceHealthRequest\x129\n" +
	"\asources\x18\x01 \x03(\x0e2\x1f.enrichment.v1.EnrichmentSourceR\asources\"\x83\x02\n" +
	"\x19CheckSourceHealthResponse\x12_\n" +
	"\rhealth_status\x18\x01 \x03(\v2:.enrichment.v1.CheckSourceHealthResponse.HealthStatusEntryR\fhealthStatus\x12'\n" +
	"\x0foverall_healthy\x18\x03 \x01(\bR\x0eoverallHealthy\x1a\\\n" +
	"\x11HealthStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.enrichment.v1.SourceHealthR\x05value:\x028\x012\xf9\x06\n" +
	"\x11EnrichmentService\x12K\n" +
	"\bEnrichIP\x12\x1e.enrichment.v1.EnrichIPRequest\x1a\x1f.enrichment.v1.EnrichIPResponse\x12W\n" +
	"\fEnrichDomain\x12\".enrichment.v1.EnrichDomainRequest\x1a#.enrichment.v1.EnrichDomainResponse\x12Q\n" +
	"\n" +
	"EnrichHash\x12 .enrichment.v1.EnrichHashRequest\x1a!.enrichment.v1.EnrichHashResponse\x12N\n" +
	"\tEnrichURL\x12\x1f.enrichment.v1.EnrichURLRequest\x1a .enrichment.v1.EnrichURLResponse\x12]\n" +
	"\x0eEnrichFilePath\x12$.enrichment.v1.EnrichFilePathRequest\x1a%.enrichment.v1.EnrichFilePathResponse\x12E\n" +
	"\x06Enrich\x12\x1c.enrichment.v1.EnrichRequest\x1a\x1d.enrichment.v1.EnrichResponse\x12T\n" +
	"\vEnrichBatch\x12!.enrichment.v1.BatchEnrichRequest\x1a\".enrichment.v1.BatchEnrichResponse\x12Z\n" +
	"\rGetReputation\x12#.enrichment.v1.GetReputationRequest\x1a$.enrichment.v1.GetReputationResponse\x12[\n" +
	"\fStreamEnrich\x12\".enrichment.v1.StreamEnrichRequest\x1a#.enrichment.v1.StreamEnrichResponse(\x010\x01\x12f\n" +
	"\x11CheckSourceHealth\x12'.enrichment.v1.CheckSourceHealthRequest\x1a(.enrichment.v1.CheckSourceHealthResponseBPZNgithub.com/DgHnG36/ioc_enrichment_service/shared/go/enrichment/v1;enrichmentv1b\x06proto3"

var (
	file_enrichment_v1_enrichment_service_proto_rawDescOnce sync.Once
	file_enrichment_v1_enrichment_service_proto_rawDescData []byte
)

func file_enrichment_v1_enrichment_service_proto_rawDescGZIP() []byte {
	file_enrichment_v1_enrichment_service_proto_rawDescOnce.Do(func() {
		file_enrichment_v1_enrichment_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enrichment_v1_enrichment_service_proto_rawDesc), len(file_enrichment_v1_enrichment_service_proto_rawDesc)))
	})
	return file_enrichment_v1_enrichment_service_proto_rawDescData
}

var file_enrichment_v1_enrichment_service_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_enrichment_v1_enrichment_service_proto_goTypes = []any{
	(*EnrichOptions)(nil),             // 0: enrichment.v1.EnrichOptions
	(*EnrichIPRequest)(nil),           // 1: enrichment.v1.EnrichIPRequest
	(*EnrichIPResponse)(nil),          // 2: enrichment.v1.EnrichIPResponse
	(*EnrichDomainRequest)(nil),       // 3: enrichment.v1.EnrichDomainRequest
	(*EnrichDomainResponse)(nil),      // 4: enrichment.v1.EnrichDomainResponse
	(*EnrichHashRequest)(nil),         // 5: enrichment.v1.EnrichHashRequest
	(*EnrichHashResponse)(nil),        // 6: enrichment.v1.EnrichHashResponse
	(*EnrichURLRequest)(nil),          // 7: enrichment.v1.EnrichURLRequest
	(*EnrichURLResponse)(nil),         // 8: enrichment.v1.EnrichURLResponse
	(*EnrichFilePathRequest)(nil),     // 9: enrichment.v1.EnrichFilePathRequest
	(*EnrichFilePathResponse)(nil),    // 10: enrichment.v1.EnrichFilePathResponse
	(*EnrichRequest)(nil),             // 11: enrichment.v1.EnrichRequest
	(*EnrichResponse)(nil),            // 12: enrichment.v1.EnrichResponse
	(*BatchEnrichRequest)(nil),        // 13: enrichment.v1.BatchEnrichRequest
	(*BatchEnrichResponse)(nil),       // 14: enrichment.v1.BatchEnrichResponse
	(*GetReputationRequest)(nil),      // 15: enrichment.v1.GetReputationRequest
	(*GetReputationResponse)(nil),     // 16: enrichment.v1.GetReputationResponse
	(*StreamEnrichRequest)(nil),       // 17: enrichment.v1.StreamEnrichRequest
	(*StreamEnrichResponse)(nil),      // 18: enrichment.v1.StreamEnrichResponse
	(*CheckSourceHealthRequest)(nil),  // 19: enrichment.v1.CheckSourceHealthRequest
	(*CheckSourceHealthResponse)(nil), // 20: enrichment.v1.CheckSourceHealthResponse
	nil,                               // 21: enrichment.v1.EnrichIPResponse.ResultsEntry
	nil,                               // 22: enrichment.v1.EnrichDomainResponse.ResultsEntry
	nil,                               // 23: enrichment.v1.EnrichHashResponse.ResultsEntry
	nil,                               // 24: enrichment.v1.EnrichURLResponse.ResultsEntry
	nil,                               // 25: enrichment.v1.EnrichFilePathResponse.ResultsEntry
	nil,                               // 26: enrichment.v1.EnrichResponse.ResultsEntry
	nil,                               // 27: enrichment.v1.BatchEnrichResponse.ErrorsEntry
	nil,                               // 28: enrichment.v1.GetReputationResponse.SourceScoresEntry
	nil,                               // 29: enrichment.v1.CheckSourceHealthResponse.HealthStatusEntry
	(EnrichmentSource)(0),             // 30: enrichment.v1.EnrichmentSource
	(*AggregatedScore)(nil),           // 31: enrichment.v1.AggregatedScore
	(*IPEnrichmentData)(nil),          // 32: enrichment.v1.IPEnrichmentData
	(*timestamppb.Timestamp)(nil),     // 33: google.protobuf.Timestamp
	(*DomainEnrichmentData)(nil),      // 34: enrichment.v1.DomainEnrichmentData
	(*HashEnrichmentData)(nil),        // 35: enrichment.v1.HashEnrichmentData
	(*URLEnrichmentData)(nil),         // 36: enrichment.v1.URLEnrichmentData
	(*FilePathEnrichmentData)(nil),    // 37: enrichment.v1.FilePathEnrichmentData
	(*structpb.Struct)(nil),           // 38: google.protobuf.Struct
	(*ThreatIntelData)(nil),           // 39: enrichment.v1.ThreatIntelData
	(*SourceHealth)(nil),              // 40: enrichment.v1.SourceHealth
}
var file_enrichment_v1_enrichment_service_proto_depIdxs = []int32{
	30, // 0: enrichment.v1.EnrichIPRequest.sources:type_name -> enrichment.v1.EnrichmentSource
	21, // 1: enrichment.v1.EnrichIPResponse.results:type_name -> enrichment.v1.EnrichIPResponse.ResultsEntry
	31, // 2: enrichment.v1.EnrichIPResponse.aggregated:type_name -> enrichment.v1.AggregatedScore
	32, // 3: enrichment.v1.EnrichIPResponse.ip_data:type_name -> enrichment.v1.IPEnrichmentData
	33, // 4: enrichment.v1.EnrichIPResponse.enriched_at:type_name -> google.protobuf.Timestamp
	30, // 5: enrichment.v1.EnrichDomainRequest.sources:type_name -> enrichment.v1.EnrichmentSource
	22, // 6: enrichment.v1.EnrichDomainResponse.results:type_name -> enrichment.v1.EnrichDomainResponse.ResultsEntry
	31, // 7: enrichment.v1.EnrichDomainResponse.aggregated:type_name -> enrichment.v1.AggregatedScore
	34, // 8: enrichment.v1.EnrichDomainResponse.domain_data:type_name -> enrichment.v1.DomainEnrichmentData
	33, // 9: enrichment.v1.EnrichDomainResponse.enriched_at:type_name -> google.protobuf.Timestamp
	0,  // 10: enrichment.v1.EnrichHashRequest.options:type_name -> enrichment.v1.EnrichOptions
	30, // 11: enrichment.v1.EnrichHashRequest.sources:type_name -> enrichment.v1.EnrichmentSource
	23, // 12: enrichment.v1.EnrichHashResponse.results:type_name -> enrichment.v1.EnrichHashResponse.ResultsEntry
	31, // 13: enrichment.v1.EnrichHashResponse.aggregated:type_name -> enrichment.v1.AggregatedScore
	35, // 14: enrichment.v1.EnrichHashResponse.hash_data:type_name -> enrichment.v1.HashEnrichmentData
	33, // 15: enrichment.v1.EnrichHashResponse.enriched_at:type_name -> google.protobuf.Timestamp
	30, // 16: enrichment.v1.EnrichURLRequest.sources:type_name -> enrichment.v1.EnrichmentSource
	24, // 17: enrichment.v1.EnrichURLResponse.results:type_name -> enrichment.v1.EnrichURLResponse.ResultsEntry
	31, // 18: enrichment.v1.EnrichURLResponse.aggregated:type_name -> enrichment.v1.AggregatedScore
	36, // 19: enrichment.v1.EnrichURLResponse.url_data:type_name -> enrichment.v1.URLEnrichmentData
	33, // 20: enrichment.v1.EnrichURLResponse.enriched_at:type_name -> google.protobuf.Timestamp
	30, // 21: enrichment.v1.EnrichFilePathRequest.sources:type_name -> enrichment.v1.EnrichmentSource
	25, // 22: enrichment.v1.EnrichFilePathResponse.results:type_name -> enrichment.v1.EnrichFilePathResponse.ResultsEntry
	31, // 23: enrichment.v1.EnrichFilePathResponse.aggregated:type_name -> enrichment.v1.AggregatedScore
	37, // 24: enrichment.v1.EnrichFilePathResponse.file_path_data:type_name -> enrichment.v1.FilePathEnrichmentData
	33, // 25: enrichment.v1.EnrichFilePathResponse.enriched_at:type_name -> google.protobuf.Timestamp
	30, // 26: enrichment.v1.EnrichRequest.sources:type_name -> enrichment.v1.EnrichmentSource
	0,  // 27: enrichment.v1.EnrichRequest.options:type_name -> enrichment.v1.EnrichOptions
	26, // 28: enrichment.v1.EnrichResponse.results:type_name -> enrichment.v1.EnrichResponse.ResultsEntry
	31, // 29: enrichment.v1.EnrichResponse.aggregated:type_name -> enrichment.v1.AggregatedScore
	33, // 30: enrichment.v1.EnrichResponse.enriched_at:type_name -> google.protobuf.Timestamp
	38, // 31: enrichment.v1.EnrichResponse.raw_details:type_name -> google.protobuf.Struct
	11, // 32: enrichment.v1.BatchEnrichRequest.requests:type_name -> enrichment.v1.EnrichRequest
	12, // 33: enrichment.v1.BatchEnrichResponse.responses:type_name -> enrichment.v1.EnrichResponse
	27, // 34: enrichment.v1.BatchEnrichResponse.errors:type_name -> enrichment.v1.BatchEnrichResponse.ErrorsEntry
	30, // 35: enrichment.v1.GetReputationRequest.sources:type_name -> enrichment.v1.EnrichmentSource
	28, // 36: enrichment.v1.GetReputationResponse.source_scores:type_name -> enrichment.v1.GetReputationResponse.SourceScoresEntry
	31, // 37: enrichment.v1.GetReputationResponse.aggregated:type_name -> enrichment.v1.AggregatedScore
	11, // 38: enrichment.v1.StreamEnrichRequest.request:type_name -> enrichment.v1.EnrichRequest
	12, // 39: enrichment.v1.StreamEnrichResponse.success:type_name -> enrichment.v1.EnrichResponse
	30, // 40: enrichment.v1.CheckSourceHealthRequest.sources:type_name -> enrichment.v1.EnrichmentSource
	29, // 41: enrichment.v1.CheckSourceHealthResponse.health_status:type_name -> enrichment.v1.CheckSourceHealthResponse.HealthStatusEntry
	39, // 42: enrichment.v1.EnrichIPResponse.ResultsEntry.value:type_name -> enrichment.v1.ThreatIntelData
	39, // 43: enrichment.v1.EnrichDomainResponse.ResultsEntry.value:type_name -> enrichment.v1.ThreatIntelData
	39, // 44: enrichment.v1.EnrichHashResponse.ResultsEntry.value:type_name -> enrichment.v1.ThreatIntelData
	39, // 45: enrichment.v1.EnrichURLResponse.ResultsEntry.value:type_name -> enrichment.v1.ThreatIntelData
	39, // 46: enrichment.v1.EnrichFilePathResponse.ResultsEntry.value:type_name -> enrichment.v1.ThreatIntelData
	39, // 47: enrichment.v1.EnrichResponse.ResultsEntry.value:type_name -> enrichment.v1.ThreatIntelData
	40, // 48: enrichment.v1.CheckSourceHealthResponse.HealthStatusEntry.value:type_name -> enrichment.v1.SourceHealth
	1,  // 49: enrichment.v1.EnrichmentService.EnrichIP:input_type -> enrichment.v1.EnrichIPRequest
	3,  // 50: enrichment.v1.EnrichmentService.EnrichDomain:input_type -> enrichment.v1.EnrichDomainRequest
	5,  // 51: enrichment.v1.EnrichmentService.EnrichHash:input_type -> enrichment.v1.EnrichHashRequest
	7,  // 52: enrichment.v1.EnrichmentService.EnrichURL:input_type -> enrichment.v1.EnrichURLRequest
	9,  // 53: enrichment.v1.EnrichmentService.EnrichFilePath:input_type -> enrichment.v1.EnrichFilePathRequest
	11, // 54: enrichment.v1.EnrichmentService.Enrich:input_type -> enrichment.v1.EnrichRequest
	13, // 55: enrichment.v1.EnrichmentService.EnrichBatch:input_type -> enrichment.v1.BatchEnrichRequest
	15, // 56: enrichment.v1.EnrichmentService.GetReputation:input_type -> enrichment.v1.GetReputationRequest
	17, // 57: enrichment.v1.EnrichmentService.StreamEnrich:input_type -> enrichment.v1.StreamEnrichRequest
	19, // 58: enrichment.v1.EnrichmentService.CheckSourceHealth:input_type -> enrichment.v1.CheckSourceHealthRequest
	2,  // 59: enrichment.v1.EnrichmentService.EnrichIP:output_type -> enrichment.v1.EnrichIPResponse
	4,  // 60: enrichment.v1.EnrichmentService.EnrichDomain:output_type -> enrichment.v1.EnrichDomainResponse
	6,  // 61: enrichment.v1.EnrichmentService.EnrichHash:output_type -> enrichment.v1.EnrichHashResponse
	8,  // 62: enrichment.v1.EnrichmentService.EnrichURL:output_type -> enrichment.v1.EnrichURLResponse
	10, // 63: enrichment.v1.EnrichmentService.EnrichFilePath:output_type -> enrichment.v1.EnrichFilePathResponse
	12, // 64: enrichment.v1.EnrichmentService.Enrich:output_type -> enrichment.v1.EnrichResponse
	14, // 65: enrichment.v1.EnrichmentService.EnrichBatch:output_type -> enrichment.v1.BatchEnrichResponse
	16, // 66: enrichment.v1.EnrichmentService.GetReputation:output_type -> enrichment.v1.GetReputationResponse
	18, // 67: enrichment.v1.EnrichmentService.StreamEnrich:output_type -> enrichment.v1.StreamEnrichResponse
	20, // 68: enrichment.v1.EnrichmentService.CheckSourceHealth:output_type -> enrichment.v1.CheckSourceHealthResponse
	59, // [59:69] is the sub-list for method output_type
	49, // [49:59] is the sub-list for method input_type
	49, // [49:49] is the sub-list for extension type_name
	49, // [49:49] is the sub-list for extension extendee
	0,  // [0:49] is the sub-list for field type_name
}

func init() { file_enrichment_v1_enrichment_service_proto_init() }
func file_enrichment_v1_enrichment_service_proto_init() {
	if File_enrichment_v1_enrichment_service_proto != nil {
		return
	}
	file_enrichment_v1_enrichment_proto_init()
	file_enrichment_v1_enrichment_service_proto_msgTypes[18].OneofWrappers = []any{
		(*StreamEnrichResponse_Success)(nil),
		(*StreamEnrichResponse_ErrorMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enrichment_v1_enrichment_service_proto_rawDesc), len(file_enrichment_v1_enrichment_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_enrichment_v1_enrichment_service_proto_goTypes,
		DependencyIndexes: file_enrichment_v1_enrichment_service_proto_depIdxs,
		MessageInfos:      file_enrichment_v1_enrichment_service_proto_msgTypes,
	}.Build()
	File_enrichment_v1_enrichment_service_proto = out.File
	file_enrichment_v1_enrichment_service_proto_goTypes = nil
	file_enrichment_v1_enrichment_service_proto_depIdxs = nil
}
