// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: enrichment/v1/enrichment_service.proto

package enrichmentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnrichmentService_EnrichIP_FullMethodName          = "/enrichment.v1.EnrichmentService/EnrichIP"
	EnrichmentService_EnrichDomain_FullMethodName      = "/enrichment.v1.EnrichmentService/EnrichDomain"
	EnrichmentService_EnrichHash_FullMethodName        = "/enrichment.v1.EnrichmentService/EnrichHash"
	EnrichmentService_EnrichURL_FullMethodName         = "/enrichment.v1.EnrichmentService/EnrichURL"
	EnrichmentService_EnrichFilePath_FullMethodName    = "/enrichment.v1.EnrichmentService/EnrichFilePath"
	EnrichmentService_Enrich_FullMethodName            = "/enrichment.v1.EnrichmentService/Enrich"
	EnrichmentService_EnrichBatch_FullMethodName       = "/enrichment.v1.EnrichmentService/EnrichBatch"
	EnrichmentService_GetReputation_FullMethodName     = "/enrichment.v1.EnrichmentService/GetReputation"
	EnrichmentService_StreamEnrich_FullMethodName      = "/enrichment.v1.EnrichmentService/StreamEnrich"
	EnrichmentService_CheckSourceHealth_FullMethodName = "/enrichment.v1.EnrichmentService/CheckSourceHealth"
)

// EnrichmentServiceClient is the client API for EnrichmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnrichmentServiceClient interface {
	EnrichIP(ctx context.Context, in *EnrichIPRequest, opts ...grpc.CallOption) (*EnrichIPResponse, error)
	EnrichDomain(ctx context.Context, in *EnrichDomainRequest, opts ...grpc.CallOption) (*EnrichDomainResponse, error)
	EnrichHash(ctx context.Context, in *EnrichHashRequest, opts ...grpc.CallOption) (*EnrichHashResponse, error)
	EnrichURL(ctx context.Context, in *EnrichURLRequest, opts ...grpc.CallOption) (*EnrichURLResponse, error)
	EnrichFilePath(ctx context.Context, in *EnrichFilePathRequest, opts ...grpc.CallOption) (*EnrichFilePathResponse, error)
	Enrich(ctx context.Context, in *EnrichRequest, opts ...grpc.CallOption) (*EnrichResponse, error)
	EnrichBatch(ctx context.Context, in *BatchEnrichRequest, opts ...grpc.CallOption) (*BatchEnrichResponse, error)
	GetReputation(ctx context.Context, in *GetReputationRequest, opts ...grpc.CallOption) (*GetReputationResponse, error)
	StreamEnrich(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamEnrichRequest, StreamEnrichResponse], error)
	CheckSourceHealth(ctx context.Context, in *CheckSourceHealthRequest, opts ...grpc.CallOption) (*CheckSourceHealthResponse, error)
}

type enrichmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnrichmentServiceClient(cc grpc.ClientConnInterface) EnrichmentServiceClient {
	return &enrichmentServiceClient{cc}
}

func (c *enrichmentServiceClient) EnrichIP(ctx context.Context, in *EnrichIPRequest, opts ...grpc.CallOption) (*EnrichIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichIPResponse)
	err := c.cc.Invoke(ctx, EnrichmentService_EnrichIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrichmentServiceClient) EnrichDomain(ctx context.Context, in *EnrichDomainRequest, opts ...grpc.CallOption) (*EnrichDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichDomainResponse)
	err := c.cc.Invoke(ctx, EnrichmentService_EnrichDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrichmentServiceClient) EnrichHash(ctx context.Context, in *EnrichHashRequest, opts ...grpc.CallOption) (*EnrichHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichHashResponse)
	err := c.cc.Invoke(ctx, EnrichmentService_EnrichHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrichmentServiceClient) EnrichURL(ctx context.Context, in *EnrichURLRequest, opts ...grpc.CallOption) (*EnrichURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichURLResponse)
	err := c.cc.Invoke(ctx, EnrichmentService_EnrichURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrichmentServiceClient) EnrichFilePath(ctx context.Context, in *EnrichFilePathRequest, opts ...grpc.CallOption) (*EnrichFilePathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichFilePathResponse)
	err := c.cc.Invoke(ctx, EnrichmentService_EnrichFilePath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrichmentServiceClient) Enrich(ctx context.Context, in *EnrichRequest, opts ...grpc.CallOption) (*EnrichResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichResponse)
	err := c.cc.Invoke(ctx, EnrichmentService_Enrich_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrichmentServiceClient) EnrichBatch(ctx context.Context, in *BatchEnrichRequest, opts ...grpc.CallOption) (*BatchEnrichResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchEnrichResponse)
	err := c.cc.Invoke(ctx, EnrichmentService_EnrichBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrichmentServiceClient) GetReputation(ctx context.Context, in *GetReputationRequest, opts ...grpc.CallOption) (*GetReputationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReputationResponse)
	err := c.cc.Invoke(ctx, EnrichmentService_GetReputation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrichmentServiceClient) StreamEnrich(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamEnrichRequest, StreamEnrichResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EnrichmentService_ServiceDesc.Streams[0], EnrichmentService_StreamEnrich_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEnrichRequest, StreamEnrichResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EnrichmentService_StreamEnrichClient = grpc.BidiStreamingClient[StreamEnrichRequest, StreamEnrichResponse]

func (c *enrichmentServiceClient) CheckSourceHealth(ctx context.Context, in *CheckSourceHealthRequest, opts ...grpc.CallOption) (*CheckSourceHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckSourceHealthResponse)
	err := c.cc.Invoke(ctx, EnrichmentService_CheckSourceHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnrichmentServiceServer is the server API for EnrichmentService service.
// All implementations must embed UnimplementedEnrichmentServiceServer
// for forward compatibility.
type EnrichmentServiceServer interface {
	EnrichIP(context.Context, *EnrichIPRequest) (*EnrichIPResponse, error)
	EnrichDomain(context.Context, *EnrichDomainRequest) (*EnrichDomainResponse, error)
	EnrichHash(context.Context, *EnrichHashRequest) (*EnrichHashResponse, error)
	EnrichURL(context.Context, *EnrichURLRequest) (*EnrichURLResponse, error)
	EnrichFilePath(context.Context, *EnrichFilePathRequest) (*EnrichFilePathResponse, error)
	Enrich(context.Context, *EnrichRequest) (*EnrichResponse, error)
	EnrichBatch(context.Context, *BatchEnrichRequest) (*BatchEnrichResponse, error)
	GetReputation(context.Context, *GetReputationRequest) (*GetReputationResponse, error)
	StreamEnrich(grpc.BidiStreamingServer[StreamEnrichRequest, StreamEnrichResponse]) error
	CheckSourceHealth(context.Context, *CheckSourceHealthRequest) (*CheckSourceHealthResponse, error)
	mustEmbedUnimplementedEnrichmentServiceServer()
}

// UnimplementedEnrichmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnrichmentServiceServer struct{}

func (UnimplementedEnrichmentServiceServer) EnrichIP(context.Context, *EnrichIPRequest) (*EnrichIPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrichIP not implemented")
}
func (UnimplementedEnrichmentServiceServer) EnrichDomain(context.Context, *EnrichDomainRequest) (*EnrichDomainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrichDomain not implemented")
}
func (UnimplementedEnrichmentServiceServer) EnrichHash(context.Context, *EnrichHashRequest) (*EnrichHashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrichHash not implemented")
}
func (UnimplementedEnrichmentServiceServer) EnrichURL(context.Context, *EnrichURLRequest) (*EnrichURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrichURL not implemented")
}
func (UnimplementedEnrichmentServiceServer) EnrichFilePath(context.Context, *EnrichFilePathRequest) (*EnrichFilePathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrichFilePath not implemented")
}
func (UnimplementedEnrichmentServiceServer) Enrich(context.Context, *EnrichRequest) (*EnrichResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enrich not implemented")
}
func (UnimplementedEnrichmentServiceServer) EnrichBatch(context.Context, *BatchEnrichRequest) (*BatchEnrichResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrichBatch not implemented")
}
func (UnimplementedEnrichmentServiceServer) GetReputation(context.Context, *GetReputationRequest) (*GetReputationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReputation not implemented")
}
func (UnimplementedEnrichmentServiceServer) StreamEnrich(grpc.BidiStreamingServer[StreamEnrichRequest, StreamEnrichResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamEnrich not implemented")
}
func (UnimplementedEnrichmentServiceServer) CheckSourceHealth(context.Context, *CheckSourceHealthRequest) (*CheckSourceHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckSourceHealth not implemented")
}
func (UnimplementedEnrichmentServiceServer) mustEmbedUnimplementedEnrichmentServiceServer() {}
func (UnimplementedEnrichmentServiceServer) testEmbeddedByValue()                           {}

// UnsafeEnrichmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnrichmentServiceServer will
// result in compilation errors.
type UnsafeEnrichmentServiceServer interface {
	mustEmbedUnimplementedEnrichmentServiceServer()
}

func RegisterEnrichmentServiceServer(s grpc.ServiceRegistrar, srv EnrichmentServiceServer) {
	// If the following call panics, it indicates UnimplementedEnrichmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnrichmentService_ServiceDesc, srv)
}

func _EnrichmentService_EnrichIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentServiceServer).EnrichIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrichmentService_EnrichIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentServiceServer).EnrichIP(ctx, req.(*EnrichIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrichmentService_EnrichDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentServiceServer).EnrichDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrichmentService_EnrichDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentServiceServer).EnrichDomain(ctx, req.(*EnrichDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrichmentService_EnrichHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentServiceServer).EnrichHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrichmentService_EnrichHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentServiceServer).EnrichHash(ctx, req.(*EnrichHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrichmentService_EnrichURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentServiceServer).EnrichURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrichmentService_EnrichURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentServiceServer).EnrichURL(ctx, req.(*EnrichURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrichmentService_EnrichFilePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichFilePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentServiceServer).EnrichFilePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrichmentService_EnrichFilePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentServiceServer).EnrichFilePath(ctx, req.(*EnrichFilePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrichmentService_Enrich_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentServiceServer).Enrich(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrichmentService_Enrich_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentServiceServer).Enrich(ctx, req.(*EnrichRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrichmentService_EnrichBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchEnrichRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentServiceServer).EnrichBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrichmentService_EnrichBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentServiceServer).EnrichBatch(ctx, req.(*BatchEnrichRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrichmentService_GetReputation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReputationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentServiceServer).GetReputation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrichmentService_GetReputation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentServiceServer).GetReputation(ctx, req.(*GetReputationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrichmentService_StreamEnrich_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EnrichmentServiceServer).StreamEnrich(&grpc.GenericServerStream[StreamEnrichRequest, StreamEnrichResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EnrichmentService_StreamEnrichServer = grpc.BidiStreamingServer[StreamEnrichRequest, StreamEnrichResponse]

func _EnrichmentService_CheckSourceHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSourceHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentServiceServer).CheckSourceHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrichmentService_CheckSourceHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentServiceServer).CheckSourceHealth(ctx, req.(*CheckSourceHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnrichmentService_ServiceDesc is the grpc.ServiceDesc for EnrichmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnrichmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "enrichment.v1.EnrichmentService",
	HandlerType: (*EnrichmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnrichIP",
			Handler:    _EnrichmentService_EnrichIP_Handler,
		},
		{
			MethodName: "EnrichDomain",
			Handler:    _EnrichmentService_EnrichDomain_Handler,
		},
		{
			MethodName: "EnrichHash",
			Handler:    _EnrichmentService_EnrichHash_Handler,
		},
		{
			MethodName: "EnrichURL",
			Handler:    _EnrichmentService_EnrichURL_Handler,
		},
		{
			MethodName: "EnrichFilePath",
			Handler:    _EnrichmentService_EnrichFilePath_Handler,
		},
		{
			MethodName: "Enrich",
			Handler:    _EnrichmentService_Enrich_Handler,
		},
		{
			MethodName: "EnrichBatch",
			Handler:    _EnrichmentService_EnrichBatch_Handler,
		},
		{
			MethodName: "GetReputation",
			Handler:    _EnrichmentService_GetReputation_Handler,
		},
		{
			MethodName: "CheckSourceHealth",
			Handler:    _EnrichmentService_CheckSourceHealth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEnrich",
			Handler:       _EnrichmentService_StreamEnrich_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "enrichment/v1/enrichment_service.proto",
}
