// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: enrichment/v1/enrichment.proto

package enrichmentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Verdict int32

const (
	Verdict_VERDICT_UNSPECIFIED    Verdict = 0
	Verdict_VERDICT_BENIGN         Verdict = 1
	Verdict_VERDICT_SUSPICIOUS     Verdict = 2
	Verdict_VERDICT_MALICIOUS      Verdict = 3
	Verdict_VERDICT_FALSE_POSITIVE Verdict = 4
	Verdict_VERDICT_UNKNOWN        Verdict = 5
)

// Enum value maps for Verdict.
var (
	Verdict_name = map[int32]string{
		0: "VERDICT_UNSPECIFIED",
		1: "VERDICT_BENIGN",
		2: "VERDICT_SUSPICIOUS",
		3: "VERDICT_MALICIOUS",
		4: "VERDICT_FALSE_POSITIVE",
		5: "VERDICT_UNKNOWN",
	}
	Verdict_value = map[string]int32{
		"VERDICT_UNSPECIFIED":    0,
		"VERDICT_BENIGN":         1,
		"VERDICT_SUSPICIOUS":     2,
		"VERDICT_MALICIOUS":      3,
		"VERDICT_FALSE_POSITIVE": 4,
		"VERDICT_UNKNOWN":        5,
	}
)

func (x Verdict) Enum() *Verdict {
	p := new(Verdict)
	*p = x
	return p
}

func (x Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_enrichment_v1_enrichment_proto_enumTypes[0].Descriptor()
}

func (Verdict) Type() protoreflect.EnumType {
	return &file_enrichment_v1_enrichment_proto_enumTypes[0]
}

func (x Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verdict.Descriptor instead.
func (Verdict) EnumDescriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_proto_rawDescGZIP(), []int{0}
}

type ThreatCategory int32

const (
	ThreatCategory_THREAT_CATEGORY_UNSPECIFIED ThreatCategory = 0
	ThreatCategory_THREAT_CATEGORY_MALWARE     ThreatCategory = 1
	ThreatCategory_THREAT_CATEGORY_BOTNET      ThreatCategory = 2
	ThreatCategory_THREAT_CATEGORY_C2          ThreatCategory = 3
	ThreatCategory_THREAT_CATEGORY_EXPLOIT     ThreatCategory = 4
	ThreatCategory_THREAT_CATEGORY_PHISHING    ThreatCategory = 5
	ThreatCategory_THREAT_CATEGORY_SPAM        ThreatCategory = 6
)

// Enum value maps for ThreatCategory.
var (
	ThreatCategory_name = map[int32]string{
		0: "THREAT_CATEGORY_UNSPECIFIED",
		1: "THREAT_CATEGORY_MALWARE",
		2: "THREAT_CATEGORY_BOTNET",
		3: "THREAT_CATEGORY_C2",
		4: "THREAT_CATEGORY_EXPLOIT",
		5: "THREAT_CATEGORY_PHISHING",
		6: "THREAT_CATEGORY_SPAM",
	}
	ThreatCategory_value = map[string]int32{
		"THREAT_CATEGORY_UNSPECIFIED": 0,
		"THREAT_CATEGORY_MALWARE":     1,
		"THREAT_CATEGORY_BOTNET":      2,
		"THREAT_CATEGORY_C2":          3,
		"THREAT_CATEGORY_EXPLOIT":     4,
		"THREAT_CATEGORY_PHISHING":    5,
		"THREAT_CATEGORY_SPAM":        6,
	}
)

func (x ThreatCategory) Enum() *ThreatCategory {
	p := new(ThreatCategory)
	*p = x
	return p
}

func (x ThreatCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThreatCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_enrichment_v1_enrichment_proto_enumTypes[1].Descriptor()
}

func (ThreatCategory) Type() protoreflect.EnumType {
	return &file_enrichment_v1_enrichment_proto_enumTypes[1]
}

func (x ThreatCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThreatCategory.Descriptor instead.
func (ThreatCategory) EnumDescriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_proto_rawDescGZIP(), []int{1}
}

type EnrichmentSource int32

const (
	EnrichmentSource_ENRICHMENT_SOURCE_UNSPECIFIED     EnrichmentSource = 0
	EnrichmentSource_ENRICHMENT_SOURCE_VIRUSTOTAL      EnrichmentSource = 1
	EnrichmentSource_ENRICHMENT_SOURCE_ABUSEIPDB       EnrichmentSource = 2
	EnrichmentSource_ENRICHMENT_SOURCE_OTX             EnrichmentSource = 3
	EnrichmentSource_ENRICHMENT_SOURCE_HYBRID_ANALYSIS EnrichmentSource = 4
)

// Enum value maps for EnrichmentSource.
var (
	EnrichmentSource_name = map[int32]string{
		0: "ENRICHMENT_SOURCE_UNSPECIFIED",
		1: "ENRICHMENT_SOURCE_VIRUSTOTAL",
		2: "ENRICHMENT_SOURCE_ABUSEIPDB",
		3: "ENRICHMENT_SOURCE_OTX",
		4: "ENRICHMENT_SOURCE_HYBRID_ANALYSIS",
	}
	EnrichmentSource_value = map[string]int32{
		"ENRICHMENT_SOURCE_UNSPECIFIED":     0,
		"ENRICHMENT_SOURCE_VIRUSTOTAL":      1,
		"ENRICHMENT_SOURCE_ABUSEIPDB":       2,
		"ENRICHMENT_SOURCE_OTX":             3,
		"ENRICHMENT_SOURCE_HYBRID_ANALYSIS": 4,
	}
)

func (x EnrichmentSource) Enum() *EnrichmentSource {
	p := new(EnrichmentSource)
	*p = x
	return p
}

func (x EnrichmentSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnrichmentSource) Descriptor() protoreflect.EnumDescriptor {
	return file_enrichment_v1_enrichment_proto_enumTypes[2].Descriptor()
}

func (EnrichmentSource) Type() protoreflect.EnumType {
	return &file_enrichment_v1_enrichment_proto_enumTypes[2]
}

func (x EnrichmentSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnrichmentSource.Descriptor instead.
func (EnrichmentSource) EnumDescriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_proto_rawDescGZIP(), []int{2}
}

type EnrichmentStatus int32

const (
	EnrichmentStatus_ENRICHMENT_STATUS_UNSPECIFIED EnrichmentStatus = 0
	EnrichmentStatus_ENRICHMENT_STATUS_PROCESSING  EnrichmentStatus = 2
	EnrichmentStatus_ENRICHMENT_STATUS_COMPLETED   EnrichmentStatus = 3
	EnrichmentStatus_ENRICHMENT_STATUS_FAILED      EnrichmentStatus = 4
	EnrichmentStatus_ENRICHMENT_STATUS_PARTIAL     EnrichmentStatus = 5
)

// Enum value maps for EnrichmentStatus.
var (
	EnrichmentStatus_name = map[int32]string{
		0: "ENRICHMENT_STATUS_UNSPECIFIED",
		2: "ENRICHMENT_STATUS_PROCESSING",
		3: "ENRICHMENT_STATUS_COMPLETED",
		4: "ENRICHMENT_STATUS_FAILED",
		5: "ENRICHMENT_STATUS_PARTIAL",
	}
	EnrichmentStatus_value = map[string]int32{
		"ENRICHMENT_STATUS_UNSPECIFIED": 0,
		"ENRICHMENT_STATUS_PROCESSING":  2,
		"ENRICHMENT_STATUS_COMPLETED":   3,
		"ENRICHMENT_STATUS_FAILED":      4,
		"ENRICHMENT_STATUS_PARTIAL":     5,
	}
)

func (x EnrichmentStatus) Enum() *EnrichmentStatus {
	p := new(EnrichmentStatus)
	*p = x
	return p
}

func (x EnrichmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnrichmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_enrichment_v1_enrichment_proto_enumTypes[3].Descriptor()
}

func (EnrichmentStatus) Type() protoreflect.EnumType {
	return &file_enrichment_v1_enrichment_proto_enumTypes[3]
}

func (x EnrichmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnrichmentStatus.Descriptor instead.
func (EnrichmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_proto_rawDescGZIP(), []int{3}
}

type ThreatIntelData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        EnrichmentSource       `protobuf:"varint,1,opt,name=source,proto3,enum=enrichment.v1.EnrichmentSource" json:"source,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ReportedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	RawData       *structpb.Struct       `protobuf:"bytes,4,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatIntelData) Reset() {
	*x = ThreatIntelData{}
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatIntelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatIntelData) ProtoMessage() {}

func (x *ThreatIntelData) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatIntelData.ProtoReflect.Descriptor instead.
func (*ThreatIntelData) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_proto_rawDescGZIP(), []int{0}
}

func (x *ThreatIntelData) GetSource() EnrichmentSource {
	if x != nil {
		return x.Source
	}
	return EnrichmentSource_ENRICHMENT_SOURCE_UNSPECIFIED
}

func (x *ThreatIntelData) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ThreatIntelData) GetReportedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReportedAt
	}
	return nil
}

func (x *ThreatIntelData) GetRawData() *structpb.Struct {
	if x != nil {
		return x.RawData
	}
	return nil
}

type AggregatedScore struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OverallScore   float32                `protobuf:"fixed32,1,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	Verdict        Verdict                `protobuf:"varint,2,opt,name=verdict,proto3,enum=enrichment.v1.Verdict" json:"verdict,omitempty"`
	TotalSources   int32                  `protobuf:"varint,3,opt,name=total_sources,json=totalSources,proto3" json:"total_sources,omitempty"`
	MaliciousCount int32                  `protobuf:"varint,4,opt,name=malicious_count,json=maliciousCount,proto3" json:"malicious_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AggregatedScore) Reset() {
	*x = AggregatedScore{}
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedScore) ProtoMessage() {}

func (x *AggregatedScore) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedScore.ProtoReflect.Descriptor instead.
func (*AggregatedScore) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_proto_rawDescGZIP(), []int{1}
}

func (x *AggregatedScore) GetOverallScore() float32 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *AggregatedScore) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_UNSPECIFIED
}

func (x *AggregatedScore) GetTotalSources() int32 {
	if x != nil {
		return x.TotalSources
	}
	return 0
}

func (x *AggregatedScore) GetMaliciousCount() int32 {
	if x != nil {
		return x.MaliciousCount
	}
	return 0
}

type IPEnrichmentData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Asn           string                 `protobuf:"bytes,3,opt,name=asn,proto3" json:"asn,omitempty"`
	IsProxy       bool                   `protobuf:"varint,4,opt,name=is_proxy,json=isProxy,proto3" json:"is_proxy,omitempty"`
	IsTor         bool                   `protobuf:"varint,5,opt,name=is_tor,json=isTor,proto3" json:"is_tor,omitempty"`
	IsVpn         bool                   `protobuf:"varint,6,opt,name=is_vpn,json=isVpn,proto3" json:"is_vpn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPEnrichmentData) Reset() {
	*x = IPEnrichmentData{}
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPEnrichmentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPEnrichmentData) ProtoMessage() {}

func (x *IPEnrichmentData) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPEnrichmentData.ProtoReflect.Descriptor instead.
func (*IPEnrichmentData) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_proto_rawDescGZIP(), []int{2}
}

func (x *IPEnrichmentData) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IPEnrichmentData) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *IPEnrichmentData) GetAsn() string {
	if x != nil {
		return x.Asn
	}
	return ""
}

func (x *IPEnrichmentData) GetIsProxy() bool {
	if x != nil {
		return x.IsProxy
	}
	return false
}

func (x *IPEnrichmentData) GetIsTor() bool {
	if x != nil {
		return x.IsTor
	}
	return false
}

func (x *IPEnrichmentData) GetIsVpn() bool {
	if x != nil {
		return x.IsVpn
	}
	return false
}

type DomainEnrichmentData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	CreationDate  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	Registrar     string                 `protobuf:"bytes,3,opt,name=registrar,proto3" json:"registrar,omitempty"`
	ResolvedIps   []string               `protobuf:"bytes,4,rep,name=resolved_ips,json=resolvedIps,proto3" json:"resolved_ips,omitempty"`
	HasSsl        bool                   `protobuf:"varint,5,opt,name=has_ssl,json=hasSsl,proto3" json:"has_ssl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainEnrichmentData) Reset() {
	*x = DomainEnrichmentData{}
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainEnrichmentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainEnrichmentData) ProtoMessage() {}

func (x *DomainEnrichmentData) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainEnrichmentData.ProtoReflect.Descriptor instead.
func (*DomainEnrichmentData) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_proto_rawDescGZIP(), []int{3}
}

func (x *DomainEnrichmentData) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainEnrichmentData) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *DomainEnrichmentData) GetRegistrar() string {
	if x != nil {
		return x.Registrar
	}
	return ""
}

func (x *DomainEnrichmentData) GetResolvedIps() []string {
	if x != nil {
		return x.ResolvedIps
	}
	return nil
}

func (x *DomainEnrichmentData) GetHasSsl() bool {
	if x != nil {
		return x.HasSsl
	}
	return false
}

type HashEnrichmentData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	HashType      string                 `protobuf:"bytes,2,opt,name=hash_type,json=hashType,proto3" json:"hash_type,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileType      string                 `protobuf:"bytes,4,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	IsPacked      bool                   `protobuf:"varint,5,opt,name=is_packed,json=isPacked,proto3" json:"is_packed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashEnrichmentData) Reset() {
	*x = HashEnrichmentData{}
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashEnrichmentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashEnrichmentData) ProtoMessage() {}

func (x *HashEnrichmentData) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashEnrichmentData.ProtoReflect.Descriptor instead.
func (*HashEnrichmentData) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_proto_rawDescGZIP(), []int{4}
}

func (x *HashEnrichmentData) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *HashEnrichmentData) GetHashType() string {
	if x != nil {
		return x.HashType
	}
	return ""
}

func (x *HashEnrichmentData) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *HashEnrichmentData) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *HashEnrichmentData) GetIsPacked() bool {
	if x != nil {
		return x.IsPacked
	}
	return false
}

type URLEnrichmentData struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Url                   string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	FinalUrl              string                 `protobuf:"bytes,2,opt,name=final_url,json=finalUrl,proto3" json:"final_url,omitempty"`
	RedirectCount         int32                  `protobuf:"varint,3,opt,name=redirect_count,json=redirectCount,proto3" json:"redirect_count,omitempty"`
	HasPhishingIndicators bool                   `protobuf:"varint,4,opt,name=has_phishing_indicators,json=hasPhishingIndicators,proto3" json:"has_phishing_indicators,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *URLEnrichmentData) Reset() {
	*x = URLEnrichmentData{}
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLEnrichmentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLEnrichmentData) ProtoMessage() {}

func (x *URLEnrichmentData) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLEnrichmentData.ProtoReflect.Descriptor instead.
func (*URLEnrichmentData) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_proto_rawDescGZIP(), []int{5}
}

func (x *URLEnrichmentData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *URLEnrichmentData) GetFinalUrl() string {
	if x != nil {
		return x.FinalUrl
	}
	return ""
}

func (x *URLEnrichmentData) GetRedirectCount() int32 {
	if x != nil {
		return x.RedirectCount
	}
	return 0
}

func (x *URLEnrichmentData) GetHasPhishingIndicators() bool {
	if x != nil {
		return x.HasPhishingIndicators
	}
	return false
}

type FilePathEnrichmentData struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Path                   string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Extension              string                 `protobuf:"bytes,3,opt,name=extension,proto3" json:"extension,omitempty"`
	IsSystemPath           bool                   `protobuf:"varint,4,opt,name=is_system_path,json=isSystemPath,proto3" json:"is_system_path,omitempty"`
	IsTempPath             bool                   `protobuf:"varint,5,opt,name=is_temp_path,json=isTempPath,proto3" json:"is_temp_path,omitempty"`
	KnownAssociatedMalware []string               `protobuf:"bytes,6,rep,name=known_associated_malware,json=knownAssociatedMalware,proto3" json:"known_associated_malware,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FilePathEnrichmentData) Reset() {
	*x = FilePathEnrichmentData{}
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePathEnrichmentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePathEnrichmentData) ProtoMessage() {}

func (x *FilePathEnrichmentData) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePathEnrichmentData.ProtoReflect.Descriptor instead.
func (*FilePathEnrichmentData) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_proto_rawDescGZIP(), []int{6}
}

func (x *FilePathEnrichmentData) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FilePathEnrichmentData) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *FilePathEnrichmentData) GetIsSystemPath() bool {
	if x != nil {
		return x.IsSystemPath
	}
	return false
}

func (x *FilePathEnrichmentData) GetIsTempPath() bool {
	if x != nil {
		return x.IsTempPath
	}
	return false
}

func (x *FilePathEnrichmentData) GetKnownAssociatedMalware() []string {
	if x != nil {
		return x.KnownAssociatedMalware
	}
	return nil
}

type SourceHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        EnrichmentSource       `protobuf:"varint,1,opt,name=source,proto3,enum=enrichment.v1.EnrichmentSource" json:"source,omitempty"`
	IsHealthy     bool                   `protobuf:"varint,2,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LastChecked   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_checked,json=lastChecked,proto3" json:"last_checked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceHealth) Reset() {
	*x = SourceHealth{}
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceHealth) ProtoMessage() {}

func (x *SourceHealth) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_v1_enrichment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceHealth.ProtoReflect.Descriptor instead.
func (*SourceHealth) Descriptor() ([]byte, []int) {
	return file_enrichment_v1_enrichment_proto_rawDescGZIP(), []int{7}
}

func (x *SourceHealth) GetSource() EnrichmentSource {
	if x != nil {
		return x.Source
	}
	return EnrichmentSource_ENRICHMENT_SOURCE_UNSPECIFIED
}

func (x *SourceHealth) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *SourceHealth) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SourceHealth) GetLastChecked() *timestamppb.Timestamp {
	if x != nil {
		return x.LastChecked
	}
	return nil
}

var File_enrichment_v1_enrichment_proto protoreflect.FileDescriptor

const file_enrichment_v1_enrichment_proto_rawDesc = "" +
	"\n" +
	"\x1eenrichment/v1/enrichment.proto\x12\renrichment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xdb\x01\n" +
	"\x0fThreatIntelData\x127\n" +
	"\x06source\x18\x01 \x01(\x0e2\x1f.enrichment.v1.EnrichmentSourceR\x06source\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12;\n" +
	"\vreported_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reportedAt\x122\n" +
	"\braw_data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\arawData\"\xb6\x01\n" +
	"\x0fAggregatedScore\x12#\n" +
	"\roverall_score\x18\x01 \x01(\x02R\foverallScore\x120\n" +
	"\averdict\x18\x02 \x01(\x0e2\x16.enrichment.v1.VerdictR\averdict\x12#\n" +
	"\rtotal_sources\x18\x03 \x01(\x05R\ftotalSources\x12'\n" +
	"\x0fmalicious_count\x18\x04 \x01(\x05R\x0emaliciousCount\"\x97\x01\n" +
	"\x10IPEnrichmentData\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x10\n" +
	"\x03asn\x18\x03 \x01(\tR\x03asn\x12\x19\n" +
	"\bis_proxy\x18\x04 \x01(\bR\aisProxy\x12\x15\n" +
	"\x06is_tor\x18\x05 \x01(\bR\x05isTor\x12\x15\n" +
	"\x06is_vpn\x18\x06 \x01(\bR\x05isVpn\"\xc9\x01\n" +
	"\x14DomainEnrichmentData\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12?\n" +
	"\rcreation_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fcreationDate\x12\x1c\n" +
	"\tregistrar\x18\x03 \x01(\tR\tregistrar\x12!\n" +
	"\fresolved_ips\x18\x04 \x03(\tR\vresolvedIps\x12\x17\n" +
	"\ahas_ssl\x18\x05 \x01(\bR\x06hasSsl\"\x9c\x01\n" +
	"\x12HashEnrichmentData\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1b\n" +
	"\thash_type\x18\x02 \x01(\tR\bhashType\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tfile_type\x18\x04 \x01(\tR\bfileType\x12\x1b\n" +
	"\tis_packed\x18\x05 \x01(\bR\bisPacked\"\xa1\x01\n" +
	"\x11URLEnrichmentData\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1b\n" +
	"\tfinal_url\x18\x02 \x01(\tR\bfinalUrl\x12%\n" +
	"\x0eredirect_count\x18\x03 \x01(\x05R\rredirectCount\x126\n" +
	"\x17has_phishing_indicators\x18\x04 \x01(\bR\x15hasPhishingIndicators\"\xcc\x01\n" +
	"\x16FilePathEnrichmentData\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\textension\x18\x03 \x01(\tR\textension\x12$\n" +
	"\x0eis_system_path\x18\x04 \x01(\bR\fisSystemPath\x12 \n" +
	"\fis_temp_path\x18\x05 \x01(\bR\n" +
	"isTempPath\x128\n" +
	"\x18known_associated_malware\x18\x06 \x03(\tR\x16knownAssociatedMalware\"\xca\x01\n" +
	"\fSourceHealth\x127\n" +
	"\x06source\x18\x01 \x01(\x0e2\x1f.enrichment.v1.EnrichmentSourceR\x06source\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x02 \x01(\bR\tisHealthy\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12=\n" +
	"\flast_checked\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vlastChecked*\x96\x01\n" +
	"\aVerdict\x12\x17\n" +
	"\x13VERDICT_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eVERDICT_BENIGN\x10\x01\x12\x16\n" +
	"\x12VERDICT_SUSPICIOUS\x10\x02\x12\x15\n" +
	"\x11VERDICT_MALICIOUS\x10\x03\x12\x1a\n" +
	"\x16VERDICT_FALSE_POSITIVE\x10\x04\x12\x13\n" +
	"\x0fVERDICT_UNKNOWN\x10\x05*\xd7\x01\n" +
	"\x0eThreatCategory\x12\x1f\n" +
	"\x1bTHREAT_CATEGORY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17THREAT_CATEGORY_MALWARE\x10\x01\x12\x1a\n" +
	"\x16THREAT_CATEGORY_BOTNET\x10\x02\x12\x16\n" +
	"\x12THREAT_CATEGORY_C2\x10\x03\x12\x1b\n" +
	"\x17THREAT_CATEGORY_EXPLOIT\x10\x04\x12\x1c\n" +
	"\x18THREAT_CATEGORY_PHISHING\x10\x05\x12\x18\n" +
	"\x14THREAT_CATEGORY_SPAM\x10\x06*\xba\x01\n" +
	"\x10EnrichmentSource\x12!\n" +
	"\x1dENRICHMENT_SOURCE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cENRICHMENT_SOURCE_VIRUSTOTAL\x10\x01\x12\x1f\n" +
	"\x1bENRICHMENT_SOURCE_ABUSEIPDB\x10\x02\x12\x19\n" +
	"\x15ENRICHMENT_SOURCE_OTX\x10\x03\x12%\n" +
	"!ENRICHMENT_SOURCE_HYBRID_ANALYSIS\x10\x04*\xb5\x01\n" +
	"\x10EnrichmentStatus\x12!\n" +
	"\x1dENRICHMENT_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cENRICHMENT_STATUS_PROCESSING\x10\x02\x12\x1f\n" +
	"\x1bENRICHMENT_STATUS_COMPLETED\x10\x03\x12\x1c\n" +
	"\x18ENRICHMENT_STATUS_FAILED\x10\x04\x12\x1d\n" +
	"\x19ENRICHMENT_STATUS_PARTIAL\x10\x05BPZNgithub.com/DgHnG36/ioc_enrichment_service/shared/go/enrichment/v1;enrichmentv1b\x06proto3"

var (
	file_enrichment_v1_enrichment_proto_rawDescOnce sync.Once
	file_enrichment_v1_enrichment_proto_rawDescData []byte
)

func file_enrichment_v1_enrichment_proto_rawDescGZIP() []byte {
	file_enrichment_v1_enrichment_proto_rawDescOnce.Do(func() {
		file_enrichment_v1_enrichment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enrichment_v1_enrichment_proto_rawDesc), len(file_enrichment_v1_enrichment_proto_rawDesc)))
	})
	return file_enrichment_v1_enrichment_proto_rawDescData
}

var file_enrichment_v1_enrichment_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_enrichment_v1_enrichment_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_enrichment_v1_enrichment_proto_goTypes = []any{
	(Verdict)(0),                   // 0: enrichment.v1.Verdict
	(ThreatCategory)(0),            // 1: enrichment.v1.ThreatCategory
	(EnrichmentSource)(0),          // 2: enrichment.v1.EnrichmentSource
	(EnrichmentStatus)(0),          // 3: enrichment.v1.EnrichmentStatus
	(*ThreatIntelData)(nil),        // 4: enrichment.v1.ThreatIntelData
	(*AggregatedScore)(nil),        // 5: enrichment.v1.AggregatedScore
	(*IPEnrichmentData)(nil),       // 6: enrichment.v1.IPEnrichmentData
	(*DomainEnrichmentData)(nil),   // 7: enrichment.v1.DomainEnrichmentData
	(*HashEnrichmentData)(nil),     // 8: enrichment.v1.HashEnrichmentData
	(*URLEnrichmentData)(nil),      // 9: enrichment.v1.URLEnrichmentData
	(*FilePathEnrichmentData)(nil), // 10: enrichment.v1.FilePathEnrichmentData
	(*SourceHealth)(nil),           // 11: enrichment.v1.SourceHealth
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
	(*structpb.Struct)(nil),        // 13: google.protobuf.Struct
}
var file_enrichment_v1_enrichment_proto_depIdxs = []int32{
	2,  // 0: enrichment.v1.ThreatIntelData.source:type_name -> enrichment.v1.EnrichmentSource
	12, // 1: enrichment.v1.ThreatIntelData.reported_at:type_name -> google.protobuf.Timestamp
	13, // 2: enrichment.v1.ThreatIntelData.raw_data:type_name -> google.protobuf.Struct
	0,  // 3: enrichment.v1.AggregatedScore.verdict:type_name -> enrichment.v1.Verdict
	12, // 4: enrichment.v1.DomainEnrichmentData.creation_date:type_name -> google.protobuf.Timestamp
	2,  // 5: enrichment.v1.SourceHealth.source:type_name -> enrichment.v1.EnrichmentSource
	12, // 6: enrichment.v1.SourceHealth.last_checked:type_name -> google.protobuf.Timestamp
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_enrichment_v1_enrichment_proto_init() }
func file_enrichment_v1_enrichment_proto_init() {
	if File_enrichment_v1_enrichment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enrichment_v1_enrichment_proto_rawDesc), len(file_enrichment_v1_enrichment_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enrichment_v1_enrichment_proto_goTypes,
		DependencyIndexes: file_enrichment_v1_enrichment_proto_depIdxs,
		EnumInfos:         file_enrichment_v1_enrichment_proto_enumTypes,
		MessageInfos:      file_enrichment_v1_enrichment_proto_msgTypes,
	}.Build()
	File_enrichment_v1_enrichment_proto = out.File
	file_enrichment_v1_enrichment_proto_goTypes = nil
	file_enrichment_v1_enrichment_proto_depIdxs = nil
}
