# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import ioc_service_pb2 as ioc_dot_v1_dot_ioc__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ioc/v1/ioc_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IoCServiceStub(object):
    """IOC SERVICE 

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BatchUpsertIoCs = channel.unary_unary(
                '/ioc.v1.IoCService/BatchUpsertIoCs',
                request_serializer=ioc_dot_v1_dot_ioc__service__pb2.BatchUpsertIoCsRequest.SerializeToString,
                response_deserializer=ioc_dot_v1_dot_ioc__service__pb2.BatchUpsertIoCsResponse.FromString,
                _registered_method=True)
        self.GetIoC = channel.unary_unary(
                '/ioc.v1.IoCService/GetIoC',
                request_serializer=ioc_dot_v1_dot_ioc__service__pb2.GetIoCRequest.SerializeToString,
                response_deserializer=ioc_dot_v1_dot_ioc__service__pb2.GetIoCResponse.FromString,
                _registered_method=True)
        self.GetByValue = channel.unary_unary(
                '/ioc.v1.IoCService/GetByValue',
                request_serializer=ioc_dot_v1_dot_ioc__service__pb2.GetByValueRequest.SerializeToString,
                response_deserializer=ioc_dot_v1_dot_ioc__service__pb2.GetByValueResponse.FromString,
                _registered_method=True)
        self.DeleteIoCs = channel.unary_unary(
                '/ioc.v1.IoCService/DeleteIoCs',
                request_serializer=ioc_dot_v1_dot_ioc__service__pb2.DeleteIoCsRequest.SerializeToString,
                response_deserializer=ioc_dot_v1_dot_ioc__service__pb2.DeleteIoCsResponse.FromString,
                _registered_method=True)
        self.FindIoCs = channel.unary_unary(
                '/ioc.v1.IoCService/FindIoCs',
                request_serializer=ioc_dot_v1_dot_ioc__service__pb2.FindIoCsRequest.SerializeToString,
                response_deserializer=ioc_dot_v1_dot_ioc__service__pb2.FindIoCsResponse.FromString,
                _registered_method=True)
        self.GetIoCStatistics = channel.unary_unary(
                '/ioc.v1.IoCService/GetIoCStatistics',
                request_serializer=ioc_dot_v1_dot_ioc__service__pb2.GetIoCStatisticsRequest.SerializeToString,
                response_deserializer=ioc_dot_v1_dot_ioc__service__pb2.GetIoCStatisticsResponse.FromString,
                _registered_method=True)
        self.IncrementDetectionCount = channel.unary_unary(
                '/ioc.v1.IoCService/IncrementDetectionCount',
                request_serializer=ioc_dot_v1_dot_ioc__service__pb2.IncrementDetectionCountRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetExpired = channel.unary_unary(
                '/ioc.v1.IoCService/GetExpired',
                request_serializer=ioc_dot_v1_dot_ioc__service__pb2.GetExpiredRequest.SerializeToString,
                response_deserializer=ioc_dot_v1_dot_ioc__service__pb2.GetExpiredResponse.FromString,
                _registered_method=True)
        self.EnrichIoC = channel.unary_unary(
                '/ioc.v1.IoCService/EnrichIoC',
                request_serializer=ioc_dot_v1_dot_ioc__service__pb2.EnrichIoCRequest.SerializeToString,
                response_deserializer=ioc_dot_v1_dot_ioc__service__pb2.EnrichIoCResponse.FromString,
                _registered_method=True)
        self.GetEnrichmentStatus = channel.unary_unary(
                '/ioc.v1.IoCService/GetEnrichmentStatus',
                request_serializer=ioc_dot_v1_dot_ioc__service__pb2.GetEnrichmentStatusRequest.SerializeToString,
                response_deserializer=ioc_dot_v1_dot_ioc__service__pb2.GetEnrichmentStatusResponse.FromString,
                _registered_method=True)
        self.GetRelatedIoCs = channel.unary_unary(
                '/ioc.v1.IoCService/GetRelatedIoCs',
                request_serializer=ioc_dot_v1_dot_ioc__service__pb2.GetRelatedIoCsRequest.SerializeToString,
                response_deserializer=ioc_dot_v1_dot_ioc__service__pb2.GetRelatedIoCsResponse.FromString,
                _registered_method=True)


class IoCServiceServicer(object):
    """IOC SERVICE 

    """

    def BatchUpsertIoCs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIoC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetByValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteIoCs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindIoCs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIoCStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrementDetectionCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExpired(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrichIoC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnrichmentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRelatedIoCs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IoCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BatchUpsertIoCs': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchUpsertIoCs,
                    request_deserializer=ioc_dot_v1_dot_ioc__service__pb2.BatchUpsertIoCsRequest.FromString,
                    response_serializer=ioc_dot_v1_dot_ioc__service__pb2.BatchUpsertIoCsResponse.SerializeToString,
            ),
            'GetIoC': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIoC,
                    request_deserializer=ioc_dot_v1_dot_ioc__service__pb2.GetIoCRequest.FromString,
                    response_serializer=ioc_dot_v1_dot_ioc__service__pb2.GetIoCResponse.SerializeToString,
            ),
            'GetByValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetByValue,
                    request_deserializer=ioc_dot_v1_dot_ioc__service__pb2.GetByValueRequest.FromString,
                    response_serializer=ioc_dot_v1_dot_ioc__service__pb2.GetByValueResponse.SerializeToString,
            ),
            'DeleteIoCs': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteIoCs,
                    request_deserializer=ioc_dot_v1_dot_ioc__service__pb2.DeleteIoCsRequest.FromString,
                    response_serializer=ioc_dot_v1_dot_ioc__service__pb2.DeleteIoCsResponse.SerializeToString,
            ),
            'FindIoCs': grpc.unary_unary_rpc_method_handler(
                    servicer.FindIoCs,
                    request_deserializer=ioc_dot_v1_dot_ioc__service__pb2.FindIoCsRequest.FromString,
                    response_serializer=ioc_dot_v1_dot_ioc__service__pb2.FindIoCsResponse.SerializeToString,
            ),
            'GetIoCStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIoCStatistics,
                    request_deserializer=ioc_dot_v1_dot_ioc__service__pb2.GetIoCStatisticsRequest.FromString,
                    response_serializer=ioc_dot_v1_dot_ioc__service__pb2.GetIoCStatisticsResponse.SerializeToString,
            ),
            'IncrementDetectionCount': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrementDetectionCount,
                    request_deserializer=ioc_dot_v1_dot_ioc__service__pb2.IncrementDetectionCountRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetExpired': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExpired,
                    request_deserializer=ioc_dot_v1_dot_ioc__service__pb2.GetExpiredRequest.FromString,
                    response_serializer=ioc_dot_v1_dot_ioc__service__pb2.GetExpiredResponse.SerializeToString,
            ),
            'EnrichIoC': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrichIoC,
                    request_deserializer=ioc_dot_v1_dot_ioc__service__pb2.EnrichIoCRequest.FromString,
                    response_serializer=ioc_dot_v1_dot_ioc__service__pb2.EnrichIoCResponse.SerializeToString,
            ),
            'GetEnrichmentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnrichmentStatus,
                    request_deserializer=ioc_dot_v1_dot_ioc__service__pb2.GetEnrichmentStatusRequest.FromString,
                    response_serializer=ioc_dot_v1_dot_ioc__service__pb2.GetEnrichmentStatusResponse.SerializeToString,
            ),
            'GetRelatedIoCs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelatedIoCs,
                    request_deserializer=ioc_dot_v1_dot_ioc__service__pb2.GetRelatedIoCsRequest.FromString,
                    response_serializer=ioc_dot_v1_dot_ioc__service__pb2.GetRelatedIoCsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ioc.v1.IoCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ioc.v1.IoCService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IoCService(object):
    """IOC SERVICE 

    """

    @staticmethod
    def BatchUpsertIoCs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.IoCService/BatchUpsertIoCs',
            ioc_dot_v1_dot_ioc__service__pb2.BatchUpsertIoCsRequest.SerializeToString,
            ioc_dot_v1_dot_ioc__service__pb2.BatchUpsertIoCsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIoC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.IoCService/GetIoC',
            ioc_dot_v1_dot_ioc__service__pb2.GetIoCRequest.SerializeToString,
            ioc_dot_v1_dot_ioc__service__pb2.GetIoCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetByValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.IoCService/GetByValue',
            ioc_dot_v1_dot_ioc__service__pb2.GetByValueRequest.SerializeToString,
            ioc_dot_v1_dot_ioc__service__pb2.GetByValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteIoCs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.IoCService/DeleteIoCs',
            ioc_dot_v1_dot_ioc__service__pb2.DeleteIoCsRequest.SerializeToString,
            ioc_dot_v1_dot_ioc__service__pb2.DeleteIoCsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindIoCs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.IoCService/FindIoCs',
            ioc_dot_v1_dot_ioc__service__pb2.FindIoCsRequest.SerializeToString,
            ioc_dot_v1_dot_ioc__service__pb2.FindIoCsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIoCStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.IoCService/GetIoCStatistics',
            ioc_dot_v1_dot_ioc__service__pb2.GetIoCStatisticsRequest.SerializeToString,
            ioc_dot_v1_dot_ioc__service__pb2.GetIoCStatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncrementDetectionCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.IoCService/IncrementDetectionCount',
            ioc_dot_v1_dot_ioc__service__pb2.IncrementDetectionCountRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExpired(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.IoCService/GetExpired',
            ioc_dot_v1_dot_ioc__service__pb2.GetExpiredRequest.SerializeToString,
            ioc_dot_v1_dot_ioc__service__pb2.GetExpiredResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnrichIoC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.IoCService/EnrichIoC',
            ioc_dot_v1_dot_ioc__service__pb2.EnrichIoCRequest.SerializeToString,
            ioc_dot_v1_dot_ioc__service__pb2.EnrichIoCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEnrichmentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.IoCService/GetEnrichmentStatus',
            ioc_dot_v1_dot_ioc__service__pb2.GetEnrichmentStatusRequest.SerializeToString,
            ioc_dot_v1_dot_ioc__service__pb2.GetEnrichmentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRelatedIoCs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.IoCService/GetRelatedIoCs',
            ioc_dot_v1_dot_ioc__service__pb2.GetRelatedIoCsRequest.SerializeToString,
            ioc_dot_v1_dot_ioc__service__pb2.GetRelatedIoCsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
