# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import threat_service_pb2 as ioc_dot_v1_dot_threat__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ioc/v1/threat_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ThreatServiceStub(object):
    """THREAT SERVICE 

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BatchUpsertThreats = channel.unary_unary(
                '/ioc.v1.ThreatService/BatchUpsertThreats',
                request_serializer=ioc_dot_v1_dot_threat__service__pb2.BatchUpsertThreatsRequest.SerializeToString,
                response_deserializer=ioc_dot_v1_dot_threat__service__pb2.BatchUpsertThreatsResponse.FromString,
                _registered_method=True)
        self.GetThreat = channel.unary_unary(
                '/ioc.v1.ThreatService/GetThreat',
                request_serializer=ioc_dot_v1_dot_threat__service__pb2.GetThreatRequest.SerializeToString,
                response_deserializer=ioc_dot_v1_dot_threat__service__pb2.GetThreatResponse.FromString,
                _registered_method=True)
        self.DeleteThreats = channel.unary_unary(
                '/ioc.v1.ThreatService/DeleteThreats',
                request_serializer=ioc_dot_v1_dot_threat__service__pb2.DeleteThreatsRequest.SerializeToString,
                response_deserializer=ioc_dot_v1_dot_threat__service__pb2.DeleteThreatsResponse.FromString,
                _registered_method=True)
        self.FindThreats = channel.unary_unary(
                '/ioc.v1.ThreatService/FindThreats',
                request_serializer=ioc_dot_v1_dot_threat__service__pb2.FindThreatsRequest.SerializeToString,
                response_deserializer=ioc_dot_v1_dot_threat__service__pb2.FindThreatsResponse.FromString,
                _registered_method=True)
        self.GetThreatStatistics = channel.unary_unary(
                '/ioc.v1.ThreatService/GetThreatStatistics',
                request_serializer=ioc_dot_v1_dot_threat__service__pb2.GetThreatStatisticsRequest.SerializeToString,
                response_deserializer=ioc_dot_v1_dot_threat__service__pb2.GetThreatStatisticsResponse.FromString,
                _registered_method=True)
        self.GetThreatsByIoC = channel.unary_unary(
                '/ioc.v1.ThreatService/GetThreatsByIoC',
                request_serializer=ioc_dot_v1_dot_threat__service__pb2.GetThreatsByIoCRequest.SerializeToString,
                response_deserializer=ioc_dot_v1_dot_threat__service__pb2.GetThreatsByIoCResponse.FromString,
                _registered_method=True)
        self.GetThreatsByTTP = channel.unary_unary(
                '/ioc.v1.ThreatService/GetThreatsByTTP',
                request_serializer=ioc_dot_v1_dot_threat__service__pb2.GetThreatsByTTPRequest.SerializeToString,
                response_deserializer=ioc_dot_v1_dot_threat__service__pb2.GetThreatsByTTPResponse.FromString,
                _registered_method=True)
        self.CorrelateThreat = channel.unary_unary(
                '/ioc.v1.ThreatService/CorrelateThreat',
                request_serializer=ioc_dot_v1_dot_threat__service__pb2.CorrelateThreatRequest.SerializeToString,
                response_deserializer=ioc_dot_v1_dot_threat__service__pb2.CorrelateThreatResponse.FromString,
                _registered_method=True)
        self.LinkIoCs = channel.unary_unary(
                '/ioc.v1.ThreatService/LinkIoCs',
                request_serializer=ioc_dot_v1_dot_threat__service__pb2.LinkIoCsRequest.SerializeToString,
                response_deserializer=ioc_dot_v1_dot_threat__service__pb2.LinkIoCsResponse.FromString,
                _registered_method=True)
        self.UnlinkIoCs = channel.unary_unary(
                '/ioc.v1.ThreatService/UnlinkIoCs',
                request_serializer=ioc_dot_v1_dot_threat__service__pb2.UnlinkIoCsRequest.SerializeToString,
                response_deserializer=ioc_dot_v1_dot_threat__service__pb2.UnlinkIoCsResponse.FromString,
                _registered_method=True)


class ThreatServiceServicer(object):
    """THREAT SERVICE 

    """

    def BatchUpsertThreats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetThreat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteThreats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindThreats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetThreatStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetThreatsByIoC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetThreatsByTTP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CorrelateThreat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LinkIoCs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlinkIoCs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ThreatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BatchUpsertThreats': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchUpsertThreats,
                    request_deserializer=ioc_dot_v1_dot_threat__service__pb2.BatchUpsertThreatsRequest.FromString,
                    response_serializer=ioc_dot_v1_dot_threat__service__pb2.BatchUpsertThreatsResponse.SerializeToString,
            ),
            'GetThreat': grpc.unary_unary_rpc_method_handler(
                    servicer.GetThreat,
                    request_deserializer=ioc_dot_v1_dot_threat__service__pb2.GetThreatRequest.FromString,
                    response_serializer=ioc_dot_v1_dot_threat__service__pb2.GetThreatResponse.SerializeToString,
            ),
            'DeleteThreats': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteThreats,
                    request_deserializer=ioc_dot_v1_dot_threat__service__pb2.DeleteThreatsRequest.FromString,
                    response_serializer=ioc_dot_v1_dot_threat__service__pb2.DeleteThreatsResponse.SerializeToString,
            ),
            'FindThreats': grpc.unary_unary_rpc_method_handler(
                    servicer.FindThreats,
                    request_deserializer=ioc_dot_v1_dot_threat__service__pb2.FindThreatsRequest.FromString,
                    response_serializer=ioc_dot_v1_dot_threat__service__pb2.FindThreatsResponse.SerializeToString,
            ),
            'GetThreatStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetThreatStatistics,
                    request_deserializer=ioc_dot_v1_dot_threat__service__pb2.GetThreatStatisticsRequest.FromString,
                    response_serializer=ioc_dot_v1_dot_threat__service__pb2.GetThreatStatisticsResponse.SerializeToString,
            ),
            'GetThreatsByIoC': grpc.unary_unary_rpc_method_handler(
                    servicer.GetThreatsByIoC,
                    request_deserializer=ioc_dot_v1_dot_threat__service__pb2.GetThreatsByIoCRequest.FromString,
                    response_serializer=ioc_dot_v1_dot_threat__service__pb2.GetThreatsByIoCResponse.SerializeToString,
            ),
            'GetThreatsByTTP': grpc.unary_unary_rpc_method_handler(
                    servicer.GetThreatsByTTP,
                    request_deserializer=ioc_dot_v1_dot_threat__service__pb2.GetThreatsByTTPRequest.FromString,
                    response_serializer=ioc_dot_v1_dot_threat__service__pb2.GetThreatsByTTPResponse.SerializeToString,
            ),
            'CorrelateThreat': grpc.unary_unary_rpc_method_handler(
                    servicer.CorrelateThreat,
                    request_deserializer=ioc_dot_v1_dot_threat__service__pb2.CorrelateThreatRequest.FromString,
                    response_serializer=ioc_dot_v1_dot_threat__service__pb2.CorrelateThreatResponse.SerializeToString,
            ),
            'LinkIoCs': grpc.unary_unary_rpc_method_handler(
                    servicer.LinkIoCs,
                    request_deserializer=ioc_dot_v1_dot_threat__service__pb2.LinkIoCsRequest.FromString,
                    response_serializer=ioc_dot_v1_dot_threat__service__pb2.LinkIoCsResponse.SerializeToString,
            ),
            'UnlinkIoCs': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlinkIoCs,
                    request_deserializer=ioc_dot_v1_dot_threat__service__pb2.UnlinkIoCsRequest.FromString,
                    response_serializer=ioc_dot_v1_dot_threat__service__pb2.UnlinkIoCsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ioc.v1.ThreatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ioc.v1.ThreatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ThreatService(object):
    """THREAT SERVICE 

    """

    @staticmethod
    def BatchUpsertThreats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.ThreatService/BatchUpsertThreats',
            ioc_dot_v1_dot_threat__service__pb2.BatchUpsertThreatsRequest.SerializeToString,
            ioc_dot_v1_dot_threat__service__pb2.BatchUpsertThreatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetThreat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.ThreatService/GetThreat',
            ioc_dot_v1_dot_threat__service__pb2.GetThreatRequest.SerializeToString,
            ioc_dot_v1_dot_threat__service__pb2.GetThreatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteThreats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.ThreatService/DeleteThreats',
            ioc_dot_v1_dot_threat__service__pb2.DeleteThreatsRequest.SerializeToString,
            ioc_dot_v1_dot_threat__service__pb2.DeleteThreatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindThreats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.ThreatService/FindThreats',
            ioc_dot_v1_dot_threat__service__pb2.FindThreatsRequest.SerializeToString,
            ioc_dot_v1_dot_threat__service__pb2.FindThreatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetThreatStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.ThreatService/GetThreatStatistics',
            ioc_dot_v1_dot_threat__service__pb2.GetThreatStatisticsRequest.SerializeToString,
            ioc_dot_v1_dot_threat__service__pb2.GetThreatStatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetThreatsByIoC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.ThreatService/GetThreatsByIoC',
            ioc_dot_v1_dot_threat__service__pb2.GetThreatsByIoCRequest.SerializeToString,
            ioc_dot_v1_dot_threat__service__pb2.GetThreatsByIoCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetThreatsByTTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.ThreatService/GetThreatsByTTP',
            ioc_dot_v1_dot_threat__service__pb2.GetThreatsByTTPRequest.SerializeToString,
            ioc_dot_v1_dot_threat__service__pb2.GetThreatsByTTPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CorrelateThreat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.ThreatService/CorrelateThreat',
            ioc_dot_v1_dot_threat__service__pb2.CorrelateThreatRequest.SerializeToString,
            ioc_dot_v1_dot_threat__service__pb2.CorrelateThreatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LinkIoCs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.ThreatService/LinkIoCs',
            ioc_dot_v1_dot_threat__service__pb2.LinkIoCsRequest.SerializeToString,
            ioc_dot_v1_dot_threat__service__pb2.LinkIoCsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlinkIoCs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ioc.v1.ThreatService/UnlinkIoCs',
            ioc_dot_v1_dot_threat__service__pb2.UnlinkIoCsRequest.SerializeToString,
            ioc_dot_v1_dot_threat__service__pb2.UnlinkIoCsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
